### PR TITLE
Adds config to show target of ingame partner

### LINKED ISSUE #5233: Showing what the Partner Ai will use in multi-battles
### Description

A common problem in romhacks that have multi-battles is that the  Partner Ai can feel very unpredictable and seem to even screw you over on occasion. This happens a lot in radical red and inclement Emerald (just the first 2 that jumped into my head) to help with this being able to see who the Partner Ai is about to target should drastically help with this. If you knew who the Partner Ai was targeting it makes planning way more predictable, allows you to actually play with the Ai instead of being annoyed by it. 

This can work by having an option (with whatever button is available) that allows you see what move the partner Ai is about to use and who they are targeting. 

### Discord contact info

awakeon

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Closes #5233

The Alternative would be to show the move because I'm not sure if you can fit both into the box.
pokeemerald-2

### CODE REVIEW

**Comment by hedara90** [comment]
It's probably more of an issue with how the AI struct works.
But if the partner decided to use a defensive more (Reflect/Light Screen), the target still reads as the opponent.
And if there are two of the same pokemon out on the field, this way doesn't tell which target it is attacking.

**Comment by AlexOn1ine** [comment]
> It's probably more of an issue with how the AI struct works. But if the partner decided to use a defensive more (Reflect/Light Screen), the target still reads as the opponent. And if there are two of the same pokemon out on the field, this way doesn't tell which target it is attacking.

oh ye, that is a limitation. Basically the best score wins in this case and there will always be a target assigned. I think a workaround could be should the exact move

**Comment by hedara90** [comment]
```
Partner will use:
<MOVE>
```
could work.
Target could be indicated in some other way, crosshair on the HP bar or something, but that might be out of scope.

**Comment by hedara90** [comment]
I played around a bit with it.
combined

**Comment by AlexOn1ine** [comment]
> I played around a bit with it. combined

very pretty. do you want to pr to my branch, paste the code or supersede this one?

**Comment by hedara90** [comment]
> 
> very pretty. do you want to pr to my branch, paste the code or supersede this one?

I can PR to your branch, code might be a bit rough though.

**Comment by AlexOn1ine** [comment]
> > very pretty. do you want to pr to my branch, paste the code or supersede this one?
> 
> I can PR to your branch, code might be a bit rough though.

whatever works best for you.

**Review by hedara90 — APPROVED** [review]

**Pull request merged**
