### PR TITLE
Item Expansion Upstream Sync

### PR DESCRIPTION
**Pull request by ultima-soul**
## Description

First merge details:
Conflicts in:
```
include/pokemon.h
src/battle_script_commands.c: Cmd_handleballthrow
src/data/items.h: SOLARBEAM -> SOLAR_BEAM
src/menu_helpers.c: IsHoldingItemAllowed
src/pokemon.c: CreateBoxMon, CalculateBaseDamage
```
Third merge details:
Conflicts in:
```
.github/workflows/build.yml
data/maps/AbandonedShip_HiddenFloorCorridors/scripts.inc: AbandonedShip_HiddenFloorCorridors_EventScript_Room1Door, AbandonedShip_HiddenFloorCorridors_EventScript_Room2Door, AbandonedShip_HiddenFloorCorridors_EventScript_Room4Door, AbandonedShip_HiddenFloorCorridors_EventScript_Room6Door
data/maps/PetalburgCity_Gym/scripts.inc: PetalburgCity_Gym_EventScript_ShouldGiveEnigmaBerry, PetalburgCity_Gym_EventScript_GiveEnigmaBerry
include/global.h: includes at top
```
Also edited:
```
data/maps/LilycoveCity_ContestLobby/scripts.inc: Added back removed additem
```
## **Discord contact info**

UltimaSoul#4017

### CODE REVIEW

**Review by AsparagusEduardo — DISMISSED** [review]
No big differences compared to my merge.

**Review by ghoulslash — DISMISSED** [review]

**Comment by ultima-soul** [comment]
Updated with details of second and third pret merge plus merge with latest IE commits from yesterday. Review suggestions will be addressed after the review of these additions.

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
Like the previous review, I didn't get any mayor differences between our merges.
However, I do recommend that we incorporate #1964 to the merge (by syncing with IE one last time), as that PR was approved to help minimize conflicts between BE and IE.

Now that I think about it, we'll need to add it anyway before we can merge due to conflicts ^^;

**Comment by ultima-soul** [comment]
Conflicts resolved.

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
