### PR TITLE
Grass/Water Pledge Swamp Animation + Sea of Fire animation tweak

### LINKED ISSUE #3588: Swamp caused by pledge moves is missing an animation
### Description

Title

### Version

upcoming (Edge)

### Upcoming Version

_No response_

### Discord contact info

bassoonian

### PR DESCRIPTION
**Pull request by SonikkuA-DatH**
Resolves #3588 
Gives the Water + Grass combo a unique swamp animation for the lingering effect

https://github.com/user-attachments/assets/8e9a6e4b-2445-4328-91f4-5d78f0c12c08

Also tweaks Sea of Fire to fade bg and mon palettes for its set effect

https://github.com/user-attachments/assets/6db5841f-9080-4645-9e7a-eb7c8f0a28ca

Discord;
dat.ha, originally Dat.HA#6907

### CODE REVIEW

**Comment by hedara90** [comment]
Could the Swamp end of turn effect go BG fade in -> Rain effect -> green shake -> BG Fade out?
Right now I think it looks a bit strange with the half fade(?) then rain then the BG.

**Comment by SonikkuA-DatH** [comment]
> Could the Swamp end of turn effect go BG fade in -> Rain effect -> green shake -> BG Fade out? Right now I think it looks a bit strange with the half fade(?) then rain then the BG.

Like this?

https://github.com/user-attachments/assets/098b3615-9249-4606-baae-cc3a1df3d7c3

**Comment by hedara90** [comment]
> Like this?
> swampC.mp4

Yea, I think that looks better.

**Review by hedara90 — APPROVED** [review]
Looking good (literally)

**Pull request merged**
