### PR TITLE
Added guide to running documentation website locally

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Should've thought of doing this earlier, sorry ^^;

## **People who collaborated with me in this PR**
toonv26526 on Discord for finally giving me the motivation to do this.

## Feature(s) this PR does NOT handle:
There's a second TODO method to install mdBook by downloading files directly. Since I didn't do this, I don't know how this process goes, but still added it as part of the document to show that it is indeed an option.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
conflicts

**Review by pkmnsnfrn — DISMISSED** [review]

**Comment by pkmnsnfrn** [comment]
Not arguing but curious, shouldn't this target `upcoming` since its not a bugfix?

**Comment by AlexOn1ine** [comment]
Would it make sense to link the [original mdbook guide](https://rust-lang.github.io/mdBook/) alongside it?

**Comment by AsparagusEduardo** [comment]
> Would it make sense to link the [original mdbook guide](https://rust-lang.github.io/mdBook/) alongside it? In case people want to learn more

Yep, no problem. Setting this as draft for now in the meantime.

**Comment by AsparagusEduardo** [comment]
Ready for re-review

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
