### PR TITLE
Fix AI tests using PASSES_RANDOMLY

### PR DESCRIPTION
**Pull request by Pawkkie**
## Description
The AI tests weren't having their state reset between PASSES_RANDOMLY runs, which meant that every run but the first one was checking the wrong information. This PR fixes that behaviour, and fixes the one AI test that used PASSES_RANDOMLY while it was broken. This is all mgriffin not me :)

## **People who collaborated with me in this PR**
@mrgriffin Did the whole thing :D

## **Discord contact info**
@Pawkkie

### CODE REVIEW

**Review by AsparagusEduardo — APPROVED** [review]
Lgtm :)

**Comment by Pawkkie** [comment]
I just want to wait for @mrgriffin to double check this because it's entirely their code and they'll have the eye for making sure I haven't missed anything lol

**Comment by AsparagusEduardo** [comment]
> I just want to wait for @mrgriffin to double check this because it's entirely their code and they'll have the eye for making sure I haven't missed anything lol

No problem 👍

**Review by mrgriffin — APPROVED** [review]
Looks good to me too, thanks! :)

**Pull request merged**
