### PR TITLE
Fix the 'bKGD: invalid index' error

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Title.
Currently, the PE branch has about 403 instances of sprites throwing some shitty libpng warning, caused by said sprites having an invalid background color.
This PR solves that by scanning every single sprite in the `graphics/pokemon` folder and setting the correct background color chunk values *([this is what "bKGD" stands for](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html))* to each sprite.
Special thanks to ax6#0162 and Glenn Randers-Pehrson, creator of Pngcrush.

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Can you please add this fix to the PR #1589 ? There seems to be an issue with CI in that PR that's not letting it merge, so might as well use the opportunity

**Comment by LOuroboros** [comment]
> 
> 
> Can you please add this fix to the PR #1589 ? There seems to be an issue with CI in that PR that's not letting it merge, so might as well use the opportunity

Uh, I don't think I can modify someone else's PR? xD ...

Do you want me to re-submit myself? I would be fine with it if it's fine by @cynderquil.

**Comment by AsparagusEduardo** [comment]
> Uh, I don't think I can modify someone else's PR? xD ...
> 
> Do you want me to re-submit myself? I would be fine with it if it's fine by @cynderquil.

What I meant to say is that if you could add that PR's sprite into your PR, with the bKGD fix

**Comment by LOuroboros** [comment]
> 
> 
> > Uh, I don't think I can modify someone else's PR? xD ...
> > Do you want me to re-submit myself? I would be fine with it if it's fine by @cynderquil.
> 
> What I meant to say is that if you could add that PR's sprite into your PR, with the bKGD fix

Ah, sure thing.

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
