### PR TITLE
Fix AI crit calculations

### PR DESCRIPTION
**Pull request by Sneed69**
## Description
Fixes AI not recording Battle/Shell Armor abilities
Fixes AI not considering guaranteed crits
Renames various variables and functions to "odds" from "chance" for clarity.

## **Discord contact info**
duke5614

### CODE REVIEW

**Comment by ghoulslash** [comment]
On the topic of this PR - I'm wondering if we should introduce AI logic configs, e.g. does the AI compute expected crit damage or ignore crit damage altogether

**Comment by AlexOn1ine** [comment]
> On the topic of this PR - I'm wondering if we should introduce AI logic configs, e.g. does the AI compute expected crit damage or ignore crit damage altogether

Any reason this could be useful?

**Comment by ghoulslash** [comment]
> > On the topic of this PR - I'm wondering if we should introduce AI logic configs, e.g. does the AI compute expected crit damage or ignore crit damage altogether
> 
> Any reason this could be useful?

allow users to customize their overall AI logic easily. As far as not checking expected damage from crit - there are likely scenarios where we don't want to give preference to something with a higher crit rate. Because we use a scoring system its not clear that something like night slash would not get used over a move that would otherwise KO the foe, for example

**Comment by AlexOn1ine** [comment]
> > > On the topic of this PR - I'm wondering if we should introduce AI logic configs, e.g. does the AI compute expected crit damage or ignore crit damage altogether
> > 
> > 
> > Any reason this could be useful?
> 
> allow users to customize their overall AI logic easily. As far as not checking expected damage from crit - there are likely scenarios where we don't want to give preference to something with a higher crit rate if its not guaranteed. Because we use a scoring system its not clear that something like night slash would not get used over a move that would otherwise KO the foe, for example

I agree but I think a guaranteed crit should be always seen

**Comment by Sneed69** [comment]
For what it's worth, using Gen 7+ crit settings, the AI currently only considers crits at 50% or 100% chance.

**Comment by AlexOn1ine** [comment]
> For what it's worth, using Gen 7+ crit settings, the AI currently only considers crits at 50% or 100% chance.

Maybe the default should be 100 with a config that can change it is 50?

**Comment by ghoulslash** [comment]
> > For what it's worth, using Gen 7+ crit settings, the AI currently only considers crits at 50% or 100% chance.
> 
> Maybe the default should be 100 with a config that can change it is 50?

This makes sense to me

**Comment by Pawkkie** [comment]
> > For what it's worth, using Gen 7+ crit settings, the AI currently only considers crits at 50% or 100% chance.
> 
> Maybe the default should be 100 with a config that can change it is 50?

This would be another fun control to bake into the risky AI flag too :)

**Comment by AlexOn1ine** [comment]
> > > For what it's worth, using Gen 7+ crit settings, the AI currently only considers crits at 50% or 100% chance.
> > 
> > 
> > Maybe the default should be 100 with a config that can change it is 50?
> 
> This would be another fun control to bake into the risky AI flag too :)

I like that idea

**Comment by AlexOn1ine** [comment]
Seems wrong 
pokeemerald-46

**Comment by Sneed69** [comment]
> Seems wrong pokeemerald-46

Those look like the correct values for a 50% crit slash.
This PR does not affect slash at all, only moves like frost breath and flower trick.

**Comment by AlexOn1ine** [comment]
> > Seems wrong pokeemerald-46
> 
> Those look like the correct values for a 50% crit slash. This PR does not affect slash at all, only moves like frost breath and flower trick.

slash has 70 base power and absol has super luck. So crit ratio is 50%. If it didn't increase it the damage should have been the same as headbutt

**Comment by Sneed69** [comment]
Why wouldn't it increase it?

**Comment by AlexOn1ine** [comment]
> Why wouldn't it increase it?

> For what it's worth, using Gen 7+ crit settings, the AI currently only considers crits at 50% or 100% chance

**Comment by AlexOn1ine** [comment]
> > Why wouldn't it increase it?


> > For what it's worth, using Gen 7+ crit settings, the AI currently only considers crits at 50% or 100% chance

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
