### PR TITLE
Test battlers always have their forced abilities

### PR DESCRIPTION
**Pull request by Sneed69**
## **Discord contact info**
duke5614

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
I understand the idea and this make sense for a personal project but I'm not sure if we should encourage the usage of illegal abilities. This is something we've tried to avoid.

**Comment by Sneed69** [comment]
image

**Comment by mrgriffin** [comment]
I wouldn't say we avoid it because it doesn't work. We avoid it because the core concept of the tests is to automate the kind of testing that a human would do in-game; so everything that gets added which isn't possible in-game erodes that core concept, and thus must meet a very high bar to be included.

Illegal abilities were only introduced because people implemented the gen 9 abilities before the species were available. At this point it might not actually be used and could be removed if there was an alternative approach to handling that situation—perhaps placeholder species which are off by default but on when `TESTING` is defined is an acceptable alternative which preserves the "battles are legal".

**Comment by AlexOn1ine** [comment]
I understand there is an issue with tests when users change their data but this is just a band-aid and doesn't solve the core problem.

**Comment by Sneed69** [comment]
I am not adding any features, I'm just making an existing own fully operational. If the feature itself is a band-aid then remove it entirely instead of leaving it half working.

**Comment by AlexOn1ine** [comment]
> If the feature itself is a band-aid then remove it entirely instead of leaving it half working.

Good point! 

If nobody has anything against I'll remove it later.

**Comment by AlexOn1ine** [comment]
Could you remove the test and allign the if blocks? 
e.g.:
```
        #if TESTING
        if (gTestRunnerEnabled)
        {
            u32 side = GetBattlerSide(battler);
            u32 partyIndex = gBattlerPartyIndexes[battler];
            if (TestRunner_Battle_GetForcedAbility(side, partyIndex))
                gBattleMons[battler].ability = gBattleStruct->overwrittenAbilities[battler] = TestRunner_Battle_GetForcedAbility(side, partyIndex);
        }
        #endif
```

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
