### PR TITLE
Added EV setters to the debug menu's "Give Pokémon Complex"

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Someone asked for a way to give themself a Pokémon with specific EV, presumably for testing purposes.
For whatever reason, the debug menu doesn't let you do that.
So I went and implemented the relevant functionality because the more debug tools our debug menu has, the better imo.

Misc. Changes:
-Updated the text strings for the 2 "Give Pokémon" options used by the debug menu.

## **Discord contact info**
lunos4026

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Was 255 chosen intentionally instead of 252? Also do we care about illegal stats (maxed out across the board)? I personally don't, It's a debug menu and users should be aware.

**Comment by LOuroboros** [comment]
> Was 255 chosen intentionally instead of 252?
"Yes". I just set them to 255 because that's the limit in Gen. 3 and I didn't think about things too much, but I brought up the idea of taking this chance to use constants such as `MAX_PER_STAT_EVS`  not just in the new `DebugAction_Give_Pokemon_SelectEVs` but also inside `DebugAction_Give_Pokemon_SelectIVs` in the Discord server :eyes:

> Also do we care about illegal stats (maxed out across the board)?

That's a good question. I personally don't, but I'm not against skipping to the move selection if the total sum of EV reaches 510 if a majority prefers that.

**Comment by Bassoonian** [comment]
I would absolutely use the existing constants, even if it's just to avoid magic numbers. As for going over the maximum amount of EVs, perhaps you could also display the total amount of EVs on the window and limit it from going higher if it would go higher than 510 (`MAX_TOTAL_EVS`)?

**Comment by LOuroboros** [comment]
I pushed a commit I had lying around in another branch.

I still need to look into the whole "display current amount of EV and not let the user go higher than `MAX_TOTAL_EVS`" matter.

I did something cursed as an experiment, which I don't intend to push, and then I kinda just stopped looking into it 😂

**Comment by LOuroboros** [comment]
Since I couldn't manage to get a text string displaying the amount of current and max EV that updates and stuff, I just pushed what I had after a bit of cleaning up.

Currently, if you assign a total sum of EV that is bigger than `MAX_TOTAL_EVS`, the code takes you back to the HP EV setup until you input a total sum of EV equal to 510 or less.

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
