### PR TITLE
Added footprints for the Gen. 4 species

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
As stated in #546 every single new species introduced in the pokemon_expansion branch is currently missing their footprints.
I decided to handle the Gen. 4 ones since I had already done them back in my first decomp related project.

## **Discord contact info**
Lunos#4026

## **Misc. Notes**

I'll need input on a few things, mainly:

* Cases like Shellos, Gastrodon, Burmy, Wormadam or Rotom.

* Whether some of them are misaligned and I should correct them or not. I feel like a few of them are, personally.

Showcase: https://streamable.com/tl33ns

If there's anything wrong with it, let me know.

### CODE REVIEW

**Comment by LOuroboros** [comment]
Dropping here a note. Currently, the bit depth of the footprints' sprites in this PR is 8bpp, which is inconsistent as vanilla's footprint sprites have a bit depth of 1bpp.
I'll try to correct that.

**Comment by LOuroboros** [comment]
Bam, done. The Gen. 4 footprint sprites have Bit Depth 1 now, just like the vanilla footprints. Gotta say, I think I fell in love with ImageMagick.

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
Most of the misalignments seem to be because it's trying to fit a footprint with an odd with into the even width circle. We can't really do much about it... Besides that, here's a couple suggestions that could be adjusted:

Starly: 1px up
Staravia: 1px up
Staraptor: 1px up
Bidoof: 1px up
Luxray: 1px up
Lucario: 1px up
Regigigas: 1px left

**Comment by LOuroboros** [comment]
> 
> 
> Most of the misalignments seem to be because it's trying to fit a footprint with an odd with into the even width circle. We can't really do much about it... Besides that, here's a couple suggestions that could be adjusted:
> 
> Starly: 1px up
> Staravia: 1px up
> Staraptor: 1px up
> Bidoof: 1px up
> Luxray: 1px up
> Lucario: 1px up
> Regigigas: 1px left

Done :eyes:

**Review by AsparagusEduardo — APPROVED** [review]

**Review by ExpoSeed — APPROVED** [review]
I checked all footprints for incorrect footprints, they're all correct

**Pull request merged**
