### PR TITLE
Used the COMPOUND_STRING macro to unify item descriptions and item data

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
About 3 hours and a half ago, I was indirectly reminded of #3243.
Somehow, that made me think that having the text strings that compose an item's descriptions in an entirely separate file is a pita when you decide to add entirely new items, TM/HM or not.
The very first way to deal with that I thought was to use the `COMPOUND_STRING` macro that SBird added in #2733 to write the strings directly in the `.description` field of each item.
That worked.
Then I gauged the public opinion in the Discord server, and most of the people seemed to be on board with the idea.
So I proceeded to ditch every single dedicated text string for item descriptions and submit a PR to the expansion.

This PR will remain a Draft until #3284 and #3274 are merged. Personal choice. I don't wanna trouble kittenchilly 😆 
Any early reviews would be appreciated.

## **Discord contact info**
lunos4026

### CODE REVIEW

**Review by mrgriffin — APPROVED** [review]
I love this change.

I think I like your formatting better than the other obvious alternative:
```c
        .description = COMPOUND_STRING(
            "A tool used for\n"
            "catching wild\n"
            "Pokémon."
        ),
```
But I suppose reasonable people could disagree about whether it's better to have 5 lines with little indentation, or 3 lines with a lot of indentation. I'll let people fight it out in the comments to this PR :rofl:

**Review by DizzyEggg — APPROVED** [review]

**Comment by DizzyEggg** [comment]
This is a great PR Lunos. Formatting is better too. Is there something missing since you set it as a draft?

**Comment by LOuroboros** [comment]
> This is a great PR Lunos. Formatting is better too. Is there something missing since you set it as a draft?

> This PR will remain a Draft until #3284 and #3274 are merged. Personal choice. I don't wanna trouble kittenchilly 😆

**Comment by Bassoonian** [comment]
Both PRs you were waiting for have been merged in 👀

**Comment by LOuroboros** [comment]
> Both PRs you were waiting for have been merged in 👀

Hell yeah!

Gonna pull and solve the merge conflicts then.

**Comment by LOuroboros** [comment]
Alright, after some crazy developments on my end and Git moving me to a non-branch for reasons that I don't understand, this PR is ready for review.

I pulled upcoming, solved the conflicts and moved the definitions of `CONFUSE_BERRY_HEAL_FRACTION` back to `src/data/items.h`.

The definition of `CONFUSE_BERRY_HP_FRACTION` which was introduced in b93dfb9d5980de2a72d3e45faae471a153c808c4 are kept in `include/constants/items.h` because the file in which they're used, `src/battle_ai_switch_items.c`, can't read preproc constants defined inside `src/data/items.h`.

**Comment by LOuroboros** [comment]
And now I had to move `CONFUSE_BERRY_HEAL_FRACTION` back for the same reasons.

I *really* don't like to have item data related constants split across 2 files like that, but I cba to think of a good solution to address that so I'll leave that to whoever else may care enough. It's not in-scope for this PR regardless.

**Comment by Bassoonian** [comment]
Like what we do for moves and Pokédex entries that share a description, I think we should have some static declarations at the top of the file for shared descriptions (I'm thinking e.g. Poké Toy and Fluffy Tail) to avoid duplicate strings (that modern doesn't consolidate, as we have found out).

**Comment by LOuroboros** [comment]
> Like what we do for moves and Pokédex entries that share a description, I think we should have some static declarations at the top of the file for shared descriptions (I'm thinking e.g. Poké Toy and Fluffy Tail) to avoid duplicate strings (that modern doesn't consolidate, as we have found out).

I don't like the inconsistency that creates at the time of editing the strings, and it's not like item description strings aren't duplicated even in vanilla, but I'll look into it.

**Comment by LOuroboros** [comment]
Ready for re-review.

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
