### PR TITLE
Revival Blessing fixes + Using Lunar Blessing's animation

### PR DESCRIPTION
**Pull request by ghoulslash**
#5471 but targeting master

Also fixes animation

### CODE REVIEW

**Comment by ghoulslash** [comment]
@AsparagusEduardo revival blessing PR to master is ready

**Comment by Bassoonian** [comment]
Lunar Blessing's animation is also broken and imo an already broken animation should not be preventing this bugfix from being merged

**Comment by AsparagusEduardo** [comment]
Please wait until I PR the test improvements to support Revival Blessing

**Comment by ghoulslash** [comment]
animation fixed in `[469d533](https://github.com/rh-hideout/pokeemerald-expansion/pull/5490/commits/469d533fa6c358d655fd427742ce044378342de3)`, waiting for edu's PR

**Comment by AsparagusEduardo** [comment]
Forgot to post it here, but PR is ready: https://github.com/ghoulslash/pokeemerald/pull/25

**Comment by ghoulslash** [comment]
added edu's PR, ready for review

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
