### PR TITLE
Remove agbcc

### LINKED ISSUE #4946: Drop agbcc from CI workflow
### Description

Most features are being tested on modern without checking agbcc anyway, so keeping our agbcc CI workflow doesn't make sense to me.
I don't believe we should get rid of `make agbcc` though, as it's still gonna be useful for some users and ourselves when merging from upstream pret.

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

AsparagusEduardo

### PR DESCRIPTION
**Pull request by mrgriffin**
Title, in preparation for 1.10.

Fixes #4946

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
is there anything left for the pr to be merged?

**Comment by mrgriffin** [comment]
I _think_ it works and removes everything it should/doesn't remove everything it shouldn't, but a second set of eyes could be good?

**Comment by hedara90** [comment]
> How does this handle `if MODERN` blocks in the existing codebase?

`MODERN` is still set to 1 in the `Makefile` so they should work the same

**Review by hedara90 — COMMENTED** [review]
The `#if MODERN` blocks in the code are also unnecessary now since it's always modern.
I tested compiling with those removed, and all tests pass at least

**Comment by mrgriffin** [comment]
Good comments:
- `#if MODERN` these _could_ go. I think a lot of them come from pret? All the `#if BUGFIX`es do, and those are all essentially forced on under modern. I felt like that could be quite invasive, but you're welcome to PR to my PR if the invasiveness is worth it :)
- `build/modern` and `build/modern-test`. I didn't think about these, but I think they probably shouldn't just change to what the agbcc directories are, because I think that would cause people who update to 1.10 to try and link modern-compiled and agbcc-compiled artifacts until they `make clean` to remove all the agbcc-compiled ones?
- `tidymodern` yeah, that could be just something else. What would you want to call it? `tidy` currently does `tidymodern` and `tidycheck`. I suppose it could be inlined into `tidy`? I doubt there's much use for "delete the ROM build artifacts, but not the test build artifacts"?

**Comment by hedara90** [comment]
I can PR the `#if MODERN` removal after this is in, keeps the invasiveness down.
Build directories, we can wait with that until 1.11 (or 1.10.x) then, by then all `agbcc` artifacts should be gone.
And yea, just `tidy` works I'd say, if someone really needs "delete the ROM build artifacts, but not the test build artifacts", they can scream at me.

**Comment by tertu-m** [comment]
So to be clear I think the code in those blocks should stay around (most of it seems like things like alignment checks)

**Comment by tertu-m** [comment]
Okay in that case if MODERN is set to 1 i have no issues with that.

**Review by hedara90 — APPROVED** [review]
Further changes to clean up the remnants of the `agbcc`/`modern` split can be addressed at a later time.

**Pull request merged**
