### PR TITLE
remove fno-toplevel-reorder

### PR DESCRIPTION
**Pull request by DizzyEggg**
Weirdly enough... it works for me. 
If CI passes, I'd appreciate others to pull and build it locally to see if it works for them too.

### CODE REVIEW

**Comment by hedara90** [comment]
I didn't see any immediate issues with it outside of the Birch into platform colors being wrong.

**Comment by AsparagusEduardo** [comment]
> I didn't see any immediate issues with it outside of the Birch into platform colors being wrong.

Gotta do a pret merge to fix this

**Comment by AsparagusEduardo** [comment]
Once #5845 is merged, this should too

**Review by SBird1337 — APPROVED** [review]
I'd like to eventually remove those extra compilation flags for those files, but for now I'm just gonna yolo this one.

**Pull request merged**
