### PR TITLE
Fixes cantBeSurpressed ability check for breakable abilities

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Title

### CODE REVIEW

**Comment by Pawkkie** [comment]
I know you don't love adding new codebase comments, but is there a particular reason we aren't just adding an edge case for Disguise instead of changing the overall handling, which seems to break at least Zero to Hero?

By which I mean something like

```diff
    if (gAbilitiesInfo[gBattleMons[battler].ability].cantBeSuppressed)
    {
        // Edge case: pokemon under the effect of gastro acid transforms into a pokemon with Comatose (Todo: verify how other unsuppressable abilities behave)
        if (gBattleMons[battler].status2 & STATUS2_TRANSFORMED
            && gStatuses3[battler] & STATUS3_GASTRO_ACID
            && gBattleMons[battler].ability == ABILITY_COMATOSE)
                return ABILITY_NONE;
+        // Edge case: Disguise is still breakable
+        if (IsMoldBreakerTypeAbility(gBattleMons[gBattlerAttacker].ability) && gBattleMons[battler].ability == ABILITY_DISGUISE)
+            return ABILITY_NONE;
        return gBattleMons[battler].ability;
    }
```
which passes existing tests and your new one

**Comment by Pawkkie** [comment]
Oh even better, then how about just
```diff
        // Edge case: pokemon under the effect of gastro acid transforms into a pokemon with Comatose (Todo: verify how other unsuppressable abilities behave)
        if (gBattleMons[battler].status2 & STATUS2_TRANSFORMED
            && gStatuses3[battler] & STATUS3_GASTRO_ACID
            && gBattleMons[battler].ability == ABILITY_COMATOSE)
                return ABILITY_NONE;

        // Edge case: Moves that can't be suppressed can still be broken
+        if (IsMoldBreakerTypeAbility(gBattleMons[gBattlerAttacker].ability))
+            return ABILITY_NONE;
            
        return gBattleMons[battler].ability;
```

**Comment by AlexOn1ine** [comment]
> Oh even better, then how about just
> 
> ```diff
>         // Edge case: pokemon under the effect of gastro acid transforms into a pokemon with Comatose (Todo: verify how other unsuppressable abilities behave)
>         if (gBattleMons[battler].status2 & STATUS2_TRANSFORMED
>             && gStatuses3[battler] & STATUS3_GASTRO_ACID
>             && gBattleMons[battler].ability == ABILITY_COMATOSE)
>                 return ABILITY_NONE;
> 
>         // Edge case: Moves that can't be suppressed can still be broken
> +        if (IsMoldBreakerTypeAbility(gBattleMons[gBattlerAttacker].ability))
> +            return ABILITY_NONE;
>             
>         return gBattleMons[battler].ability;
> ```

You are skipping all the following checks in that function. Also I wouldn't say it is an edge case.

**Comment by Pawkkie** [comment]
> You are skipping all the following checks in that function. Also I wouldn't say it is an edge case.
Yeah sorry I transitioned from PC to on my phone in transit, I just meant to suggest using a conditional like that there as a base as it passes all tests.

I'd take the approach of just making the mold breaker check a function but up to you what you'd prefer :D

**Comment by AlexOn1ine** [comment]
@Pawkkie I updated the pr. I skip the return if it is a breakable ability. Also I refactored the moldbreaker check a bit to make it more readable.

**Comment by Pawkkie** [comment]
> @Pawkkie I updated the pr. I skip the return if it is a breakable ability. Also I refactored the moldbreaker check a bit to make it more readable.

Your update perfectly ninja'd my last comment which suggested exactly what you did, sweet :D 

I will merge once the checks finishes if that's acceptable, this looks great to me eye.

**Comment by AlexOn1ine** [comment]
> > @Pawkkie I updated the pr. I skip the return if it is a breakable ability. Also I refactored the moldbreaker check a bit to make it more readable.
> 
> Your update perfectly ninja'd my last comment which suggested exactly what you did, sweet :D
> 
> I will merge once the checks finishes if that's acceptable, this looks great to me eye.

sec, there is still a problem

**Comment by AlexOn1ine** [comment]
As suggested I made a new function. This was solved cleaner this way because I had to skip the suppress checks.

**Comment by Pawkkie** [comment]
Yeah this looks SUPER readable, more so than the original even before the needed modifications. Will just wait on checks :)

**Review by Pawkkie — APPROVED** [review]
Hollar at me if I'm doing this incorrectly I'm new to this lol

**Pull request merged**
