### PR TITLE
add debug build target

### PR DESCRIPTION
**Pull request by u8-Salem**
since I messed up the branch on #4664 I closed that pr and cherry picked to a new branch. 

Adds a debug build target

## Description
`make debug` will build separate artifacts in `build/(modern-)debug` and enable `-Og`  and `-g`.
Also adds the option to run any build with `NOOPT=1` completely disable optimization by using `-O0`

preproc directives regarding debug menus have been removed and integrated in the regular control flow. 

Also fixes an error that reveals when building with debug (Werror=maybe-uninitialized)

## **Discord contact info**
u8.salem

### CODE REVIEW

**Comment by tertu-m** [comment]
Everything in the code looks OK so far. I'll try this out later.

**Comment by AlexOn1ine** [comment]
Could we add the settings from `make debug` to `make check` as well?

**Comment by tertu-m** [comment]
Personally I would like to have a release and a debug target for make check in case an issue happens only on release or only on debug builds.

**Comment by AlexOn1ine** [comment]
> Personally I would like to have a release and a debug target for make check in case an issue happens only on release or only on debug builds.

Not following why would it be a problem on `make check`? It would be nice to have immediate access to DebugPrint in tests.

**Comment by AlexOn1ine** [comment]
> Everything in the code looks OK so far. I'll try this out later.

tertu, did you look into it? :eyes:

**Comment by tertu-m** [comment]
I don't actually support disabling the debug menu in release builds categorically. @u8-Salem could you add a compile option to re-enable it?

**Comment by AlexOn1ine** [comment]
> I don't actually support disabling the debug menu in release builds categorically. @u8-Salem could you add a compile option to re-enable it?

That was something @SBird1337 requested us todo which I agree with. A release build shouldn't have any debug features. Though I understand it will be a bit annoying for us to always compile with `make debug`

**Comment by tertu-m** [comment]
> > I don't actually support disabling the debug menu in release builds categorically. @u8-Salem could you add a compile option to re-enable it?
> 
> That was something @SBird1337 requested us todo which I agree with. A release build shouldn't have any debug features. Though I understand it will be a bit annoying for us to always compile with `make debug`

Ah, apologies, I phrased that wrong. More accurately, what I meant is that I think the debug menu should be not linked to the level of optimization the ROM is built with. So maybe the debug menu is behind NDEBUG, and there's an option that lets you do `make DEBUG=1`, which undefs NDEBUG.

**Comment by hedara90** [comment]
I don't know if it's feasible to automate or if it should be up to users to keep track of it.
But when running `make NOOPT=1`, it will only be applied to files that have been changed since last compile. So if nothing has changed the ROM will be identical (tested, with Comp Syntax off so no files change). You currently have to manually run some clean/tidy command.

**Review by tertu-m — APPROVED** [review]

**Pull request merged**
