### PR TITLE
Sets neutral nature and ability 0 as default in trainer control

### LINKED ISSUE #3641: Vanilla trainers' Pokémon have wrong PIDs/Natures
### Description

#3114 changed all the vanilla trainers to `TrainerMonCustomized`, but `TrainerMonCustomized` generates its PIDs [using a CRC32 of the party member being generated](<https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/battle_main.c#L1889-1894>), whereas vanilla generates its PIDs from a [hash of the trainer name](<https://github.com/pret/pokeemerald/blob/master/src/battle_main.c#L1998-1999>) combined with [hashes of the species names](<https://github.com/pret/pokeemerald/blob/master/src/battle_main.c#L2007-L2008>) that have previously been generated.

The PID affects the nature of the generated Pokémon. The gender and ability are unaffected because the hash is `<< 8`.

Note also that because the species names are part of the hash, decapitalization would also affect the vanilla hash and alter the natures.

Because of the above, I think the best fix for this would be to explicitly list the natures in `src/data/trainer_parties.h`. We probably shouldn't just change back to a vanilla-compatible hash because that would change the natures of parties that were balanced around the current nature, although perhaps in practice that wouldn't be a big problem.

### Version

1.6.2 (Default)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #4123: Setting trainer pokemon's nature or gender can inadverdently change their default nature, gender, and ability.
### Description

Setting a nature or gender in `trainer_parties.h` results in any unset nature, gender, or ability liable to be inadvertently changed from its default. This relates to #3641 which shows trainers already don't have their vanilla emerald PID/nature. That issue's proposed solution of explicitly setting trainer pokemon natures in `trainer_parties.h` will fix natures but in the process break gender and ability from their vanilla values. The following shows that setting nature can change a pokemon's default gender (even with the `personalityHash` problem from #3641 commented out).

Screenshot 2024-02-03 030837
Screenshot 2024-02-03 030420

To explain, the personality value of this poochyena is 136 and it has whatever nature is 11. The modify nature function simply adds or subtracts from personality to get to the new nature. If I set the nature to 1, it subtracts 10 from 136 to get 126. Only 126 is below the gender ratio of 127 for poochyena, so it becomes female. "Life uhhhh finds a way."

The solutions I see are:
1. Don't care about vanilla nature, gender, ability, or default values being changed by unrelated set values.
2. Restore `nameHash` from vanilla emerald to get the nature, then generate a PID from nature, gender, and ability all at once.
3. Go ahead in setting vanilla natures in `trainer_parties.h` but still generate a PID like above.

I wrote a function that can generate a PID like I mentioned, just waiting for the greenlight. I think solution 3 makes the most sense as `nameHash` is only useful for getting the nature. But, nature is the only value of the personality-derived values (nature, gender, ability) that isn't immediately obvious from looking at the code and most trainer pokemon natures can't be looked up anywhere.

### Version

1.7.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

hungry_pickle

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #4123
Fixes #3641

Since the hardy nature is the default now the macro for natures is not needed anymore.

### CODE REVIEW

**Comment by Bassoonian** [comment]
While I think a neutral nature is good, abilities defaulting to slot 0 when undefined is something I find a little bit harder to accept, since knowing that each regular trainer's mon has the ability in their first slot allows for unfair advantages as opposed to it being inpredictable. I don't immediately have a solution other than just randomising it, which I think is a better solution

**Comment by AlexOn1ine** [comment]
> abilities defaulting to slot 0 when undefined is something I find a little bit harder to accept
It already defaults to zero in like 99% of cases without this change. This changed was solely based on pickels recommendation.

**Comment by AlexOn1ine** [comment]
> I don't immediately have a solution other than just randomising it, which I think is a better solution

Tbh, I don't think this is a good change. Natute is something that will be rarely known to player and usually has a downside when you get a bad one but having ability set to slot one is the standard vanilla behavior since gen3 and most people are aware of that. Changing it here would cause more harm then good imo.

**Comment by mrgriffin** [comment]
For avoidance of doubt, by randomization I think we mean "based on the hash" so that it's arbitrary but consistent. Literally using `Random()` would mean that if you white out and battle the trainer again that they could have different values, which seems like a weird choice!

I don't have any strong opinions about which option is better, except to note that people might be currently relying on the behavior of getting the first ability without having explicitly specified `.ability`.

**Comment by Bassoonian** [comment]
> having ability set to slot one is the standard vanilla behavior since gen3

Is it really? I had no idea, oops

That asides, I do think the hash-based "randomisation" could be ideal (maybe with a config, then, if it's not vanilla)

**Comment by AlexOn1ine** [comment]
> That asides, I do think the hash-based "randomisation" could be ideal (maybe with a config, then, if it's not vanilla)

I wouldn't mind a config. I'll see what I can do.

**Comment by AlexOn1ine** [comment]
Ready for re-review.

Added config `RANDOM_MON_ABILITY` and set it to false, specifically because of this:

> I don't have any strong opinions about which option is better, except to note that people might be currently relying on the behavior of getting the first ability without having explicitly specified .ability.

Though I don't have strong feelings about it anymore since it is a config now.

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
