### PR TITLE
Cleaned up remaining Castform hack stuff

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Title.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Review by DizzyEggg — CHANGES_REQUESTED** [review]
1. Cherrim doesn't transform in sunny weather at all
2. Castform has a broken palette 
pokeemerald_01

**Comment by AsparagusEduardo** [comment]
> 2. Castform has a broken palette

It seems a different PR broke this, because I'm working on an unrelated PR and Castform's palette is also broken there, so it must be an upcoming thing.
imagen

**Comment by DizzyEggg** [comment]
> > 2. Castform has a broken palette
> 
> It seems a different PR broke this, because I'm working on an unrelated PR and Castform's palette is also broken there, so it must be an upcoming thing. imagen

Yeah, can confirm it's also broken on upcoming. I would say it's in scope of this PR to fix it :D

**Comment by AsparagusEduardo** [comment]
> Yeah, can confirm it's also broken on upcoming. I would say it's in scope of this PR to fix it :D

Alright

**Comment by AsparagusEduardo** [comment]
> 1. Cherrim doesn't transform in sunny weather at all

Can't reproduce.
mGBA_Q2Ve9pBBIv

**Comment by DizzyEggg** [comment]
> > 1. Cherrim doesn't transform in sunny weather at all
> 
> Can't reproduce. mGBA_Q2Ve9pBBIv

You're right, it works, my bad

**Comment by AsparagusEduardo** [comment]
Fixed Castform palettes. (Shiny weather palettes are the same regular ones)
imagen imagen imagen imagen imagen

**Comment by SonikkuA-DatH** [comment]
Castform starting with Gen 8's HOME has true shiny colors for the forms. I'll DM you the needed pals for that

**Comment by AsparagusEduardo** [comment]
> Castform starting with Gen 8's HOME has true shiny colors for the forms. I'll DM you the needed pals for that

Please make a separate PR for it. I'm done with this one tbh.

**Review by DizzyEggg — APPROVED** [review]

**Pull request merged**
