### PR TITLE
AI respects partner when using spread moves in double battles

### LINKED ISSUE #4517: Double battles Earthquake missing partner check
### Description

It appears the move Earthquake is missing the "IsBattlerAlive(battlerAtkPartner)" check in doubles. This has resulted in instances of the AI being disincentivised from clicking Earthquake once its doubles partner has fainted, leaving it as the only Pokemon on its side of the field, meaning it chooses unexpected moves where Earthquake would be expected. 

Please note: this is not my area of expertise, apologies, but happy to provide a link to a time-stamped Twitch VOD for demonstration purposes or to discuss on Discord. I have also put latest version, however I am unsure which version the game was built using, however a user in the RHH Discord looked and confirmed the check was missing/in the wrong place today 07th May 2024. A second user has provided the attached video and believes all moves with the "MOVE_TARGET_FOES_AND_ALLY" check will be affected.

https://github.com/rh-hideout/pokeemerald-expansion/assets/166724814/8179a4c7-ed41-4041-aee9-6448d958fef7

### Version

1.8.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

grintoul

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #4517

You could argue that AI should never use EQ while the partner is grounded and alive but I did it only on super effective (I am indifferent though so open to change it).

Also removed redundant Bulldoze effect.

/Edit: Add logic for all spread moves

### CODE REVIEW

**Comment by Bassoonian** [comment]
Shouldn't this not just affect Earthquake but rather [all moves that affect both opponents as well as your ally](https://bulbapedia.bulbagarden.net/wiki/Category:Moves_that_target_all_adjacent_Pok%C3%A9mon)? I think just checking the move's target data would be more helpful and accurate here rather than hardcoding specific move effects.

I would personally already deduce some points if there is an alive partner on the field that is not somehow immune to it and deduce even more points if it would be super effective, but perhaps this should be discussed in greater detail on Discord

**Comment by AlexOn1ine** [comment]
> Shouldn't this not just affect Earthquake but rather [all moves that affect both opponents as well as your ally](https://bulbapedia.bulbagarden.net/wiki/Category:Moves_that_target_all_adjacent_Pok%C3%A9mon)? I think just checking the move's target data would be more helpful and accurate here rather than hardcoding specific move effects.

Yeah, I agree,

**Comment by AlexOn1ine** [comment]
ready for re-review

**Comment by Bassoonian** [comment]
Conflicts

**Comment by AlexOn1ine** [comment]
> Conflicts

solved

**Comment by AlexOn1ine** [comment]
> > Conflicts
> 
> solved
> 
> Edit: I'm stupid

Should be good now

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
