### PR TITLE
Fixed ability to use dupe gimmick use in Double Battles

### LINKED ISSUE #5143: Double Dynamax
### Description

currently during double battles if a player hasn't dynamaxed while on player's turn the dynamax gimmick can be activated for both the players pokemon on that turn.
pokeemerald-0

### Version

1.9.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AgustinGDLV**
Fixes #5143 and #5125.

**Double Tera Fix:**

https://github.com/user-attachments/assets/75b15d51-d5b6-4093-8731-7239a0b4bac0

**Separate Gimmicks Still Work:** 

https://github.com/user-attachments/assets/0b104512-978f-417d-8fca-7105cb40c71a

### CODE REVIEW

**Comment by pkmnsnfrn** [comment]
You fixed the existing bug, but I'm hesitant to merge it because it introduces another problem (that should have been caught with the Gimmick refactor tbh, not pointing any fingers)

# Replication

`wget https://files.catbox.moe/kqd85y.inc -O data/scripts/debug.inc && https://files.catbox.moe/01pxf7.h -O include/config/battle.h`

# Steps

1. Run Debug Script 1. 
2. On Turn 1, Dynamax Throh and attempt to Tera Sawk
3. Notice that Sawk cannot Tera
4. On Turn 2, then Sawk can Tera because it fails the Dynamax check.

I imagine the bigger problem here is that we don't have a way to resolve the "tie" between Dynamax and Tera. Our current implementation is based on the principle that Mega Rayquaza could not Mega Evolve if it was holding a Z-Crystal, but there's no way to detect the "presence" of either Tera or Dynamax. 

[Nat Dex OU, the metagame closest](https://www.smogon.com/forums/threads/national-dex-anything-goes-metagame-discussion.3711024/) to the situation we have now, doesn't have Dynamax enabled as a mechanic, so we don't have a precedent to follow here.

# Possible Solutions:

## if a mon has a defined Tera type, it cannot Dynamax

but there's no way to distinguish a Pichu with Tera Electric type from intentional or unintentional usage.

## if a mon has a defined Dynamax Level, it cannot Tera

but that means a freshly caught mon will never be able Dynamax, the game will always prompt for Tera

## Gimmicks need to be a menu
We remove the Mega Ray style restrictions and let players choose from a list of all the Gimmicks the mon can currently do

## We force developers to either choose between Tera and Dynamax 
and make it clear that when both are enabled, Dynamax will always win (new bug still needs to be fixed)

## something else I haven't thought of

**Comment by AgustinGDLV** [comment]
Appreciate you testing and still happy to take the blame here — should double check AI behavior on this PR in general.

I think that the solution I would be most comfortable with would be disabling Tera if the Dynamax flag was on since that’s fairly intentional but I think that has issues. Happy to open up to senate discussion so we can come to a consensus fast and fix, don’t really mind any of the solutions listed

**Comment by pkmnsnfrn** [comment]
> Appreciate you testing 
Appreciate the fast fix :handshake: 

> should double check AI behavior on this PR in general.
I did not check the AI but I will in the next round of tests.

> Happy to open up to senate discussion so we can come to a consensus fast and fix, don’t really mind any of the solutions listed.

I don't think this needs to be a Senate-only discussion - if anything, having an open dialogue about this would be useful for brainstorming purposes.

> Alternatively, it would be possible to refresh possible gimmicks after one has been selected and still allow using both, but this would have the issue of one having priority over the other without UI changes.

If you do _just_ this, I would feel comfortable merging #5235. I think everything else I mentioned is a separate problem / PR, just wanted to flag it early.

**Comment by AlexOn1ine** [comment]
> I think that the solution I would be most comfortable with would be disabling Tera if the Dynamax flag was on since that’s fairly intentional but I think that has issues. Happy to open up to senate discussion so we can come to a consensus fast and fix, don’t really mind any of the solutions listed.

What if one of the AI mons has the ability do tera, the other dynamax and no flags are set for the player? 
I see the problem generally but I think solving it through the flags seems sub optimal. 

The function `HasTrainerUsedGimmick` returns a gimmick. Can you not check what gimmick was chosen and decide based on it what to allow and what not?

**Comment by AlexOn1ine** [comment]
> You fixed the existing bug, but I'm hesitant to merge it because it introduces another problem (that should have been caught with the Gimmick refactor tbh, not pointing any fingers)

I don't think this is a valid reason not to merge. This PR fixes a bug that users are probably waiting for. The second bug can be fixed in a follow up and opening an issue ticket for now

**Comment by pkmnsnfrn** [comment]
> > You fixed the existing bug, but I'm hesitant to merge it because it introduces another problem (that should have been caught with the Gimmick refactor tbh, not pointing any fingers)
> 
> I don't think this is a valid reason not to merge. This PR fixes a bug that users are probably waiting for. The second bug can be fixed in a follow up and opening an issue ticket for now

I don't agree that knowingly adding a bug is an acceptable merge, but I won't fight you on it. If you do merge, please make sure the new bug has an issue.

**Comment by AlexOn1ine** [comment]
> > > You fixed the existing bug, but I'm hesitant to merge it because it introduces another problem (that should have been caught with the Gimmick refactor tbh, not pointing any fingers)
> > 
> > 
> > I don't think this is a valid reason not to merge. This PR fixes a bug that users are probably waiting for. The second bug can be fixed in a follow up and opening an issue ticket for now
> 
> I don't agree that knowingly adding a bug is an acceptable merge, but I won't fight you on it. If you do merge, please make sure the new bug has an issue.

Correct me if I'm wrong but the bug was previously present so it would be fair game to merge if at least one bug is fixed. Also this seems like a niche scenario for ppl who have both Dynamax and Tera Blast on.

**Review by AlexOn1ine — COMMENTED** [review]
I'm merging this since this fixes important bugs. The other issue was present before and applies to users who have both dmax and tera in their hacks. It should be fixed but I think this is more important.

**Review by AlexOn1ine — APPROVED** [review]

**Comment by DeusGrim** [comment]
I'm glad the original bug was fixed and i can see why the new bug would cause problems. Wouldn't it be easiest to let the items become the flag setters for what pokemon in party can use what gimmick from both tera and dynamax? enabling the tera type of a pokemon or the dynamax level, setting a specific tera and dynamax flag which can be enabled through the flags menu into an unused flag space by whoever is making a new game?

**Comment by AlexOn1ine** [comment]
> I'm glad the original bug was fixed and i can see why the new bug would cause problems. Wouldn't it be easiest to let the items become the flag setters for what pokemon in party can use what gimmick from both tera and dynamax? enabling the tera type of a pokemon or the dynamax level, setting a specific tera and dynamax flag which can be enabled through the flags menu into an unused flag space by whoever is making a new game?

what if you have both items?

**Comment by DeusGrim** [comment]
> testing.
> https://discord.com/channels/419213663107416084/1233459650578350081/1276267180396384287
> 
> we came up with a solution in Discord, but 

I just saw that, i realized it was a similar solution too! It even included the idea of just having a menu option also come up, which i thought about but didn't consider. I thought using the items as the menu for each separately would work easier having each deal with the set gimmick separately while also doing an active check for the opposite one.

**Pull request merged**
