### PR TITLE
Update Giga Impact's graphic and use fade-in battle animation.

### PR DESCRIPTION
**Pull request by Blackforest92**
This is an alternate to [#1818](https://github.com/rh-hideout/pokeemerald-expansion/pull/1818)
If this alternate is decided to be unpleasing, feel free to discard this PR.

Animation preview [here](https://discord.com/channels/419213663107416084/774393519569502268/904963411220242452).

This PR also :
(1) rename SPACIAL_REND tilemap `.bin` files to GIGA_IMPACT, as giga impact feels more like a common move than spacial rend.
(2) Giga Impact and Spacial Rend now use the same tilemap `.bin` files to save spaces.

### CODE REVIEW

**Comment by Blackforest92** [comment]
Adjusted timing of background fade-in. Preview [here](https://discord.com/channels/419213663107416084/774393519569502268/905144670194110546)
Now it fade as `gVerticalDipSpriteTemplate` is executing.

**Comment by BuffelSaft** [comment]
Need to resolve conflicts.

**Comment by Blackforest92** [comment]
Updated branch to latest RHH's `battle_engine`

**Review by BuffelSaft — CHANGES_REQUESTED** [review]
Looks good to me:
giga impact
I think it would be better to remove `BG_SPACIAL_REND_ON_OPPONENT` completely and use the Giga Impact labels in the Spacial Rend animation though - sorry to make a simple PR such a pain!

**Review by BuffelSaft — APPROVED** [review]

**Review by ghoulslash — APPROVED** [review]

**Pull request merged**
