### PR TITLE
Gen 1 > Gen 5 Palette Conversion

### PR DESCRIPTION
**Pull request by Blackforest92**
This PR converts Sugimori palettes to official one, fix to a lot of normal-shiny, sprite errors, and overall sprites tidying.
This PR ignores shiny colors and some colors are picked based on my preference. Ex : Blastoise or Nidoqueen
What? You don't like it? Want everything to be strictly official? Want me to do shinies too?
I am sorry but we live in a society.
This part is non-negotiable and I am not giving you an option.
Handgun

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
We'll need #1965 to test this behemoth ^^;

**Comment by Blackforest92** [comment]
Converted GEN5 palettes, This PR also :
- Add new Female icons for Hippopotas and Hippowdon.
- Organized male and female files.

**Comment by MandL27** [comment]
Was scrolling through this on a branch that also has #1965 applied and I noticed a few mon still have their Sugi palette. Golem was the first really obvious one to me, though there are probably others and I'm too lazy atm to comb through the file list to figure out which ones.

**Comment by Blackforest92** [comment]
Yes, some are picked based of my preferences.
Golem family tree, or Rapidash alike do not hurt my eyes and i find them more pleasing to use current palette. Things that hurt my eyes is like Pikachu or Wailord.

**Comment by LOuroboros** [comment]
> Yes, some are picked based of my preferences. Golem family tree, or Rapidash alike do not hurt my eyes and i find them more pleasing to use current palette. Things that hurt my eyes is like Pikachu or Wailord.

The conversion should applied to all sprites for consistency's sake imo.

**Comment by Blackforest92** [comment]
That's not something i will do.
I have finished 600+ pokemons, tidy stuffs (iirc Blastoise front shell, 2nd frame of Gardevoir, Pidgeot, Walrein?, many more)
And i believe i have done enough. I meant it when i typed non-negotiable.
Reviewers are free to reject this PR if votes are overwhelming negative, no drama.

If this PR is rejected and you want to make them all strictly official, i still suggest you to clone my pokeemerald `pokemon_expansion` so you don't need to start over. Only several of them are picked by preferences though i don't remember which one accurately anymore among those 600+ pokemons so i can't assist on this.

**Comment by MandL27** [comment]
Consensus between myself, Lunos, and Jaizu is that this should be all or nothing, not cherrypicked. Closing.

**Pull request closed without merging**
