### PR TITLE
Prevents double targeting on player mon if both ai mons see kill

### LINKED ISSUE #5212: AI should double target in Double Battles
### Description

> If the Ai sees both Pokemon can get an OHKO it should [choose do one of the following]

* randomly pick which mon goes for the kill while the other mon will act normally
* double target the mon that can be OHKO'd

The double target functionality should be optional, triggered by a flag.

### Discord contact info

Awakeon

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Closes #5212. It isn't exactly what was asked in the suggestion but this is a superset of it. I believe the suggestion in the issue ticket isn't good and should not make it into expansion

In vanilla when both AI mons see a kill on a player mon they will pin down the mon with both mons. This pr changes it so the other mon will be targeted by one of the AI mons.

Since this is a superset of the vanilla implementation I made it as default with a vanilla ai flag to turn it off. This could potentially be a config. Additionally or replacing the ai flag.

Examples:
```
Slot 1 Slot 3
Slot 0 Slot 2
```
If slot 1 and 3 see kill on slot 2, Slot 1 will first target slot 2 then if Slot 3 targets slot 2 as well, slot 1 will recalc and skip slot 3 as the target 

If both ai mons (slot 1 and 3) see kill on both player mons (slot 0 and 2), slot 1 will randomly decide between slot 0 and 2. Then Slot 3 decides randomly. If they both target the same slot, slot 1 will recalc  

Scenario 1:

https://github.com/user-attachments/assets/2e8aecd8-4bc8-47f5-a251-41817e74344e

Scenario 2:

https://github.com/user-attachments/assets/9846edc1-d781-4e5e-ba96-7c7e7bc70b4a

Scenario 3:

https://github.com/user-attachments/assets/9987a541-96fb-4a13-a947-11f4caceac2b

### CODE REVIEW

**Comment by Pawkkie** [comment]
Would you be willing to add an extremely brief section for the flag to `docs/ai_flags.md` so it stays up to date? :)

**Review by Pawkkie — CHANGES_REQUESTED** [review]
Looks good to me as is, though I would request that `AI_FLAG_VANILLA_DOUBLE_TARGET` get added to the ai_flags.md document if you don't mind :)

**Comment by AlexOn1ine** [comment]
> Looks good to me as is, though I would request that `AI_FLAG_VANILLA_DOUBLE_TARGET` get added to the ai_flags.md document if you don't mind :)

Will add. 

Also I want to write some tests.

**Comment by AlexOn1ine** [comment]
Ready for re-review

**Comment by AlexOn1ine** [comment]
There is a bug (the ai recalc the target but not the move choice) in this so putting in on draft

**Comment by Pawkkie** [comment]
> There is a bug (the ai recalcs the target but not the move choice) in this so putting in on draft

I'm not back form my honeymoon so can re-review when you're ready :)

**Pull request closed without merging**
