### PR TITLE
Corrected Final Gambit's move data and tweaked its effect

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
After #1287, I decided to look into Final Gambit since it had the same effect as Dragon Tail assigned to it for some reason.
I found out that the move's true effect was already done. It was simply not assigned to the move in its data, for whatever reason.
On top of that, it was also missing the `FLAG_KINGSROCK_AFFECTED`, so I threw it in.
Untitled1987

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Review by ghoulslash — APPROVED** [review]

**Review by ultima-soul — DISMISSED** [review]
Seems like we should maybe look at the proper order later for how Final Gambit works compared to how it looks in the Gen 5 gif on Bulbapedia: https://cdn.bulbagarden.net/upload/2/2f/Final_Gambit_V.png

**Comment by LOuroboros** [comment]
> 
> 
> Seems like we should maybe look at the proper order later for how Final Gambit works compared to how it looks in the Gen 5 gif on Bulbapedia: https://cdn.bulbagarden.net/upload/2/2f/Final_Gambit_V.png

It seems that the attacker must faint before the attack proceeds to hurt the foe, is that correct?
It should be simple if so. Sounds like a quick change in the order on which the functions are called in Final Gambit's effect's battle script would be just about all it would take. I'll take a look at it :eyes:

**Comment by ultima-soul** [comment]
> > Seems like we should maybe look at the proper order later for how Final Gambit works compared to how it looks in the Gen 5 gif on Bulbapedia: https://cdn.bulbagarden.net/upload/2/2f/Final_Gambit_V.png
> 
> It seems that the attacker must faint before the attack proceeds to hurt the foe, is that correct?
> It should be simple if so. Sounds like a quick change in the order on which the functions are called in Final Gambit's effect's battle script would be just about all it would take. I'll take a look at it 👀

Maybe make sure to double-check in USUM how losing and stuff works when using Final Gambit and doing testing the same in the Battle Engine.

**Comment by LOuroboros** [comment]
> 
> 
> > It seems that the attacker must faint before the attack proceeds to hurt the foe, is that correct?
> > It should be simple if so. Sounds like a quick change in the order on which the functions are called in Final Gambit's effect's battle script would be just about all it would take. I'll take a look at it 👀
> 
> Maybe make sure to double-check in USUM how losing and stuff works when using Final Gambit and doing testing the same in the Battle Engine.

T'was the first thing I did, and it looks like in USUM, Final Gambit does affect the target before affecting the attacker, meaning that its effect in the BE is currently working as intended, I think?

Here's a quick vid: https://streamable.com/sdpzv1

**Comment by LOuroboros** [comment]
Multiple tests on top of the one above showed certain inaccuracies in Final Gambit's effect, so I fixed them *as far as I can tell* and pushed them to the branch submitted in this PR.

Ready for reviews :eyes:

**Review by ultima-soul — CHANGES_REQUESTED** [review]
Some issues:
- When blocked via type immunity, it should print "it doesn't affect foe" message.
- When triggering defender's Focus Band or defender uses Endure or defender has Sturdy, no "Hung on with X" message printed and attacker takes damage equivalent to how much HP was lost by defender to get to 1 HP when it should lose all of its HP.

**Comment by LOuroboros** [comment]
Ready for re-review :eyes:

**Review by ultima-soul — APPROVED** [review]

**Review by ExpoSeed — APPROVED** [review]

**Pull request merged**
