### PR TITLE
Unify end/end2/end3

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Port of @mrgriffin's PR #2701 so full credit to them.

Generally the PR should make it more convenient to write new battle scripts.

To port non expansion scripts a user needs to replace all `end2/end3` commands with a simple `end` and do the following change in `battle_script_commands.c / battle_util.c`:
```diff
-BattleScriptPushCursor();
-gBattlescriptCurrInstr = BattleScript_X;
+BattleScriptCall(BattleScript_X);
```

### CODE REVIEW

**Comment by pkmnsnfrn** [comment]
Does this need a real ass code review? Or do we just need to play through the game and see if anything breaks?

Are there specific actions that are liable to break?

**Comment by AlexOn1ine** [comment]
> Does this need a real ass code review? Or do we just need to play through the game and see if anything breaks?
> 
> Are there specific actions that are liable to break?

I don't think this breaks anything but a playthrough wouldn't hurt.

**Review by AsparagusEduardo — DISMISSED** [review]

**Comment by AsparagusEduardo** [comment]
Looks good to me :)
Just needs to solve conflicts

**Comment by ShinyDragonHunter** [comment]
To make it easier on those porting, would it be worth at least keeping some form of "end2" etc but just have the macros be the new way that would be functionally equivalent?

**Comment by AsparagusEduardo** [comment]
> To make it easier on those porting, would it be worth at least keeping some form of "end2" etc but just have the macros be the new way that would be functionally equivalent?

You can read in the code of the PR that they all point to `end` now and they still work, so any people still using `end2` will have their scripts still work out of the box. They'll just have to rename their uses of it in the scripts for when they are eventually removed.

**Pull request closed without merging**
