### PR TITLE
Implemented Battle Bond

### LINKED ISSUE #438: ABILITY_BATTLE_BOND

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Title.
Closes #438.

https://user-images.githubusercontent.com/4485172/135700089-63ef0280-1153-4e2b-84c2-5422a3890508.mp4

## **Discord contact info**

Lunos#4026

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
I feel that `STRINGID_ATTACKERBECAMEASHSPECIES` should use the species name in the "Ash" part instead of the nickname
image
Battle bond isn't triggering when using multihit moves. Would need to test again when #1676 is merged.
battlebond

**Comment by LOuroboros** [comment]
>  Battle bond isn't triggering when using multihit moves. Would need to test again when #1676 is merged.

I just did. Effectively, that PR will solve the issue once it's merged.

https://github.com/LOuroboros/pokeemerald/tree/battle_bond_dev

**Comment by AsparagusEduardo** [comment]
> > Battle bond isn't triggering when using multihit moves. Would need to test again when #1676 is merged.
> 
> I just did. Effectively, that PR will solve the issue once it's merged.
> 
> https://github.com/LOuroboros/pokeemerald/tree/battle_bond_dev
> 
> 
Wouldn't it be more correct to show the new form's species name instead of the previous form?
In this example: "MMMMMMMMM became Ash-Blaziken"

**Comment by LOuroboros** [comment]
> 
> 
> > > Battle bond isn't triggering when using multihit moves. Would need to test again when #1676 is merged.
> > 
> > 
> > I just did. Effectively, that PR will solve the issue once it's merged.
> > [https://github.com/LOuroboros/pokeemerald/tree/battle_bond_dev](https://github.com/LOuroboros/pokeemerald/tree/battle_bond_dev?rgh-link-date=2021-10-02T16%3A45%3A47Z)
> > 
> 
> Wouldn't it be more correct to show the new form's species name instead of the previous form's? In this example: "MMMMMMMMM became Ash-Blaziken"

No, I don't think so because it's supposed to be a Torchic that transforms into an upgraded version of the same species. Such is the case of Greninja, and it's the only single reference point we have for it.

**Comment by AsparagusEduardo** [comment]
> No, I don't think so because it's supposed to be a Torchic that transforms into an upgraded version of the same species. Such is the case of Greninja, and it's the only single reference point we have for it.

Alright, fair.

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
