### PR TITLE
Fix evaporate/sizzle strings failing to print after the first move failure.

### PR DESCRIPTION
**Pull request by ShaeTsuPog**
## Description
This fixes an issue where the flag for `HITMARKER_STRING_PRINTED` persisted after the first failure of a move under primal sun/rain, causing the string to not print on subsequent failures.

## Images
Before:
primalbug

After:
primalfix

## Issue(s) that this PR fixes
N/A

## **Discord contact info**
Shae#9032

### CODE REVIEW

**Comment by ShaeTsuPog** [comment]
This now clears the bit for `HITMARKER_STRING_PRINTED` after moves are finished executing, allowing for the string to print for every failure of a move under primal weather, which is closer to vanilla. Single battle behavior matches the before GIF previously provided. Here is a comparison for before and after for double battles.

Before:
primaldoublebefore

After:
primaldoubleafter

Note that in both GIFs there is a noticeable pause with a blank message box after the string is printed for multi target moves like Surf, but this brings it closer to vanilla behavior where the string is printed for every nullification, as shown in this video Lunos posted in the Discord: https://discord.com/channels/419213663107416084/774393519569502268/1097715331465744424

As an additional reference, here is how it looks with multi hit moves like Water Shuriken with this change, the string is printed once and only once per move:
primalmultihit

**Comment by AsparagusEduardo** [comment]
Hmm, one of Intimidate's tests failed with that change. Please look into that. You can test locally by doing `make -jN check`

**Comment by ShaeTsuPog** [comment]
I've looked at this some more and I'm pretty sure that `HandleAction_ActionFinished` would be the proper place to clear it, but the issue with the Intimidate test seems to be that its causing an unmatched message error on line 82 for this test in particular: https://github.com/rh-hideout/pokeemerald-expansion/blob/ae80d545c5b4f2f86baf702d4527d88c11b935b0/test/ability_intimidate.c#L60

Somehow clearing the hitmarker in `HandleAction_ActionFinished` seems to cause the order that mons are sent out to change in this test and only this test, sending out both player mons before the opponents, rather than alternating like is written in the test.

Is it possible this test in particular is flawed, or is clearing the hitmarker here actually somehow changing the order pokemon are sent out? If it's the latter, then I'm at a complete loss as I have no idea how this could be affecting send out order.

For what its worth, I threw together a quick test in-game and it seems to work correctly?

intimtest

**Comment by AlexOn1ine** [comment]
Fwiw the test `Intimidate doesn't activate on an empty field in a double battle: FAIL` also fails for me without ever using this PR.

**Comment by AsparagusEduardo** [comment]
Replaced by #3138

**Pull request closed without merging**
