### PR TITLE
Destiny Bond and OHKO moves are blocked by Dynamax

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Source: [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Dynamax)

### CODE REVIEW

**Comment by hedara90** [comment]
Partially fixes #5777

**Comment by hedara90** [comment]
Could you write tests for these cases?
(Or wait 2 days until I get back to my ssh keys)

**Comment by AlexOn1ine** [comment]
> Could you write tests for these cases? (Or wait 2 days until I get back to my ssh keys)

sec

**Comment by AlexOn1ine** [comment]
Closing this because there is a weird bug. The engine does not recognize Destiny Bond as the current move so if you even hardcode the movecheck the test still does not pass
```
    if (gCurrentMove == MOVE_DESTINY_BOND)
    {
        BattleScriptPushCursor();
        gBattlescriptCurrInstr = BattleScript_MoveBlockedByDynamax;
        return;
    }
```

**Comment by Bassoonian** [comment]
What about the OHKO moves?

**Comment by AlexOn1ine** [comment]
> What about the OHKO moves?

There is already a test for them and they fail accordingly

**Comment by AlexOn1ine** [comment]
> Closing this because there is a weird bug. The engine does not recognize Destiny Bond as the current move so if you even hardcode the movecheck the test still does not pass
> 
> ```
>     if (gCurrentMove == MOVE_DESTINY_BOND)
>     {
>         BattleScriptPushCursor();
>         gBattlescriptCurrInstr = BattleScript_MoveBlockedByDynamax;
>         return;
>     }
> ```

I might be wrong here but I still don't understand where the bug is coming from

**Pull request closed without merging**
