### PR TITLE
Dynamic regional dex rating

### LINKED ISSUE #3874: Prof. Birch cannot identify Pokedex correctly
### Description

If you set the entire pokedex completed in the debug menu and talk to Birch to evaluate the pokedex, or encounter him in any other situation where he checks your progress, he will not identify that you have completed the pokedex in any way.
Maybe related to the regional dex originally being a higher number?

profbirchdialogpokedex

### Version

1.7.1 (Default)

### Upcoming Version

515aa367bfeb542e1cfa888ebf4b86351e9946e9

### Discord contact info

kakarikiki

### PR DESCRIPTION
**Pull request by Bassoonian**
This PR completely overhauls the regional dex rating. Features:
- There no longer is a hardcoded limit of 200 in the rating. Instead, it dynamically adapts to the amount of species in the regional dex and the amount of quotes Birch has, evenly distributing them across the size of the regional dex.
- The two different functions in Match Call and actually talking to Birch have been condensed into a single function.
- Rather than hardcoding Jirachi and Deoxys (and how they affect what counts as a complete dex), there is now a static array that consists of species that are ignored for regional dex rating purposes. They are taken into account for the formulas mentioned above.
- This also saves a whopping 496 bytes!

This is currently based on master since it's a bugfix (imo), but can be rebased to upcoming if considered too invasive for master.

## Issue(s) that this PR fixes
Fixes #3874 

## **Discord contact info**
bassoonian

### CODE REVIEW

**Comment by pkmnsnfrn** [comment]
should not be blocking: I understand that the static array for Jirachi and Deoxys work just fine, but that sounds like it should be a member of the Pokemon struct, like `doesNotCountForRegionalPokedex`. This concepts exists in every main series game from Gen 3 onwards and editing that property would likely be on every developer's list for their game's regional dex.

**Comment by Bassoonian** [comment]
> should not be blocking: I understand that the static array for Jirachi and Deoxys work just fine, but that sounds like it should be a member of the Pokemon struct, like `doesNotCountForRegionalPokedex`. This concepts exists in every main series game from Gen 3 onwards and editing that property would likely be on every developer's list for their game's regional dex.

I believe making it a member of the struct will make the process slightly longer since we need to check that value for each mon in the dex as opposed to just going through the list, but it's a very fair remark. Since this is going to master, I think we could potentially consider it blocking, so feedback from others would be highly appreciated here

**Comment by pkmnsnfrn** [comment]
imho, merge this one as is, make an issue for later to address `doesNotCountForRegionalPokedex`. You fixed the bug, this is a bug fix, we can optimize later

**Comment by AlexOn1ine** [comment]
Can anybody provide a save that this can be tested with?

**Review by AlexOn1ine — APPROVED** [review]
I think it's fine if this goes to master since it fixes an obvious bug. 

@pkmnsnfrn Could you please open an issue ticket?

**Pull request merged**
