### PR TITLE
Fix Light Of Ruin freeze and potentially other move anims

### LINKED ISSUE #2991: MOVE_DEVASTATING_DRAKE Freezes The Game In Double Battles
Screenshot 2023-05-11 173803

### LINKED ISSUE #3053: LightOfRuin freezes the game in double battles
### Description

LightOfRuin Freezes the game in double battles. Works fine in single battles. 

_**does not happen if the battle animations are turned off**_

**screenshot**

pokeemerald-13

### Version

upcoming (Edge)

### Upcoming Version

8efbe825dbd7a306af3ee8c8b4cdd4608375573a

### Discord contact info

Aaghat#2527

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3053
Fixes #2991

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
It also fixed Flatter (Issue #2925). :tada:

**Comment by ghoulslash** [comment]
> It also fixed Flatter (Issue #2925). :tada: 

But why is a gen3 move anim now requiring this check in the first place? What is creating so many extra sprites? If I had to guess it might be related to the new mega indicator system since iirc it creates each indicator per battler and never destroys them

**Comment by AsparagusEduardo** [comment]
> > It also fixed Flatter (Issue #2925). 🎉
> 
> But why is a gen3 move anim now requiring this check in the first place? What is creating so many extra sprites? If I had to guess it might be related to the new mega indicator system since iirc it creates each indicator per battler and never destroys them

Are we sure those animations didn't crash in double battles before that refactor?

**Comment by DizzyEggg** [comment]
> > It also fixed Flatter (Issue #2925). 🎉
> 
> But why is a gen3 move anim now requiring this check in the first place? What is creating so many extra sprites? If I had to guess it might be related to the new mega indicator system since iirc it creates each indicator per battler and never destroys them

Yes, you're 100% right. I'll look into changing that.

**Review by ghoulslash — APPROVED** [review]

**Pull request merged**
