### PR TITLE
Fix Baton Pass not passing Embargo properly

### LINKED ISSUE #3554: Embargo passed onto a party member via Baton Pass is lifted after 1 out of 5 turns pass, when it shouldn't
### Description

If a Pokémon that is under the effects of Embargo uses Baton Pass to switch out the Pokémon, the one that is sent out is supposed to inherit that status and be affected by Embargo for the remainder of its active effect.

In the expansion, Embargo is lifted immediately after sending out a new Pokémon, when it should last 4 turns after the fact.

Expansion:

Embargo_BatonPass_Fling_Expansion

USUM:

https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/08bd15f3-efa6-43b8-8295-e2787301c63a

### Version

upcoming (Edge)

### Upcoming Version

3004fd588aa4afe17a3bfd297978c0b932b45fef

### Discord contact info

lunos4026

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3554

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Egg, I think you need to change the target to master. Fiery Wrath fix isn't in upcoming yet.

**Comment by DizzyEggg** [comment]
> Egg, I think you need to change the target to master. Fiery Wrath fix isn't in upcoming yet.

The tests which this PR fixes aren't in master either XD 

Once master is merged into upcoming, there should be no problem.

**Comment by AlexOn1ine** [comment]
> The tests which this PR fixes aren't in master either XD

I see, this is a little problematic 😅  
> Once master is merged into upcoming, there should be no problem.

Yeah

**Comment by AsparagusEduardo** [comment]
> Once master is merged into upcoming, there should be no problem.

Once sec xD

**Comment by AsparagusEduardo** [comment]
> Once sec xD

Done

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
