### PR TITLE
Adds missing Hisuian sprites and cries

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes: 

#2254
#2253
#2252
#2251
#2250
#2249
#2248
#2463

Sprites and Cries for:

Basculegion-M
Wyrdeer
Enamorus
Sneasler
Samurott
Decidueye
Basculegion-F
Enamorus-T

### CODE REVIEW

**Comment by Jaizu** [comment]
Shouldn't we force adding second frames to sprites to avoid having a lot of single frame sprites like we have already?

**Comment by AsparagusEduardo** [comment]
> Shouldn't we force adding second frames to sprites to avoid having a lot of single frame sprites like we have already?

It would be preferable, but if the resource isn't available I don't see the issue of having single frames for now. I rather have that than leaving them with the missingno sprite.

**Comment by Jaizu** [comment]
Then at least we should have anim_front with 2 frames that are the same so we can easily submit them in the future once available.

**Comment by AsparagusEduardo** [comment]
> Then at least we should have anim_front with 2 frames that are the same so we can easily submit them in the future once available.

If we do that, it'll be harder to find which mon are missing their second frame code-wise, as it would be as simple as looking for `/front.4bpp`
image

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
There are palette issues with the following mon:

Regular palette:
image
Shiny palette:
image

**Comment by AlexOn1ine** [comment]
Changing it to draft for now because I found some better sprites + conflicts.

**Comment by AlexOn1ine** [comment]
Fixed previous issues and changed some sprites. Ready for review.

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
Looks good!
Just needs to revert `graphics/pokemon/samurott/shiny.pal`, as it's doing something weird currently:
image

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
