### PR TITLE
Fix Sliggoo not evolving in fog

### PR DESCRIPTION
**Pull request by kittenchilly**
## Description
Sliggoo was only set to evolve during rain, while it can evolve during fog as well. This fixes that.

## **Discord contact info**
kittenchilly

### CODE REVIEW

**Comment by DizzyEggg** [comment]
Perhaps it would be better to have two options EVO_LEVEL_RAIN and EVO_LEVEL_RAIN_FOG available? And a config for Sliggoo, so if it's <= gen6 it's only rain, and then it's rain and fog. What do others think?

**Comment by AsparagusEduardo** [comment]
> Perhaps it would be better to have two options EVO_LEVEL_RAIN and EVO_LEVEL_RAIN_FOG available? And a config for Sliggoo, so if it's <= gen6 it's only rain, and then it's rain and fog. What do others think?

Or even better, have a separate `EVO_LEVEL_FOG` and have the config allow it when it's `>= GEN_7` :)

**Comment by LOuroboros** [comment]
> Perhaps it would be better to have two options EVO_LEVEL_RAIN and EVO_LEVEL_RAIN_FOG available? And a config for Sliggoo, so if it's <= gen6 it's only rain, and then it's rain and fog. What do others think?

The thought crossed my mind yesterday when I saw the PR, but I assumed there wouldn't be much interest in splitting the evos like that. Like, it's hard to think a user would specifically want an `EVO_LEVEL_RAIN` that is specifically not affected by fog.

Eduardo's idea sounds nice. Either way is fine imo though.

**Comment by kittenchilly** [comment]
Oh, can Sliggoo not evolve in fog in gen 6? Is there even a case in gen 6 with fog that sliggoo can level up in?

**Comment by AsparagusEduardo** [comment]
> Oh, can Sliggoo not evolve in fog in gen 6? Is there even a case in gen 6 with fog that sliggoo can level up in?

image

**Comment by kittenchilly** [comment]
> > Oh, can Sliggoo not evolve in fog in gen 6? Is there even a case in gen 6 with fog that sliggoo can level up in?
> 
> image

Ah I see. If I add another config should I rebase to upcoming then?

**Comment by AsparagusEduardo** [comment]
> Ah I see. If I add another config should I rebase to upcoming then?

Yep

**Comment by kittenchilly** [comment]
Alright, I'll close to rebase.

**Pull request closed without merging**
