### PR TITLE
Debug Menu improvements

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
HunarPG#2786 and I spotted some weird things in the debug menu, so I decided to go ahead and correct most of them.
- Updated the text string used by Debug_FlagsNotSetMessage.
- Renamed Debug_FlagsNotSetMessage to Debug_FlagsNotSetOverworldConfigMessage.
- Added an equivalent for the battle config file called Debug_FlagsNotSetBattleConfigMessage,
- DEBUG_FLAG_NO_COLLISION -> OW_FLAG_NO_COLLISION
  - And moved it to include/config/overworld.h, because at the end of the day it's still an overworld flag just like the other 2 already in that file.
- Corrected miswritten preproc config in DebugAction_Flags_CatchingOnOff.
- Updated the comment that describes the effect of DEBUG_OVERWORLD_MENU reducing the number of characters a tiny bit and fixing a typo.
- Added a new option to clear the PC boxes inside the debug menu's Utilities section.
- Made DebugAction_Give_FillPC give different individual species starting with Bulbasaur instead of 420 Deoxys.
  - Made it set the Seen and Caught Pokédex flags for each of those species.
  - Made it enable the FLAG_SYS_POKEMON_GET for user's convenience.

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by LOuroboros** [comment]
Ready for review I think. I made a couple of improvements.
-Added a new option to clear the PC boxes inside the debug menu's Utilities section.
-Made DebugAction_Give_FillPC give different individual species starting with Bulbasaur instead of 420 Deoxys.
 -Made it set the Seen and Caught Pokédex flags for each of those species.
 -Made it enable the FLAG_SYS_POKEMON_GET for user's convenience.

**Comment by AsparagusEduardo** [comment]
For this and future PRs, I'd prefer for the Title/Description to be updated to what it fully does, to make it easier for me when I compile for the changelog :)

**Comment by LOuroboros** [comment]
> For this and future PRs, I'd prefer for the Title/Description to be updated to what it fully does, to make it easier for me when I compile for the changelog :)

I can't explain every single thing on the title though. GitHub does suggest to use 50 words or less too.

**Comment by AsparagusEduardo** [comment]
> I can't explain every single thing on the title though. GitHub does suggest to use 50 words or less too.

Yeah, but instead of "Updated Debug Menu" you could write "Debug Menu Improvements"

**Pull request merged**
