### PR TITLE
Added missing Alcremie forms

### LINKED ISSUE #1175: SPECIES_ALCREMIE

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Added missing Alcremie forms. Sprite and pallette optimization by @blackforest92.

I haven't been able to find icons for the forms.

## Images
mGBA_xmAuuWN8t0 mGBA_Gh3wRZS0Zt

## Issue(s) that this PR fixes
Closes #1175.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Any reason the old Alcremie define block can't be simplified?
#define SPECIES_ALCREMIE_STRAWBERRY_RUBY_CREAM      FORMS_START + 311
#define SPECIES_ALCREMIE_STRAWBERRY_MATCHA_CREAM    FORMS_START + 312
#define SPECIES_ALCREMIE_STRAWBERRY_MINT_CREAM      FORMS_START + 313
#define SPECIES_ALCREMIE_STRAWBERRY_LEMON_CREAM     FORMS_START + 314
#define SPECIES_ALCREMIE_STRAWBERRY_SALTED_CREAM    FORMS_START + 315
#define SPECIES_ALCREMIE_STRAWBERRY_RUBY_SWIRL      FORMS_START + 316
#define SPECIES_ALCREMIE_STRAWBERRY_CARAMEL_SWIRL   FORMS_START + 317
#define SPECIES_ALCREMIE_STRAWBERRY_RAINBOW_SWIRL   FORMS_START + 318
```

**Comment by AsparagusEduardo** [comment]
> Any reason the old Alcremie define block can't be simplified?

I still want to add the synonyms for the cream/swirls. Will this suffice?
```diff
// Alcremie
+#define SPECIES_ALCREMIE_RUBY_CREAM                 SPECIES_ALCREMIE_STRAWBERRY_RUBY_CREAM
+#define SPECIES_ALCREMIE_MATCHA_CREAM               SPECIES_ALCREMIE_STRAWBERRY_MATCHA_CREAM
+#define SPECIES_ALCREMIE_MINT_CREAM                 SPECIES_ALCREMIE_STRAWBERRY_MINT_CREAM
+#define SPECIES_ALCREMIE_LEMON_CREAM                SPECIES_ALCREMIE_STRAWBERRY_LEMON_CREAM
+#define SPECIES_ALCREMIE_SALTED_CREAM               SPECIES_ALCREMIE_STRAWBERRY_SALTED_CREAM
+#define SPECIES_ALCREMIE_RUBY_SWIRL                 SPECIES_ALCREMIE_STRAWBERRY_RUBY_SWIRL
+#define SPECIES_ALCREMIE_CARAMEL_SWIRL              SPECIES_ALCREMIE_STRAWBERRY_CARAMEL_SWIRL
+#define SPECIES_ALCREMIE_RAINBOW_SWIRL              SPECIES_ALCREMIE_STRAWBERRY_RAINBOW_SWIRL
#define SPECIES_ALCREMIE_STRAWBERRY_RUBY_CREAM      FORMS_START + 311
#define SPECIES_ALCREMIE_STRAWBERRY_MATCHA_CREAM    FORMS_START + 312
#define SPECIES_ALCREMIE_STRAWBERRY_MINT_CREAM      FORMS_START + 313
#define SPECIES_ALCREMIE_STRAWBERRY_LEMON_CREAM     FORMS_START + 314
#define SPECIES_ALCREMIE_STRAWBERRY_SALTED_CREAM    FORMS_START + 315
#define SPECIES_ALCREMIE_STRAWBERRY_RUBY_SWIRL      FORMS_START + 316
#define SPECIES_ALCREMIE_STRAWBERRY_CARAMEL_SWIRL   FORMS_START + 317
#define SPECIES_ALCREMIE_STRAWBERRY_RAINBOW_SWIRL   FORMS_START + 318
```
 
> Only further changes that are needed are in `pokemon_animations.c`

Right, will do.

**Comment by AlexOn1ine** [comment]
> I still want to add the synonyms for the cream/swirls. Will this suffice?
Yeah, If you have further plans that should be fine.

**Comment by AsparagusEduardo** [comment]
> Yeah, If you have further plans that should be fine.

It's to allow users to be less specific about the Pokémon they use on their scripts and such, like how we have `SPECIES_GIRATINA` and `SPECIES_GIRATINA_ALTERED`.

In any case, it's ready to merge :)

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
