### PR TITLE
ShouldPivot type cleanup

### PR DESCRIPTION
**Pull request by Pawkkie**
## Description
As discussed on Discord starting [here](https://discord.com/channels/419213663107416084/1077168246555430962/1289922042619101197), ShouldPivot being a bool32 that returns one of three values from an enum is unintuitive (or at least was to me lol). This PR follows MGriffin's cleanup suggestion, and also moves the enum definition such that it can be referenced from across various AI functions in the future.

## **People who collaborated with me in this PR**
MGriffin and Hedara for explaining how this works and offering a solution

## **Discord contact info**
@Pawkkie

### CODE REVIEW

**Comment by Bassoonian** [comment]
I would personally ensure the enums have a clear prefix to indicate what they belong to, as `PIVOT` on its own is somewhat vague and potentially confusing later down the line.

**Comment by Pawkkie** [comment]
> I would personally ensure the enums have a clear prefix to indicate what they belong to, as `PIVOT` on its own is somewhat vague and potentially confusing later down the line.

Dyou mean rename from AIPivot to AIShouldPivot, or rename the PIVOT enum to SHOULD_PIVOT, or both?

**Comment by Bassoonian** [comment]
The latter! We actually don't have a lot of precedent for what eg `AIPivot` should be, but the actual enum entries should follow the define conventions and have a clear context in their name

**Comment by Pawkkie** [comment]
Fixed and conflicts resolved!

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
