### PR TITLE
Gender differences sprites, part 3

### PR DESCRIPTION
**Pull request by SubzeroEclipse**
## Description
Third batch of sprites of mons with gender based differences. This one adds:
- Meganium
- Ledyba/Ledian
- Sudowoodo
- Aipom/Ambipom
- Wooper/Quagsire
- Murkrow
- Wobbuffet
- Girafarig
- Gligar
- Steelix
- Heracross
- Sneasel (both regular and Hisuian)/Weavile
- Ursaring
- Piloswine/Mamoswine
- Octillery
- Houndoom
- Donphan
- Torchic (lol)/Combusken/Blaziken
- Beautifly
- Dustox
- Ludicolo
- Nuzleaf/Shiftry

Once again, big thanks to CyanSixFour for providing the sprites.

## **Discord contact info**
subzeroeclipse

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
I found some stuff that could be improved:
### Quagsire
Officially, there's no difference in the tail fin, and the dorsal fin doesn't go higher up Female Quagsire's back.

mGBA_cKHi7ryBMt
 
 

### Houndoom
Officially, Female Houndoom's horns are not only shorter, but thinner.
mGBA_F4QbjpapUO
 

### Nuzleaf
The female front sprite leaf doesn't look quite right to me. Because the current one is already very small, maybe we could make the male's bigger instead.
imagen imagen
HOME art for comparison:
imagen imagen

### Shiftry
Same as with Nuzleaf.
imagen imagen
HOME art for comparison:
imagen imagen

Everything else looks good to me :)

**Comment by CyanSMP64** [comment]
We based the front of both Houndoom and Quagsire on the BW designs, though looking at it now I feel like the back of female Nuzleaf could be shorter
IMG_8734 official back sprite for reference
Shiftry looks fine to me IMO, they are already shorter than they are in the official gen 4-5 sprites

**Comment by SubzeroEclipse** [comment]
Added sprites showcased on Discord for Quagsire and Nuzleaf. Not sure how to make Shiftry look better though :/

**Comment by AsparagusEduardo** [comment]
#### Quagsire and Nuzleaf changes
Good changes, looks good to me :)

#### Shiftry
Thinking about it more, you're right, Shiftry looks better now that I've given it a second look.

#### Houndoom
Huh, that's interesting. HGSS's sprites have their horn thickness change be more noticeable, while BW's sprites (which were based of HGSS) are just longer. Maybe it was a rushed thing or something related to the puppet animation in BW?
The HOME artwork shows the thickness being different, so I'm thinking we should go for HGSS style on this one.

HGSS
 

BW
 

HOME
imagen imagen

**Comment by SubzeroEclipse** [comment]
Ready for re-review =)

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
