### PR TITLE
Update almost all Gen 9 icon sprites + add the missing ones

### LINKED ISSUE #3553: Reminder: Add CyanSMP's Gen 9 icons
### Description

I saw this [commit ](https://github.com/leo60228/pokeemerald/commit/56f10adf1d817c8d3d35b18d803292477008ccda) and I thought it would be a good to the current icons.

### Discord contact info

doejohn126

### PR DESCRIPTION
**Pull request by kittenchilly**
## Description
Updates almost every Gen 9 icon to be better and fit the game more, in my opinion. I'd like people to give feedback and see if anything looks off to them. I mostly eyeballed the palette indexes so I may have missed or messed up something. Or if you think an old icon looks better than the new one.

Also adds the remaining icon sprites for the indigo disk mons that were missing, as well as all of Ogerpon's forms and Bloodmoon Ursaluna!
Also Partner Pikachu and Partner Eevee.

## Issue(s) that this PR fixes
Fixes #3553 since I believe most of these are actually the same sprites. Maybe with a different animation.

## **People who collaborated with me in this PR**
I mostly used this post on whackahack for the icons, but I also edited them myself a few times: https://whackahack.com/foro/threads/9-gen-sprites.67492/post-493662
Most of the icons from this whackahack post were derived from ezerart's custom icons:
https://www.deviantart.com/ezerart/art/Pokemon-Gen-9-Icon-sprites-3DS-Style-944211258
The new icon sprites for indigo disk mons were made by Roger Wrightshoe, also based on ezerart's icons.
Partner Pikachu and Partner Eevee sprites were from the pokecommunity thread, although I edited the sprites to include the heart and also make female partner pikachu more accurate (basing it off the pokesprite one).

## **Discord contact info**
kittenchilly

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Can you list the improvements that you did for the Gen 9 mons?

**Comment by kittenchilly** [comment]
> Can you list the improvements that you did for the Gen 9 mons?

"The additional changes were small, like moving the sprite down or recoloring a few pixels, nothing major. Also I meant additional changes to the spritesheet from the whackahack thread, if that wasn't clear" posting this from discord

**Comment by AlexOn1ine** [comment]
@AsparagusEduardo do you want to review this or should I do it?

**Comment by AsparagusEduardo** [comment]
> @AsparagusEduardo do you want to review this or should I do it?

If you want to, go ahead :)

**Comment by AlexOn1ine** [comment]
No better pal available for those? Previous colors looked better.
- Nymble 
- Lokix

Frame issues (the animation looks weird)
- Maushokl-Four
- Tinkatuff

Rest looks good.

**Comment by kittenchilly** [comment]
> No better pal available for those? Previous colors looked better.
> 
> * Nymble
> * Lokix
> 
> Frame issues (the animation looks weird)
> 
> * Maushokl-Four
> * Tinkatuff
> 
> Rest looks good.



> No better pal available for those? Previous colors looked better.
> 
> * Nymble
> * Lokix
> 
> Frame issues (the animation looks weird)
> 
> * Maushokl-Four
> * Tinkatuff
> 
> Rest looks good.

I noticed 

> No better pal available for those? Previous colors looked better.
> 
> * Nymble
> * Lokix
> 
> Frame issues (the animation looks weird)
> 
> * Maushokl-Four
> * Tinkatuff
> 
> Rest looks good.

I agree with Nymble and Lokix, but I thought the new sprites looked better besides the palette. I'll see if I can modify the palette.
For Maushold-four and Tinkatuff is it because of the face moving weirdly? I can probably fix that

**Comment by kittenchilly** [comment]
Ok, review addressed. See if it looks better.

**Comment by AlexOn1ine** [comment]
Sorry not for noticing earlier but those also have some anim issues:
Pawmi
Pawmo
Fidough

Tinkatuff looks good now
Maushold is still a bit weird but if you don't want to touch it anymore more it's fine. 

Also I noticed this directed to master. @AsparagusEduardo is this correct?

**Comment by kittenchilly** [comment]
I targeted master since I believe most other graphical changes have targeted master. Also I wouldn't really call this "new content"

**Comment by kittenchilly** [comment]
> Sorry not for noticing earlier but those also have some anim issues: Pawmi Pawmo Fidough
> 
> Tinkatuff looks good now, same for Nymble and Lokix Maushold is still a bit weird but if you don't want to touch it anymore more it's fine.
> 
> Also I noticed this is directed to master. @AsparagusEduardo is this correct?

Could you say what you think looks off about pawmi, pawmo, and fidough?

**Comment by AlexOn1ine** [comment]
> > Sorry not for noticing earlier but those also have some anim issues: Pawmi Pawmo Fidough
> > Tinkatuff looks good now, same for Nymble and Lokix Maushold is still a bit weird but if you don't want to touch it anymore more it's fine.
> > Also I noticed this is directed to master. @AsparagusEduardo is this correct?
> 
> Could you say what you think looks off about pawmi, pawmo, and fidough?

The animation is cut at like 70% of their body. Granted it is not as bad as it was with Tinkatuff but it is still somewhat noticeable.

**Comment by AlexOn1ine** [comment]
> > > Sorry not for noticing earlier but those also have some anim issues: Pawmi Pawmo Fidough
> > > Tinkatuff looks good now, same for Nymble and Lokix Maushold is still a bit weird but if you don't want to touch it anymore more it's fine.
> > > Also I noticed this is directed to master. @AsparagusEduardo is this correct?
> > 
> > 
> > Could you say what you think looks off about pawmi, pawmo, and fidough?
> 
> The animation is cut at like 70% of their body. Granted it is not as bad as it was with Tinkatuff but it is still somewhat noticeable.
> 
> /Edit: If someone else chimes in and think it's fine, then I would accept them. Example for pawmi, the other are similar:
> pawmi.mp4

@kittenchilly do you want to try and fix those? If not we can merge and open an issue for those since it just 3 icons.

**Comment by kittenchilly** [comment]
> > > > Sorry not for noticing earlier but those also have some anim issues: Pawmi Pawmo Fidough
> > > > Tinkatuff looks good now, same for Nymble and Lokix Maushold is still a bit weird but if you don't want to touch it anymore more it's fine.
> > > > Also I noticed this is directed to master. @AsparagusEduardo is this correct?
> > > 
> > > 
> > > Could you say what you think looks off about pawmi, pawmo, and fidough?
> > 
> > 
> > The animation is cut at like 70% of their body. Granted it is not as bad as it was with Tinkatuff but it is still somewhat noticeable.
> > /Edit: If someone else chimes in and think it's fine, then I would accept them. Example for pawmi, the other are similar:
> > pawmi.mp4
> 
> @kittenchilly do you want to try and fix those? If not we can merge and open an issue for those since it just 3 icons.

We can go ahead and merge it, let me resolve conflicts

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
