### PR TITLE
Add missing Heal Block functionalities

### PR DESCRIPTION
**Pull request by Sneed69**
Heal block now stops healing from the following:
- Strength Sap
- Leftovers / Black Sludge
- Grassy Terrain
- Berries
- Shell Bell

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Berries, Leftovers/Black Sludge and Shell Bell should have a config imo

**Comment by Sneed69** [comment]
If the items used a generation based config then EFFECT_ABSORB would also need to use it or it would be inconsistent.

**Comment by AsparagusEduardo** [comment]
> If the items used a generation based config then EFFECT_ABSORB would also need to use it or it would be inconsistent.

That's right, forgot to mention it.

**Comment by Sneed69** [comment]
Then I'm guessing there would be some hefty AI changes involved to calculate if an HP draining move should be used if it's not gonna heal?

**Comment by Sneed69** [comment]
Added generation specific stuff
The AI already handles checking absorb value with heal block so no changes were needed.

**Comment by Sneed69** [comment]
Added Heal Pulse to the block list.
Heal Block and Pollen Puff now fail is used against a heal blocked mon.
Couldn't find a way to prevent those moves from targeting heal blocked mons though.

**Review by ghoulslash — APPROVED** [review]
I'll handle a separate PR preventing pollen puff ally targeting from heal block

**Comment by AsparagusEduardo** [comment]
Suggestion for future PRs: If the PR addresses an Issue, please tag it in order to make it easier to know to close it after merging the PR.

**Pull request merged**
