### PR TITLE
Tag previously-unused icon pals as such in code.

### PR DESCRIPTION
**Pull request by GraionDilach**
Incase someone still assume them being disabled (like I did earlier today on Team Aqua discord).

## **Discord contact info**
graiondilach

### CODE REVIEW

**Review by Bassoonian — APPROVED** [review]

**Comment by Bassoonian** [comment]
Can we rebase this to master? It's arguably a fix and not a new feature, so the sooner it can roll out, the better imo

**Comment by GraionDilach** [comment]
Done.

**Comment by AsparagusEduardo** [comment]
> Can we rebase this to master? It's arguably a fix and not a new feature, so the sooner it can roll out, the better imo

It's not really a fix, just cleanup.

**Comment by GraionDilach** [comment]
Reverted to upcoming.

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
