### PR TITLE
Setting Modern as default

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
@gruxor is happy.

`make` now does modern, while `make agbcc` compiles using agbcc. `make modern` still does its thing.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by DizzyEggg** [comment]
The future is now

**Comment by SBird1337** [comment]
The CI seems to still build tests with agbcc.

**Comment by mrgriffin** [comment]
> The CI seems to still build tests with agbcc. (But also they are currently broken on modern)

Oh yeah... idk how others feel, but I'd really want the tests to run and pass before we merge this PR.

[There was a tiny amount of discussion on Discord, but nothing particularly helpful.](https://discord.com/channels/419213663107416084/1077009799293710357/1147546810844454983) I haven't had the time to look into this, but a reasonable first step might be to look at the failing tests running in a visual mgba.

**Comment by AsparagusEduardo** [comment]
> Oh yeah... idk how others feel, but I'd really want the tests to run and pass before we merge this PR.

I completely agree.

**Comment by AsparagusEduardo** [comment]
Set as draft until tests work on modern.

**Comment by AsparagusEduardo** [comment]
CI set to Modern and tests pass :)

**Review by mrgriffin — APPROVED** [review]
Time to merge this? :eyes:

**Comment by SBird1337** [comment]
Can we rebase to upcoming one more time to get CI confirmation? :)

**Comment by mrgriffin** [comment]
> Can we rebase to upcoming one more time to get CI confirmation? :)

Good call, it's complaining about my ModifyPersonalityForNature test :kekw: 
```diff
diff --git a/test/battle/trainer_control.c b/test/battle/trainer_control.c
index 99bea0e8cc..192b12980c 100644
--- a/test/battle/trainer_control.c
+++ b/test/battle/trainer_control.c
@@ -123,7 +123,7 @@ TEST("CreateNPCTrainerPartyForTrainer generates different personalities for diff
 
 TEST("ModifyPersonalityForNature can set any nature")
 {
-    u32 personality, nature, j, k;
+    u32 personality = 0, nature = 0, j, k;
     for (j = 0; j < 64; j++)
     {
         for (k = 0; k < NUM_NATURES; k++)
```

**Comment by Jaizu** [comment]
I think this PR is broken and needs this 2 aditional changes... right? If someone more savy than me with makefiles can confirm I would be grateful.
image

**Comment by mrgriffin** [comment]
> I think this PR is broken and needs this 2 aditional changes... right? If someone more savy than me with makefiles can confirm I would be grateful.

Yeah that sounds right. [`.PHONY`](<https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html>) is needed because otherwise `touch agbcc` will mean `make agbcc` does nothing (until one of its dependencies changes). And building the tools is obviously necessary.

**Comment by AsparagusEduardo** [comment]
> Yeah that sounds right. [`.PHONY`](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html) is needed because otherwise `touch agbcc` will mean `make agbcc` does nothing (until one of its dependencies changes). And building the tools is obviously necessary.

I'm out until Friday, so someone can PR to this PR the merge with upcoming plus these changes and I'll accept it.

**Comment by mrgriffin** [comment]
> I'm out until Friday, so someone can PR to this PR the merge with upcoming plus these changes and I'll accept it.

https://github.com/AsparagusEduardo/pokeemerald/pull/24

**Review by mrgriffin — APPROVED** [review]

**Comment by AsparagusEduardo** [comment]
https://www.youtube.com/watch?v=jeMAHzsafcw

**Pull request merged**
