### PR TITLE
Status2/3/4 refactoring

### PR DESCRIPTION
**Pull request by cfmnephrite**
## Description
Replaces statuses2/3/4 with a bitfield within `BattlePokemon`

- status2/3/4 bit flags removed
- status2/3/4 renamed to "volatile statuses" and all references thereto are renamed
- added "generic" functions for checking/applying volatiles statuses and for running associated animations

DRAWBACK
To add a volatile status to the "generic" function, it is necessary to define a corresponding enum in `include/constants/battle.h` of the form `ENUM_VOLATILE_STATUS_X` and add it to the switch case in `battle_util.c`.

## Feature(s) this PR does NOT handle:
Does not merge anything else further into `BattlePokemon`

### CODE REVIEW

**Comment by ghoulslash** [comment]
Im seeing drawbacks but not really many advantages to this refaftor. Can you elaborate on the value added?
Also this will also need to handle the battle debug menu 
 (I see it's still in draft but want to make sure that's on the to-do list)

**Comment by cfmnephrite** [comment]
> Im seeing drawbacks but not really many advantages to this refaftor. Can you elaborate on the value added? Also this will also need to handle the battle debug menu (I see it's still in draft but want to make sure that's on the to-do list)

This is just stage 1 of a long process of unifying various structs into `BattlePokemon`. Eventually, the aim is just to have one large bitfield representing every possible volatile status - something which I believe would be a massive boon to usability - inside that struct. I'm *starting* with this because I just prefer doing the more laborious parts first before I get burned out. Hop into the discussion [here](https://discord.com/channels/419213663107416084/1205029201460338778) :)

**Comment by AsparagusEduardo** [comment]
> I'm _starting_ with this because I just prefer doing the more laborious parts first before I get burned out. Hop into the discussion [here](https://discord.com/channels/419213663107416084/1205029201460338778) :)

This might be the most controversial of them, so I would leave this for later since it needs more discussion from the looks of it 👀

**Comment by cfmnephrite** [comment]
Closed because tbh, I don't really think this is the way to go anymore. I'd rather keep the option for a generic function than have an easy-to-use bitfield.

**Pull request closed without merging**
