### PR TITLE
Pret merge (2024/03/24)

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
SHA1 before merge: `4a6dd2595d7c2ee3962db6f08a8eed87b611bfee`
SHA1 after merge: `7b81da5544985649fc39404b8fefa0906052c848`

## Images
I can't figure out why the hash changes with the following changes:
image
image
image
image
image
image

I would like to know before doing the merge.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by Bassoonian** [comment]
Does the hash also differ on agbcc?

**Comment by DizzyEggg** [comment]
> Does the hash also differ on agbcc?

That's a good question. If the hash is the same on agbcc, then it's fine, it's likely modern does better optimizations with the 'non-hacky' code.

**Comment by AsparagusEduardo** [comment]
> Does the hash also differ on agbcc?

> That's a good question. If the hash is the same on agbcc, then it's fine, it's likely modern does better optimizations with the 'non-hacky' code.

Good point. I'll test it there in a bit.

**Comment by AsparagusEduardo** [comment]
Sorry for the delay. Confirmed that agbcc's hash is `a1662dcac77032df0dc98a9626bc4132a799a782` both before and after.

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
