### PR TITLE
Wandering Spirit

### PR DESCRIPTION
**Pull request by ghoulslash**
Adds the ability Wandering Spirit

wandering_spirit

Currently, the ability pop up system cannot handle two popups on screen at once due to the fact that the tiles are allocated from a sprite tile tag, and so both sprites would have the same ability/name. One could theoretically have two separate tile tags but this implementation works well, it is just a long transition.

### CODE REVIEW

**Comment by BuffelSaft** [comment]
Hunger Switch is missing from the list of unaffected abilities, but other than that it's looking good so far.

I need to test a couple of things in sword too:
- Should Wandering Spirit activate if the attacker already has Wandering Spirit?
- Should switch-in abilities activate when swapped, as they do with Skill Swap (I think not but need to confirm)?

**Comment by BuffelSaft** [comment]
> * Should Wandering Spirit activate if the attacker already has Wandering Spirit?

Tested, yes it should, so no changes needed there.

> * Should switch-in abilities activate when swapped, as they do with Skill Swap (I think not but need to confirm)?

Switch in abilities should activate when swapped. Tested against Intimidate and Mold Breaker in Sword.

**Comment by ghoulslash** [comment]
> 
> 
> > * Should Wandering Spirit activate if the attacker already has Wandering Spirit?
> 
> Tested, yes it should, so no changes needed there.
> 
> > * Should switch-in abilities activate when swapped, as they do with Skill Swap (I think not but need to confirm)?
> 
> Switch in abilities should activate when swapped. Tested against Intimidate and Mold Breaker in Sword.

Added the switchinabilities call to wandering spirit. ready for re-review.

**Review by BuffelSaft — APPROVED** [review]

**Comment by BuffelSaft** [comment]
Some conflicts need resolving, but after that this can be merged.

**Comment by ghoulslash** [comment]
> 
> 
> Some conflicts need resolving, but after that this can be merged.

ready to be merged

**Review by BuffelSaft — APPROVED** [review]

**Pull request merged**
