### PR TITLE
Reverted Intimidate Rework

### LINKED ISSUE #2619: Some abilities are broken in certain battle types like battle factory
Have an enemy mon
Ko it
Enemy trainer sends a mon with Intimidate
Popup gets enabled from player side and not from enemies, including wrong buffers on the text.

SBird made a test for this and it's confirmed to be broken.

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Closes #2619

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by LOuroboros** [comment]
Ready for review.

The issue with Intimidate in the Battle Factory was happening due to my rework of Intimidate, and considring that I don't really know what could be causing it and that it was working fine before, I just ended up reverting the whole thing. I did add the appropriate check for Guard Dog to what was there though.

**Comment by SBird1337** [comment]
Did we ever figure out why this regresses
```
U-turn does not switch the user out if Wimp Out activates
```
to fail?

**Comment by mrgriffin** [comment]
> Did we ever figure out why this regresses
> 
> ```
> U-turn does not switch the user out if Wimp Out activates
> ```
> 
> to fail?

The test passes with:
```diff
-        TURN { MOVE(player, MOVE_U_TURN); SEND_OUT(opponent, 1); }
+        TURN { MOVE(player, MOVE_U_TURN); SEND_OUT(opponent, 1); SEND_OUT(player, 1); }
```
i.e., it seems the regression is that now the player has to send out a Pokémon even though it should have been suppressed by Wimp Out activating.

When I `git diff` against upcoming I see this:
```diff
-    case VARIOUS_JUMP_IF_EMERGENCY_EXITED:
-        if (gSpecialStatuses[gActiveBattler].emergencyExited)
-            gBattlescriptCurrInstr = T1_READ_PTR(gBattlescriptCurrInstr + 3);
-        else
-            gBattlescriptCurrInstr += 7;
-        return;
```
So it seems the various got lost somehow on this branch?

**Comment by LOuroboros** [comment]
> ```diff
> VARIOUS_JUMP_IF_EMERGENCY_EXITED
> ```

OH. Looking at the diff, I did remove it. It was an accident. Will restore.

**Comment by DizzyEggg** [comment]
Done in #2712

**Pull request closed without merging**
