### PR TITLE
Fix speed ties

### PR DESCRIPTION
**Pull request by mrgriffin**
See #4772, [this is Alex's suggestion of caching the speed tie-breaks at the start of the turn](https://discord.com/channels/419213663107416084/774393519569502268/1250525738772336710).

### CODE REVIEW

**Comment by mrgriffin** [comment]
The doubles test fails, and I think this is because each battler shouldn't have a 50-50 chance of being faster than another. As an example, if battler1's bit says it's faster than battler2 and slower than battler3, but battler2's bit says it's faster than batlter3 then we have 3 > 1 > 2 from the first and 2 > 3 from the second, and that's obviously inconsistent.

I think the correct approach would be to generate a number 0..23 which corresponds to the number of permutations of 4 (`MAX_BATTLERS_COUNT`) elements.

**Comment by mrgriffin** [comment]
> The doubles test fails

Pushed a fix for this, which is exactly as described in my message—I generate a number 0..23 and interpret that as the relative order of all four battlers.

**Comment by mrgriffin** [comment]
I've un-drafted this. I would like to make the doubles test faster, but I don't think it's possible to do in the test system as it exists rn.

My idea is to replace the 24 `PARAMETRIZE`s with just counting the order that each battler goes in, and then in a `FINALLY` we can check that turn order "slot" contains the same count for each battler. But as I say, I'm not sure how to do that. If anybody has suggestions then I'm all ears :)

**Comment by hedara90** [comment]
Could 3 different fixed damage moves and a healing move work?
Nature's Madness deals 50%, Crush Grip BP depends on HP of target, Dragon Rage 40 and Recover heals 50% of total.
I haven't done the math, but all the orders should result in a different final HP for the target if its max HP is less than 80, I think.

**Comment by mrgriffin** [comment]
Oh, that's clever! My gut feeling is that should work :thinking:

**Comment by hedara90** [comment]
**Attackers**
A level 22 Wobbuffet with Crush Grip
Something using Nature's Madness or equivalent
Something at level 25 using Seismic Toss
**Target**
A level 13 Wobbuffet using Life Dew

I think this could work, but I didn't calculate all permutations.

**Comment by AlexOn1ine** [comment]
Any reason we can't merge this? This solves the issue. 

Also conflicts. I made a new function for ai speed calcs and removed the randomness during a tie but now that there is consistency across the board we should bring it back.

**Comment by hedara90** [comment]
Oh, I was working on trying to set up a test that didn't have the massive array of turn orders.
But I hit some problems with it, I might have a setup that works though.
Life Dew, Crush Grip, Endeavor and Super Fang might result in unique final HP values depending on the speed tie.

**Comment by AlexOn1ine** [comment]
> Life Dew, Crush Grip, Endeavor and Super Fang might result in unique final HP values depending on the speed tie.
hm, I feel like we shouldn't hold up a merge because of this since it solves a crucial problem.

**Comment by hedara90** [comment]
Yea, the test can wait.
I'll try to calculate it soon, but Crush Grip makes everything so much more complicated.

**Comment by AlexOn1ine** [comment]
> Any reason we can't merge this? This solves the issue.
> 
> Also conflicts. I made a new function for ai speed calcs and removed the randomness during a tie but now that there is consistency across the board we should bring it back. Not the function but the speed tie check. I think having the separate function has other benefits.


@mrgriffin conflicts :eyes:

**Comment by mrgriffin** [comment]
> conflicts

Resolved! (Hopefully—I only ran the "Turn order" tests locally because it's bedtime :sweat_smile:)

**Comment by AlexOn1ine** [comment]
> > conflicts
> 
> Resolved! (Hopefully—I only ran the "Turn order" tests locally because it's bedtime 😅)

For some reason `test/battle/ability/comatose.c:48: Unmatched ANIMATION` fails. Which is weird.

**Comment by mrgriffin** [comment]
> For some reason `test/battle/ability/comatose.c:48: Unmatched ANIMATION` fails. Which is weird.

I watched the replay and it's _very_ weird—the Ditto uses Toxic on itself (that's probably a difference in the speed ties in the old and new code)... But as far as Toxic goes I would guess what's happening is that Ditto tries to go for Celebrate which would be the first move in its moveset... but the first move is now Toxic due to it transforming.

**Review by tertu-m — APPROVED** [review]

**Comment by hedara90** [comment]
Test setup:
**Player**
Wobbuffet, 480 HP, 100 Def
Anything
**Opponent**
Wobbuffet, 490 HP (default), 100 Atk
Anything

**Turn**
Player Wobbuffet, Endeavor -> Opponent Wobbuffet
Player Anything, Life Dew
Opponent Wobbuffet, Crush Grip -> Player Wobbuffet
Opponent Anything, Super Fang -> Player Wobbuffet

**Possible Outcomes**
| Player Wobb HP |	Foe Wobb HP |
| --- | --- |
| 188 |	360 |
| 189 |	360 |
| 261 |	360 |
| 235 |	360 |
| 262 |	360 |
| 202 |	360 |
| 189 |	378 |
| 189 |	189 |
| 189 |	480 |
| 138 |	480 |
| 188 |	240 |
| 188 |	188 |
| 262 |	262 |
| 262 |	142 |
| 202 |	403 |
| 202 |	202 |
| 262 |	283 |
| 202 |	283 |
| 235 |	180 |
| 261 |	180 |
| 235 |	235 |
| 235 |	300 |
| 261 |	141 |
| 261 |	261 |

**Pull request merged**
