### PR TITLE
Added config for shiny chances

### LINKED ISSUE #3910: Shiny chance config
### Description

Should be self-explanatory

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by fdeblasio**
## Description
This PR adds a config for the odds of a shiny Pokemon to match Gen 6+'s increased chances

## Issue(s) that this PR fixes
Fixes #3910 

## **Discord contact info**
Frankfurter0

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Doesn't it break saves if set to TRUE by default? 🤔

**Comment by mrgriffin** [comment]
> Doesn't it break saves if set to TRUE by default? 🤔

Yeah, it can turn Pokémon that were not shiny into shiny Pokémon when going from the old `SHINY_ODDS` to the new one. Or vice-versa when going from the new to the old.

Break might be too strong a word, but it's not backwards-compatible in the sense we usually strive for.

**Comment by AsparagusEduardo** [comment]
Yeah, that's why we haven't done it until now. The original BoxMon refactor was able to handle this, but the current one doesn't afaik.

**Comment by mrgriffin** [comment]
Copying from #expansion-dev:

> I think it'd be better to just directly compute [`isShiny`](<https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/pokemon.c#L883>) from `SHINY_ODDS` (plus the Shiny Charm logic etc etc)?
>
> I don't think there's any downsides to this approach. It won't affect existing Pokémon regardless of what `SHINY_ODDS` is set to. (And we've already given up on transferring Pokémon to non-current Expansion so it doesn't matter whether they'd be shiny on other games)

**Comment by AlexOn1ine** [comment]
@fdeblasio do you want to work on this further, or can it be closed?

**Comment by fdeblasio** [comment]
> @fdeblasio do you want to work on this further, or can it be closed?

This can be closed

**Pull request closed without merging**
