### PR TITLE
Fixed Bad Dream's ability popup message

### LINKED ISSUE #2429: Bad Dream's Ability Pop Up appears if the mon that has the ability is the one asleep
In this example, only Oddish has Bad Dreams.
baddreams2

In this second example, both Zygarde and Oddish have Bad Dreams.
baddreams

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Fixes #2429

## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by BuffelSaft** [comment]
This shouldn't need to loop through all battlers, it's called in a while loop that already does that. I think it's just checking the wrong battlers in the if statement?
```
if (gBattleMons[battler].status1 & STATUS1_SLEEP
    || gBattleMons[BATTLE_OPPOSITE(battler)].status1 & STATUS1_SLEEP
    || GetBattlerAbility(battler) == ABILITY_COMATOSE
    || GetBattlerAbility(BATTLE_OPPOSITE(battler)) == ABILITY_COMATOSE)
```
This should be checking the opposite battler and the opposite battler's ally, instead of the opposite battler and the battler that has Bad Dreams.

It definitely needs the `IsBattlerAlive()` check added though.

**Comment by BuffelSaft** [comment]
Oh there's also another loop in `Cmd_trygetbaddreamstarget`, I'm not so sure what's going on with this now.

**Comment by AsparagusEduardo** [comment]
It needs to loop through all of them because it should also affect allies.
> At the end of each turn, each adjacent [sleeping](https://m.bulbapedia.bulbagarden.net/wiki/Sleep_(status_condition)) opponent takes damage equal to 1/8 of its maximum HP.

**Comment by LOuroboros** [comment]
The battle script also has a loop though, and it uses `trygetbaddreamstarget` which runs yet another loop.

Wouldn't this be a good chance to optimize the code for Bad Dreams' effect? :eyes:

**Comment by BuffelSaft** [comment]
Yeah, the battle script already loops and so does `DoBattlerEndTurnEffects` . `DoBattlerEndTurnEffects` loops through every battler to see if it should try to activate bad dreams, and then the battle script loop handles the damage part.
Both are needed, as it needs to loop through all battlers to try to trigger the ability, and then loop through both foes to damage them if the conditions are met (it doesn't affect the bad dream's mon's ally, just its opponents).

The changes to that `if` I suggested fix the issue, it doesn't need another loop added.

**Comment by AsparagusEduardo** [comment]
Going to confirm if Bad Dreams affect allies or not, one sec.

**Comment by AsparagusEduardo** [comment]
You're right, it doesn't affect allies. Will fix in a sec.
melonDS_2TldypXFzd

**Review by BuffelSaft — APPROVED** [review]

**Pull request merged**
