### PR TITLE
Cleaned up a bit of code with GetBattlerPartyData

### LINKED ISSUE #2656: Make more use of GetBattlerPartyData
This is a handy function whose usage would clean a bit the battle code I think.
Its name is a bit long, so perhaps we could rename it so something like: "GetBattlerMon" or sth else.

Similarly, we could also have two additional functions for GetBattlerPartyDataPlayer and GetBattlerPartyDataOpponent(names are subject to change)

```
struct Pokemon *GetBattlerPartyData(u8 battlerId)
{
    struct Pokemon *mon;
    if (GetBattlerSide(battlerId) == B_SIDE_PLAYER)
        mon = &gPlayerParty[gBattlerPartyIndexes[battlerId]];
    else
        mon = &gEnemyParty[gBattlerPartyIndexes[battlerId]];

    return mon;
}
```

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Closes #2656

The function was already present. I just renamed it to represent more what it does and cleaned up the code I could

### CODE REVIEW

**Comment by hedara90** [comment]
I don't know if `GetBattlerPartyData` is the best name for the function. To me is sounds like it would return a reference to a party (`Pokemon` array) instead of a reference to a single `Pokemon`.

**Comment by AlexOn1ine** [comment]
> I don't know if `GetBattlerPartyData` is the best name for the function. To me is sounds like it would return a reference to a party (`Pokemon` array) instead of a reference to a single `Pokemon`.

so keep the old name?

**Comment by hedara90** [comment]
Yea, more descriptive of what it does

**Comment by AlexOn1ine** [comment]
Would `GetPartyBattlerData` work better? I see how the current name is confusing but I think it would be good to have a reference to party because it is the job of the function.

**Comment by hedara90** [comment]
> Would `GetPartyBattlerData` work better? I see how the current name is confusing but I think it would be good to have a reference to party because it is the job of the function.

That works

**Comment by AlexOn1ine** [comment]
ready for review again

**Review by hedara90 — APPROVED** [review]

**Pull request merged**
