### PR TITLE
Fixes Salt Cure visual bug if mon fainted by direct attack

### LINKED ISSUE #3386: Salt Cure kill Visual Bug
### Description

When a Pokemon with Salt Cure kills a Pokemon, a Visual Bug like in the following image occurs. I think the reason could be that the "Pokemon is being Salt Cured" text is replacing the fainted text. Keeping the last Pokemons Sprite and Colors still there.

https://cdn.discordapp.com/attachments/1083396892739776643/1158754490434977892/pokeemerald-3.png?ex=652e8937&is=651c1437&hm=d6d55022976f7e28882dbe62d8540655fac9e647fd6420696023bce6e91fd683&

### Version

upcoming (Edge)

### Upcoming Version

7c7396c

### Discord contact info

._.terra._.

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #3386

Before:
salt_cure_bug
After:
salt_cure

### CODE REVIEW

**Comment by DizzyEggg** [comment]
All good, it's only missing a test.

**Review by DizzyEggg — CHANGES_REQUESTED** [review]
tests

**Comment by AlexOn1ine** [comment]
Test added.

**Comment by DizzyEggg** [comment]
Salt Cure is fine, but not sure about the other one. Is it actually bad that there are two options that do the same thing? I assume giving TMs is something that's often done when debugging, so it's easier for users to quickly locate this given it's in 2 places. What do others think about it?

**Comment by AlexOn1ine** [comment]
> Salt Cure is fine, but not sure about the other one. Is it actually bad that there are two options that do the same thing? I assume giving TMs is something that's often done when debugging, so it's easier for users to quickly locate this given it's in 2 places. What do others think about it?

Yeah, I don't mind removing it from here. I just did it because it was an opened issue and relatively easy to fix.

**Comment by AlexOn1ine** [comment]
Reverted the removal of the debug TM/HM duplicate case

**Review by DizzyEggg — APPROVED** [review]

**Pull request merged**
