### PR TITLE
Missing ignoreSubstitute flags

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Title.

Noticed by Lhea on discord. 

[moves_bypassing_sub.txt](https://github.com/rh-hideout/pokeemerald-expansion/files/15442367/moves_bypassing_sub.txt) (showdown flags)

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
```
- Tests FAILED :       1    Add TESTS='X' to run tests with the defined prefix.
  - Defog does not lower evasiveness if target behind Substitute.
```
So that's why it was commented out. We should probably figure out what the correct path here is.

**Comment by AsparagusEduardo** [comment]
Bypassing Substitute is only in Gen 4 apparently.
image

**Comment by AsparagusEduardo** [comment]
Actually, let me check in-game in Gen 5 to make sure

**Comment by AsparagusEduardo** [comment]
Confirmed. Gen 5 Defog doesn't work on if the target is behind a Substitute.
chrome_3gVt9Dw1o4

**Comment by AlexOn1ine** [comment]
Updated the defog flag to: `B_UPDATED_MOVE_FLAGS == GEN_4`

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
