### PR TITLE
Fixes move relearner limitation

### LINKED ISSUE #5633: Longer learnsets aren't fully displayed in the move relearner
### Description

Some of the level-up learnsets from later gens have got rather lengthy (especially gen 8/9 who have mons able to remember moves from their pre-stages, Gallade being a notable example) and cannot be shown entirely when using the move relearner (and also when checking them in TheXaman's HGSS Dex).
pokeemerald-0

### Version

upcoming (Edge)

### Upcoming/master Version

ac1dd857f79a7b42a6b93b00221e83af5254ee3f

### Discord contact info

subzeroeclipse

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #5633

### CODE REVIEW

**Comment by Bassoonian** [comment]
Is the 60 an arbitrary number or one based on actual truth? It's worth noting that the move relearner has a separate `MAX_RELEARNER_MOVES`, which means this PR doesn't actually affect the move relearner

**Comment by AlexOn1ine** [comment]
> Is the 60 an arbitrary number or one based on actual truth? It's worth noting that the move relearner has a separate `MAX_RELEARNER_MOVES`, which means this PR doesn't actually affect the move relearner

`MAX_RELEARNER_MOVES` uses `MAX_LEVEL_UP_MOVES`. We can make the change there. 

I chose 60 so it is big enough we don't get any complaints anymore. I don't think setting it to the longest learnset is any better

**Comment by Bassoonian** [comment]
It's not that easy unfortunately, `MAX_RELEARNER_MOVES` uses the constant you edited, but it is capped at 25 for EWRAM reasons

**Comment by AlexOn1ine** [comment]
> It's not that easy unfortunately, `MAX_RELEARNER_MOVES` uses the constant you edited, but it is capped at 25 for EWRAM reasons

I see. So what should I change then?

**Pull request closed without merging**
