### PR TITLE
Added Ogerpon Tera Sprites

### PR DESCRIPTION
**Pull request by hedara90**
Added sprites for Ogerpon Tera forms.

## Description

Tera form front sprites have been added, those are re-scaled from KingOfThe-X-Roads' 96px Ogerpon Tera sprites.
Tera form back sprites have been added, those are re-scaled from Caruban's 288px sprites for Essentials v21.1.

## Images

OgerponSpritesTeraOnly

## **Discord contact info**

hedara

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
references in the family species files are still wrong

**Comment by hedara90** [comment]
Fixed the back sprite offset, changed the regular back sprites to make it work due to how the Ogerpon species define works.
Also fixed a palette issue with the Hearthflame Tera back sprite.

**Comment by AlexOn1ine** [comment]
If someone wants to review, please do. I won't have time tomorrow and forgot about it today.

**Comment by kittenchilly** [comment]
The tera forms don't need a separate icon.png. They are always the same as the base form, so they will always be duplicates

**Comment by AsparagusEduardo** [comment]
> The tera forms don't need a separate icon.png. They are always the same as the base form, so they will always be duplicates

Could be a config

**Comment by kittenchilly** [comment]
Oh, I see why. Its because the macro uses the form name for the icon, and it has to be changed for these new sprites. I think its fine right now since I believe we'd have to change a bit about how the macro works, so we can just do it in another PR.

**Comment by hedara90** [comment]
Ogerpon being defined in a macro was the source of a few problems for adding tera sprites.

**Comment by AsparagusEduardo** [comment]
I'll PR a new macro definition to avoid the need of duplicate files

**Comment by hedara90** [comment]
Oh, sorry, I completely forgot about it.

**Comment by AsparagusEduardo** [comment]
https://github.com/hedara90/pokeemerald-expansion/pull/2

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
