### PR TITLE
Replaced every Gen. 6 and 7 cry with USUM dumps

### LINKED ISSUE #1332: Extremely high sample rate for cries
Currently, cries in Pokemon Expansion are sampled at a rate of 44.1 kHz. This is extremely high for the GBA, and as a result, Pokemon Expansion takes around 29 MB.

UltimaSoul: "The problem is that they're exported at a higher sample rate as .aif files which is generally higher than the ripped versions so it takes more space unecessarily. Secondly, they're currently uncompressed, so likely it'd be a smarter move to not used uncompressed cries."

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Potentially closes #1332 I guess?
This PR basically replaces every Gen. 6 and 7 species cry *(minus Meltan and Melmetal for obvious reasons)* with dumps that come straight from USUM.

Showcase:

https://user-images.githubusercontent.com/4485172/147604908-29ee6341-aaf5-40ea-b917-45d76627acbf.mp4

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
I compiled without padding to see how much storage would change. 
- Current: 27.505.512 bytes (26.2 MB)
- This PR: 30.758.436 bytes (29.3 MB)
- Difference: 3.252.924 bytes (3.1 MB)

🤔

**Comment by LOuroboros** [comment]
> I compiled without padding to see how much storage would change.
> 
>     * Current: 27.505.512 bytes (26.2 MB)
> 
>     * This PR: 30.758.436 bytes (29.3 MB)
> 
>     * Difference: 3.252.924 bytes (3.1 MB)
> 
> 
> 🤔

The goal is not size efficiency but consistency. I believe we have decided to use cries ripped straight from the games.

I hope I'm not misremembering.

**Comment by AsparagusEduardo** [comment]
> The goal is not size efficiency but consistency. I believe we have decided to use cries ripped straight from the games.
> 
> I hope I'm not misremembering.

I remember that was the case with the goal of saving space. That's literally what #1332 is talking about

**Comment by LOuroboros** [comment]
> > The goal is not size efficiency but consistency. I believe we have decided to use cries ripped straight from the games.
> > I hope I'm not misremembering.
> 
> I remember that was the case with the goal of saving space. That's literally what #1332 is talking about

Judging by previous conversations inside the Discord server, I believe the saving of space would come from using the `cry` macro instead of the `cry_uncomp` one in `gCryTable` and `gCryTable_Reverse`?

We'd just need to define how to go about it. Do we use `cry` for entire generations, or do we decide on a species basis?

**Comment by BuffelSaft** [comment]
> We'd just need to define how to go about it. Do we use `cry` for entire generations, or do we decide on a species basis?

It's done on a species basis, as some cries sound really bad/completely wrong when compressed with `cry` (e.g. Dwebble). Most sound fine when compressed though, so it's worth doing to save space.

**Comment by LOuroboros** [comment]
Superseded by #2019.

**Pull request closed without merging**
