### PR TITLE
Remove Special Handling for Deoxys

### PR DESCRIPTION
**Pull request by ultima-soul**
## Description

Removes special handling for Deoxys and cleans up some functions, their arguments, and local variables plus data.

## **Discord contact info**

UltimaSoul#4017

### CODE REVIEW

**Comment by ExpoSeed** [comment]
merge conflicts :(

**Comment by ultima-soul** [comment]
Resolved merge conflicts.

**Comment by ExpoSeed** [comment]
It seems okay to me on Deoxys's end, I'm just not sure if this will have any side effects for castform

**Review by ExpoSeed — APPROVED** [review]
Castform is handled elsewhere so it should be fine

**Review by ghoulslash — APPROVED** [review]

**Pull request merged**
