### PR TITLE
Master into upcoming merge

### PR DESCRIPTION
**Pull request by Bassoonian**
There's been a bunch of bug fixes lately that are not yet in upcoming atm, so see title

### CODE REVIEW

**Review by AsparagusEduardo — APPROVED** [review]

**Comment by AsparagusEduardo** [comment]
Yeah, my bad ^^;

**Comment by AsparagusEduardo** [comment]
oh, uh... I don't think `master` itself should've been used for this ._.

**Comment by Bassoonian** [comment]
Oh? I thought that's what you always did

**Comment by AsparagusEduardo** [comment]
I did it not via PR, but directly to the branch ^^;
I was worried for a second because in the list of branches, it showed this PR, but now it seems to be gone. 🤔 
image
I think this way of doing it is good as well, so sorry about worrying you.

**Pull request merged**
