### PR TITLE
Sync battle engine

### PR DESCRIPTION
**Pull request by ExpoSeed**

### CODE REVIEW

**Comment by ExpoSeed** [comment]
@Pyredrid played through the whole game on this branch, no observable bugs unique to this merge

**Comment by Pyredrid** [comment]
Can confirm, beat the game with no major issues cropping up.

**Review by ghost — APPROVED** [review]

**Review by AsparagusEduardo — APPROVED** [review]
I've done tests to check if current issues are still present after the merge and they still are, so we can at least be sure that the merge is good in that sense.
As this is the first merge in a long time, if there are issues that might originate from this, we can deal with them as they come up.

**Comment by ExpoSeed** [comment]
i stink at making prs to the right branch

**Pull request closed without merging**
