### PR TITLE
Moved ability and move effect tests to folders by letter

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
I started realizing that after adding TODO tests, the amount of test files grew a lot, so I made this PR to help organization.

## Feature(s) this PR does NOT handle:
Only moved the files, didn't do anything else to make this easier to review.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
is there a reason for this change?

**Comment by AlexOn1ine** [comment]
is there a reason why the size of the folder would bother us?

**Comment by AsparagusEduardo** [comment]
> is there a reason for this change?

Easier to browse on interfaces such as VSCode. Whenever I open the `move_effect` or `ability` folders, they always start on top, making it harder to search for a specific file. With 352 effects and 311 abilities, scrolling quickly becomes a pain.

Before:
image
After
image

**Comment by AlexOn1ine** [comment]
why not search with `CTRL+SHIFT+P`?

**Comment by AsparagusEduardo** [comment]
> is there a reason why the size of the folder would bother us?
> 
> Because I generally think this is a bad change for ppl who write tests.

Bad how? We already have folders to split tests and I don't recall any complaints with them

**Comment by AlexOn1ine** [comment]
> > is there a reason why the size of the folder would bother us?
> > Because I generally think this is a bad change for ppl who write tests.
> 
> Bad how? We already have folders to split tests and I don't recall any complaints with them

I just think it is redundant to introduce an other folder. It just makes it obscure.

**Comment by AsparagusEduardo** [comment]
> I just think it is redundant to introduce an other folder. It just makes it obscure.

If you use Ctrl+P, you'll find the file anyway. If you don't, you can find the file by its name in the same way

**Comment by AlexOn1ine** [comment]
Mentioned on discord but It would be better if someone else reviews the pr.

**Comment by hedara90** [comment]
Just adding my 2Ꝑ to this.
It doesn't really matter for me how the test folders are laid out, because quite often I have to find what I'm looking for by running `grep -nri "MOVE_WHATEVER" test/` and then opening the file I find it in. Because it's not guaranteed that what I'm looking for will be where I'd expect it to be.
If I for example want to test Mud-Slap, should I look in `battle/move_effect_secondary/` since it's a secondary effect? Or should I look in `battle/move_effect/` since it's using `MOVE_EFFECT_ACC_MINUS_1` since it's tested with Sand Attack?
So for me it doesn't really help to sort it into folders, it'll be an additional letter and / I have to type to open the file for editing.

**Comment by AlexOn1ine** [comment]
Please solve conflicts. I' fine merging it. 

Though I think changes like this should be discussed because they are very subjective and workflow should not necessary be an argument.

**Comment by AsparagusEduardo** [comment]
Uh... I found an issue with this change, as all the tests moved seem to disappear from the runner.
I'll close this PR for now as this issue falls a bit out of the intended scope for it.

**Pull request closed without merging**
