### PR TITLE
Implemented Xhyzi's RHH copyright intro (with config)

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Credits to Xhyzi.

https://user-images.githubusercontent.com/2904965/198175189-896e8384-de6c-492f-b9c3-d24f9ef13c96.mp4

The config allows to restore the original copyright screen.

## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Leaving this as a draft for now because I'd like to change "Battle Engine" to "Expansion", but I'm not good with sprites :(

**Comment by Jaizu** [comment]
> Leaving this as a draft for now because I'd like to change "Battle Engine" to "Expansion", but I'm not good with sprites :(

I can -eventually, withbout an estimated ETA- take care of this.

**Comment by AsparagusEduardo** [comment]
> I can -eventually, withbout an estimated ETA- take care of this.

Thank you :)
I solved the conflicts for when you want to test it out :D

**Comment by AsparagusEduardo** [comment]
Ready for review!

image
Thank you @Jaizu for updating the graphics! :D

**Review by DizzyEggg — APPROVED** [review]

**Review by DizzyEggg — CHANGES_REQUESTED** [review]
When RHH_COPYRIGHT_INTRO  is set to FALSE, the original intro doesn't load at all.

**Review by DizzyEggg — APPROVED** [review]
All seems good

**Pull request merged**
