### PR TITLE
Fixed mini_printf on modern

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Uncommenting `NDEBUG` caused issues to compile when building on modern.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by SBird1337** [comment]
This could go to pret, too :O

**Comment by AsparagusEduardo** [comment]
> This could go to pret, too :O

True. Will PR it there instead.

**Comment by AsparagusEduardo** [comment]
Actually, can you do it? ^^;

**Comment by AsparagusEduardo** [comment]
Did it https://github.com/pret/pokeemerald/pull/1938

**Comment by SBird1337** [comment]
was merged to pret and will make its way here with #3468

**Pull request closed without merging**
