### PR TITLE
Variadic IS_BATTLER_OF_TYPE and GetBattlerTypes

### PR DESCRIPTION
**Pull request by mrgriffin**
@AlexOn1ine wanted something like `!IS_BATTLER_ANY_TYPE(gBattlerAttacker, TYPE_ROCK, TYPE_GROUND, TYPE_STEEL)`.

In addition to that I added `GetBattlerTypes` which computes all the types at the same time, to improve the performance of any code which checks multiple types at once, and updated all `GetBattlerType`s to use the new function.

So that downstream code continues to work:
- `GetBattlerType` is implemented in terms of `GetBattlerTypes`.
- `IS_BATTLER_OF_TYPE` is implemented in terms of `IS_BATTLER_ANY_TYPE`.

## Things to note in the release changelog:
- `IS_BATTLER_ANY_TYPE` should be preferred to `IS_BATTLER_OF_TYPE` whenever more than one type is being checked.
- `GetBattlerTypes` should be preferred to `GetBattlerType` whenever more than one type is being checked.

### CODE REVIEW

**Comment by mrgriffin** [comment]
Oh for God's sake, I forgot `agbcc` still exists on `master` :facepalm:

**Comment by mrgriffin** [comment]
Rebased onto `upcoming` at Alex's request. I didn't check for any new `IS_BATTLER_OF_TYPE` to combine.

**Comment by Bassoonian** [comment]
Would you be able to sync with upcoming and check for any potential new candidates? That way we can merge this PR :)

**Comment by mrgriffin** [comment]
Synced. I couldn't find any new occurrences of `IS_BATTLER_OF_TYPE` or `GetBattlerType` which needed updating.

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
