### PR TITLE
[WIP] Add Wonder launcher items

### PR DESCRIPTION
**Pull request by u8-Salem**
Add all Wonder Launcher Items.
Reference: https://bulbapedia.bulbagarden.net/wiki/Wonder_Launcher

### ITEMS
- [x] X Items
    - [x] X Attack 1, 2, 3, 6
    - [x] X Defense 1, 2, 3, 6
    - [x] X SpAttack 1, 2, 3, 6
    - [x] X SpDefense 1, 2, 4, 6
    - [x] X Speed 1, 2, 3, 6
    - [x] X Accuracy 1, 2, 3, 6
    - [x] Dire Hit 1, 2, 3
    - [x] Guard Spec
- [ ] Unique Items
    - [ ] Reset Urge
    - [ ] Ability Urge
    - [ ] Item Urge
    - [ ] Item Drop
- [x] Healing Items
- [x] Unused Healing Items
    - [x] Max Ether
    - [x] Elixir
    - [x] Max Elixir
- [ ] Tests for all Items
## **Showcase**
**Ability Urge**
abilityurge

**Reset Urge**
reseturge

**Item Urge**
itemurge

**Item Drop**
itemdrop
## **Credit**
[**KryptonLion**](https://www.deviantart.com/kryptonlion/art/The-Ultimate-Pokemon-ItemDex-Full-Version-1-0-786663071) for the Sprites and Palettes
## **Discord contact info**
Salem#3258

### CODE REVIEW

**Comment by CallmeEchoo** [comment]
Currently there are a number of things I would want to clarify.

1. Handling of the stat stages. Currently `GetXItemStage` checks for the item ID. a better approach would be to pass that argument via `.secondaryId` or `.holdItemParam`
2. Unique Items such as Ability Urge use `ItemUseInBattle_StatIncrease`. this leads to an incorrect string being displayed when activating the item. should each item get their own `ItemUseInBattle_` function?
3. Ability Urge would need to be tested thouroughly. Serebii mentions abilities it should work with, but those dont include abilities post gen 5.

**Comment by AsparagusEduardo** [comment]
Merge the latest upcoming first, there are conflicts.

**Comment by CallmeEchoo** [comment]
> Merge the latest upcoming first, there are conflicts.

merged

**Comment by AlexOn1ine** [comment]
Salem, do you think you can finish this PR?

**Comment by AsparagusEduardo** [comment]
Superseded by #4474.
Let me know @u8-Salem if you want to retake this.

**Pull request closed without merging**
