### PR TITLE
Fixed potential memory bug that may cause softlock at the beginning of battles.

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
There's a bug that causes softlocks at the beginning of certain battles that so far hasn't been able to be replicated when using the Battle engine alone.
A way of replicating this error is fighting the twins in Route 104 and then the Fisherman:
softlock
However it doesn't seem to be happening when using `modern` to compile

@ultima-soul has pinned down the commit where this started to happen to this one:
https://github.com/DizzyEggg/pokeemerald/commit/ec4c73711ef1889a60f17bd68cca67c4b99cde9d

It may need additional testing.

## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by Pyredrid** [comment]
Unable to reproduce this bug with either all three branches merged or just `battle_engine`.  Unless someone can reproduce this bug with just these branches, we should probably close this for now...

**Review by ExpoSeed — CHANGES_REQUESTED** [review]
2 things:

1. fix conflicts
2. given that this bug was more likely to be an issue with some other branch, i feel this pr should be closed

**Comment by AsparagusEduardo** [comment]
> 2 things:
> 
> 1. fix conflicts
> 2. given that this bug was more likely to be an issue with some other branch, i feel this pr should be closed

I don't see why we can't fix it on our side. That way, people using the branches won't complain to us 👀

**Comment by ExpoSeed** [comment]
well was there even a bug on our side? that's what i'm questioning

**Comment by AsparagusEduardo** [comment]
> well was there even a bug on our side in the first place? that's what i'm questioning
It's posible, as it started happening from Egg's changes in that specific commit.

**Comment by ExpoSeed** [comment]
fixed in #1346 + some other change we have no idea where

**Pull request closed without merging**
