### PR TITLE
Implemented Fling (2/2)

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Complements #1906

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by LOuroboros** [comment]
Also huge thanks to @AsparagusEduardo because they used their programmer magic tricks to get the `flingPower` field set for every item data automagically, which would have taken me at least an entire day otherwise since I don't know a different way than to do it manually myself 🤣

**Comment by AsparagusEduardo** [comment]
> Also huge thanks to @AsparagusEduardo because they used their programmer magic tricks to get the `flingPower` field set for every item data automagically, which would have taken me at least an entire day otherwise since I don't know a different way than to do it manually myself 🤣

Just to be clear, there wasn't a way to do it automatically, so I did it manually 🤣

**Comment by LOuroboros** [comment]
As pointed out by Dat.H A inside the Discord server, the Moon Stone was missing its `flingPower` value. I just fixed it.

If anyone else finds a mistake, let me know.

**Comment by AsparagusEduardo** [comment]
Here's some missing Fling data extracted from BDSP: https://docs.google.com/spreadsheets/d/1m2EEepu3_nhhEu3kHqc6b_0o5Z--Gire7FG-5NibKDw/edit#gid=1476687871

Max Honey: 30
Lure: 30
Super Lure: 30
Max Lure: 30
Dynite Ore: 30

**Comment by LOuroboros** [comment]
> Here's some missing Fling data extracted from BDSP: [docs.google.com/spreadsheets/d/1m2EEepu3_nhhEu3kHqc6b_0o5Z--Gire7FG-5NibKDw/edit#gid=1476687871](https://docs.google.com/spreadsheets/d/1m2EEepu3_nhhEu3kHqc6b_0o5Z--Gire7FG-5NibKDw/edit#gid=1476687871)
> 
> Max Honey: 30 Lure: 30 Super Lure: 30 Max Lure: 30 Dynite Ore: 30

Done :eyes:

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
