### PR TITLE
Fix TryChangeBattleTerrain overwriting gBattlerAttacker and ABILITYEFFECT_ON_TERRAIN

### PR DESCRIPTION
**Pull request by ghoulslash**
Fixes seed sower in doubles and probably other abilities. Also makes `BattleScript_ActivateTerrainAbilities` use gBattlerTarget as an iterator (with savetarget/restoretarget)

Also fix ABILITYEFFECT_ON_TERRAIN setting gBattlerAbility incorrectly

### CODE REVIEW

**Comment by DizzyEggg** [comment]
It would be good to have tests for fixed abilities/moves.

**Comment by DizzyEggg** [comment]
Conflicts

**Comment by DizzyEggg** [comment]
Actually, what was the original issue here? Could you provide steps?

**Comment by ghoulslash** [comment]
> Actually, what was the original issue here? Could you provide steps?

It's been a while (I forgot about this fix) but in doubles if you attack both enemies and the first has seed sower, gBattlerAttacker gets overwritten and your second target becomes your own partner

**Pull request merged**
