### PR TITLE
Clean up battle scripts

### PR DESCRIPTION
**Pull request by Bassoonian**
This PR removes all unreferenced labels (and in a few cases the unused script that foes with it) of the battle and battle animation scripts.

## **Discord contact info**
bassoonian

### CODE REVIEW

**Comment by DizzyEggg** [comment]
All in all this looks fine. 2 question though:
1. Shouldn't it go to upcoming? This isn't a bug fix per se.
2. Some of these I could see being useful when reading the scripts. There's also a (little) chance that an user used these labels for their own move/animation scripts and now they won't compile. Personally I'm fine with deleting them, but would like to hear from someone else.

**Comment by Bassoonian** [comment]
1. Cleanup has traditionally been included in master I believe, but I can retarget it, sure
2. I was considering the same, but figured perhaps in those cases a comment would suffice? As actual labels, they end up in the .map and .sym files, which I assume affects rom size, even if only minimally? If it doesn't matter much at all, I can also just add them all back in and only delete the actually unused ones (which are three or four, if I remember correctly)

**Comment by DizzyEggg** [comment]
> As actual labels, they end up in the .map and .sym files, which I assume affects rom size, even if only minimally?

They don't actually, you can have 5 labels with the same ROM location.

**Comment by Bassoonian** [comment]
Ah, misconception on my end then :) your (singular or plural, you choose haha) call then on whether or not to keep them (as labels or as comments)

**Comment by AlexOn1ine** [comment]
Imo the clean up is good for `battle_scripts_1.s` and makes sense but for animation you are removing reusable pieces. For example you can use the normal Techno Blast animation just by pointing to it. This is usually not the case with battle scripts since they are often tailor-made for a move but can easily apply to anims.

**Comment by DizzyEggg** [comment]
@Bassoonian I agree with Alex here. I think it's fine to remove the labels in `battle_scripts_1.s` and leave the battle anim file as it is now.

**Comment by Bassoonian** [comment]
What about `battle_scripts_2.s`?

**Comment by AlexOn1ine** [comment]
> What about `battle_scripts_2.s`?

same as `battle_scripts_1.s`

**Comment by Bassoonian** [comment]
Done as requested

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
