### PR TITLE
Implement bag_sort branch

### LINKED ISSUE #3917: Implement ghoul's bag sorting branch
### Description

Title, since this is a vanilla thing as of Gen V. Branch in question: https://github.com/ghoulslash/pokeemerald/tree/bag_sort

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Bassoonian**
Implements @ghoulslash's [bag_sort branch](https://github.com/ghoulslash/pokeemerald/tree/bag_sort). As such, do NOT squash when merging.

This is still a draft as not all items have received updated categories. I personally believe we should deprecate `sItemsByType` in favour of an extra field in `gItems`, but wanted some thoughts on that before I start porting everything over.

## Issue(s) that this PR fixes
Fixes #3917 

## **Discord contact info**
bassoonian

### CODE REVIEW

**Comment by Jaizu** [comment]
Items should have a sort id, otherwise they will follow itemid in their categories
image

**Comment by ghoulslash** [comment]
> Implements @ghoulslash's [bag_sort branch](https://github.com/ghoulslash/pokeemerald/tree/bag_sort). As such, do NOT squash when merging.
> 
> This is still a draft as not all items have received updated categories. I personally believe we should deprecate `sItemsByType` in favour of an extra field in `gItems`, but wanted some thoughts on that before I start porting everything over.
> 
> ## Issue(s) that this PR fixes
> Fixes #3917 
> 
> ## **Discord contact info**
> bassoonian
> 

Agree with adding a new item struct field

**Comment by LOuroboros** [comment]
I agree too.

I also think there should be an opt-in config to remember the sorting, because if I'm not misremembering, the bag is reordered when you reload the savefile.

**Comment by pkmnsnfrn** [comment]
@Bassoonian, what exactly is the missing vanilla data?

**Comment by Bassoonian** [comment]
When using bag sorting in vanilla games, the items are ordered in a specific way (per pocket, of course) that does not match item ids. I've been unable to find a complete list (or any list at all, really), so this probably requires a SV save with maxed out items to depart from and then maxed out items saves for other games to fill in the gaps of items unavailable in SV

**Comment by AlexOn1ine** [comment]
What actually happens when ppl have the better bag branch?

**Comment by pkmnsnfrn** [comment]
https://www.pokecommunity.com/threads/more-bag-pockets.424360/

I don't think BetterBag supports sorting out of the box.

**Comment by pkmnsnfrn** [comment]
Oh you're asking, what if we implement this sorting and then people merge betterBag? I assume, without looking at any code, that it will sort within the bag pocket using the ID we give it, so it should be fine...?

**Comment by AlexOn1ine** [comment]
> Oh you're asking, what if we implement this sorting and then people merge betterBag? I assume, without looking at any code, that it will sort within the bag pocket using the ID we give it, so it should be fine...?

yeah, that this is what I meant. It would make sense that they are sorted within the bag.

**Comment by pkmnsnfrn** [comment]
Start trying to work on this, and then realized that this task won't be as simple as I thought. Then Bulbapedia saved the day. Each page notes how "sort" or "index" works for that game.

The page isn't done for SV yet. I spent the better part of the evening getting SV working on my PC, and I'm certain _somebody_ around here has already emulated SV on their machines...

* [BW](<https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_pocket_(Black_and_White)>)
* [BW2](<https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_pocket_(Black_2_and_White_2)>)
* [XY](<https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_pocket_(X_and_Y)>)
* [ORAS](<https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_pocket_(Omega_Ruby_and_Alpha_Sapphire)>)
* [USUM](<https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_pocket_(Sun,_Moon,_Ultra_Sun,_and_Ultra_Moon)>)
* [LGPE](<https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_pocket_(Let%27s_Go,_Pikachu!_and_Let%27s_Go,_Eevee!)>)
* [SwSh](<https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_pocket_(Sword_and_Shield)>)
* [BDSP](<https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_pocket_(Brilliant_Diamond_and_Shining_Pearl)>)

**Comment by Bassoonian** [comment]
Oh, I never found these. They're perfect. I'll start working on implementing the order from SwSh and then we can adjust as necessary. Thanks!

**Comment by Bassoonian** [comment]
I won't be working on this anytime soon, so closing it for now. Others are free to take over if they feel like it

**Pull request closed without merging**
