### PR TITLE
Set otGender + Moves in FillPartnerParty

### LINKED ISSUE #3158: TRAINER_CUSTOM_PARTNER is always male
### Description

MON_DATA_OT_GENDER is not set in FillPartnerParty in the case of custom partners. This defaults to a male OT, which may be undesired behaviour if someone would like a multi battle with a female Trainer.

### Version

upcoming (Edge)

### Upcoming Version

_No response_

### Discord contact info

bassoonian

### PR DESCRIPTION
**Pull request by AlexOn1ine**
## Description

Fixes `MON_DATA_OT_GENDER` not being set in `FillPartnerParty` (Credit to Crater for the suggestion)
Also `CustomTrainerPartyAssignMoves` was still missing in `FillPartnerParty` for `F_TRAINER_PARTY_EVERYTHING_CUSTOMIZED`
## Images
pokeemerald-25
pokeemerald-24

## Issue(s) that this PR fixes

Fixes #3158

### CODE REVIEW

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
Looks good, just needs to extend the existing Test to check for it.

**Comment by AlexOn1ine** [comment]
> Looks good, just needs to extend the existing Test to check for it.

I don't know how I could test it because it is limited to multi battles.

**Comment by AsparagusEduardo** [comment]
> > Looks good, just needs to extend the existing Test to check for it.
> 
> I don't know how I could test it because it is limited to multi battles.

It's about the party generation, isn't it? 
Look for `TEST("CreateNPC` and you should find an existing test to extend

**Comment by AlexOn1ine** [comment]
> > > Looks good, just needs to extend the existing Test to check for it.
> > 
> > 
> > I don't know how I could test it because it is limited to multi battles.
> 
> It's about the party generation, isn't it? Look for `TEST("CreateNPC` and you should find an existing test to extend

Yes but there no test for `FillPartnerParty`. I tried to make one when I included `F_TRAINER_PARTY_EVERYTHING_CUSTOMIZED` in this function but it was a pain to set up so SBird said that it is fine without.

I could include the gender check in `CreateNPCTrainerPartyFromTrainer` so I could test it but it doesn't seem necessary there.

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
