### PR TITLE
Improved Guillotine Bigram Handling

### LINKED ISSUE #4153: One-hit KO gets guillotine'd
### Description

`One-hit KO` gets decapitalised to `One-hit Ko` at the moment. I'm sure there's other places where Guillotine is doing unintended work (move descriptions, Pokédex entries...) that we ought to check and fix.

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by aarant**
*Changelog 1.9.0 reminder: add 3949 and 4206 to the changelog as well. -AsparagusEduardo*

Changed the way that the `guillotine` feature handles bigrams, based on my ideas and mgriffin's. 

Fixes #4153 

## Description
Now, instead of hardcoded exceptions, any sequence of two capital letters separated by whitespace, digits, ctrl chars or a forward slash will *not* be decapped. (This treats the beginning and end of strings as whitespace for this purpose).

This works by using one more character of lookbehind/lookahead

## Images
romhack-465

## Issue(s) that this PR fixes
Fixes #4153 

## **Discord contact info**
merrp

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
I gave this a whirl and I was trying to find a case with "OK", but by pure chance I got this one:
image
I think it is important that we are able to define what bisects are kept capitalized instead of having all of them non-decapped.

**Comment by mrgriffin** [comment]
Jaizu found https://github.com/aarant/pokeemerald/issues/24. Repeating an idea I had on Discord here, so it doesn't get lost:

Maybe lowercase letters\* should allow bigram detection to apply. So, `XY ` is a bigram, and `XYz` is a bigram, but `XYZ` is not. I _think_ this makes sense, if somebody wrote `PCs` then keeping it as `PCs` seems to make sense, but if they wrote `PCS` then it seems like it should decap to `Pcs`.

That said, I wouldn't be surprised if there are some counter-examples, and this idea doesn't work :sweat_smile: 

\* Or maybe just `s`.

**Comment by AsparagusEduardo** [comment]
> That said, I wouldn't be surprised if there are some counter-examples, and this idea doesn't work 😅
> 
> * Or maybe just `s`.

I can already think of one:
"*NOw that's what I call decapitalization!*" :P

Even just *s* would cause issues in other languages, like spanish:
"*Ella NOs mostró como decapitalizar de forma eficiente.*"

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
Here are my notes after using this Regex to find all instances of bigrams and then going going to those places:
`".*(?<!([A-Z]|[0-9]|[a-z]|_))[A-Z]{2}(?!([A-Z]|[0-9]|_))`

- `“`, `”`, `/`, `!`, `?`, `'`,`-` aren't being taken into account for bigram detection.
image image image image image image image image

- Don't look good: MR., MT., SP., SR., JR., IF, GO, TO, IS, UP, BE, BY, OF, WE, OR, DO, IN, AS, TY, ON, ED, AT, AL, SO, AN, AT, OI, HI, YO, UM, OH, US
(+ YA, ME, IT, HE, VE, RE, EH, UH from the above examples)
image image image image image image image image image image image image image image image image image image image image image image image image image image image

- The AM/PM go es into conflict with dialog that uses AM as in "I am"
image
- Unclear: (HT, WT, LV, VS)
image image image image

- Looks good: PC, TM, HM, TV, KO, HP, NO, PP, OK, MC, TY, AI, ID, XL, XS, OT, BP, LR, UV
image image image image image image image image image image image image image image image image image

Other errors:
- Player name decapped in Save menus:
image image image

**Comment by AsparagusEduardo** [comment]
With this, I can see that it'd be better to have a list of bigrams to not decap than to do decap

**Comment by aarant** [comment]
> With this, I can see that it'd be better to have a list of bigrams to not decap than to do decap

should be done now!

**Comment by AsparagusEduardo** [comment]
> * Player name decapped in Save menus:

I think you misinterpreted what I meant with `Player name decapped in Save menus`.
I'm talking about the fact that if you do your name in all-caps, it'll automatically decap it in the main menu and the "would you like to save, even if you purposely set it as all-caps.
image image image image image

I did not mean that decapped versions of the default names should be added.

**Comment by aarant** [comment]
Added some code that should fix player name case not being preserved on the save menu and main menu

**Comment by AsparagusEduardo** [comment]
> Added some code that should fix player name case not being preserved on the save menu and main menu

It's still happening for the trainer card:
image

**Comment by AsparagusEduardo** [comment]
As discussed on the discord, this will be handled via a new implementation.

**Pull request closed without merging**
