### PR TITLE
Pickup Table Refactor

### PR DESCRIPTION
**Pull request by kittenchilly**
## Description
Refactors the Pickup table to be more in line with modern gens.
Also switches to using SWSH pickup table data, since the SV table is the same except for removing repels.

## **Discord contact info**
kittenchilly

### CODE REVIEW

**Comment by LOuroboros** [comment]
I don't think this PR is much of an update as is. At least not an "update to ORAS".

The image you shared from Bulbapedia shows that the modern games have 10 different tables for Pickup that represent different Pokémon level thresholds, which are not really present here.

[DoesntKnowHowToPlay made an implementation for that in their old Pokeruby project](https://github.com/Doesnty/goodruby/commit/e3b45e4bade41497584cd743561ec563eb8e286c).

I think that porting that over to the expansion would be a better way to go about updating Pickup, preferably with a preproc config to toggle between the vanilla and the Gen. 6 functionality.

**Comment by kittenchilly** [comment]
> I don't think this PR is much of an update as is. At least not an "update to ORAS".
> 
> The image you shared from Bulbapedia shows that the modern games have 10 different tables for Pickup that represent different Pokémon level thresholds, which are not really present here.
> 
> [DoesntKnowHowToPlay made an implementation for that in their old Pokeruby project](https://github.com/Doesnty/goodruby/commit/e3b45e4bade41497584cd743561ec563eb8e286c).
> 
> I think that porting that over to the expansion would be a better way to go about updating Pickup, preferably with a preproc config to toggle between the vanilla and the Gen. 6 functionality.

Bulbapedia says Emerald uses the same level thresholds. If we haven't changed it from decomp it should work exactly the same and we only need to change what items it gives.

**Comment by LOuroboros** [comment]
> > I don't think this PR is much of an update as is. At least not an "update to ORAS".
> > The image you shared from Bulbapedia shows that the modern games have 10 different tables for Pickup that represent different Pokémon level thresholds, which are not really present here.
> > [DoesntKnowHowToPlay made an implementation for that in their old Pokeruby project](https://github.com/Doesnty/goodruby/commit/e3b45e4bade41497584cd743561ec563eb8e286c).
> > I think that porting that over to the expansion would be a better way to go about updating Pickup, preferably with a preproc config to toggle between the vanilla and the Gen. 6 functionality.
> 
> Bulbapedia says Emerald uses the same level thresholds. If we haven't changed it from decomp it should work exactly the same and we only need to change what items it gives.

I think I misinterpreted how the data is shown there, sorry, my bad. Carry on :eyes:

**Comment by AsparagusEduardo** [comment]
I would prefer a refactor that makes the tables easier to edit instead of just changing the items.

**Comment by kittenchilly** [comment]
I'm going to set this to a draft since this PR seems to require more than I thought, especially in regards to pickup's in battle effect.

**Comment by kittenchilly** [comment]
Ready to review.

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
