### PR TITLE
Remove metadata in AIF files

### PR DESCRIPTION
**Pull request by SombrAbsol**
I removed the useless metadata in the AIF files.

## Description
I noticed that a number of recent generation Pokémon cries had unnecessary metadata in their respective AIF audio files, so I automatically removed this metadata with foobar2000. It's not a big deal because it's just a few kilobytes less, but at least the repository is a bit cleaner and lighter. It doesn't change anything in the ROM compilation.

### CODE REVIEW

**Comment by pkmnsnfrn** [comment]
My thinking for testing this is:

1. Randomly select 18 cries (10%)
2. Use [this method](https://superuser.com/posts/1758398/revisions) to see if there's a difference
3. If all 18 cries have an empty output, then we merge the PR.

@hedara90 thoughts?

**Comment by hedara90** [comment]
Shouldn't it work to build all sounds with/out this PR and diff the ROM? If anything important was removed with the metadata it should result in a different ROM.
I haven't looked into the specification for the AIF format, so I can't look at the binary data directly.

**Comment by pkmnsnfrn** [comment]
> Shouldn't it work to build all sounds with/out this PR and diff the ROM? If anything important was removed with the metadata it should result in a different ROM. I haven't looked into the specification for the AIF format, so I can't look at the binary data directly.

It worked! `15e78f403221b2a9b2fb59cc3a185427` is the md5sum for both .gba files. Sounds like that's enough for a merge, no?

**Comment by SombrAbsol** [comment]
> My thinking for testing this is:
> 
>     1. Randomly select 18 cries (10%)
> 
>     2. Use [this method](https://superuser.com/posts/1758398/revisions) to see if there's a difference
> 
>     3. If all 18 cries have an empty output, then we merge the PR.
> 
> 
> @hedara90 thoughts?

Can confirm that all 18 outputs are silent!

**Comment by hedara90** [comment]
I read up a bit on the `.aif` format and looked a bit at the files in a hex editor.
Exactly which metadata has been removed?
From what I can see it's mostly removing data after the end of the `SSND`chunk. Some other metadata chunks are still preserved, like `NAME` chunks which I'd also assume are not needed in our case since they're duplicating the filename.
I don't know if the `MARK` and `INST` chunks do anything when compiled into the ROM, but I'd assume that they're helpful for sound editing purposes.

**Comment by SombrAbsol** [comment]
In theory, only the title and track number have been removed. I used foobar2000 to automatically remove the metadata and given the software, I think it only removed the metadata that is not ‘essential’ to the files as such (including the ones I mentioned).
foobar2000_XTs9Zlwd47

**Comment by hedara90** [comment]
Is that before the removal?
I'm still seeing the name in the hex data.
20240729_17h56m49s_grim

**Comment by SombrAbsol** [comment]
Yup, that’s before. But it's odd that foobar2000 didn't remove it...
Anyway, I was able to remove this chunk by converting the `AIF` files to `WAV` and then to `AIF` (taking care to remove the metadata at each step), as they are both lossless formats. I'll be updating my fork shortly.

**Comment by SombrAbsol** [comment]
Done!
I've double-checked the audio differences and the ROMs' MD5 before and after, and there's no difference in either case!

All builded ROMs got `9ed3f0fd33758513c8590c644650236c` as MD5. I guess the ROM didn't build in the same way as @pkmnsnfrn, so I think it would be better to rebuild to see if its MD5 (`15e78f403221b2a9b2fb59cc3a185427`) is also the same as before, just in case.

**Comment by pkmnsnfrn** [comment]
I don't think it matters if our hashes match - if you have a match between expansion without your channges and expansion with your changes, then I think we're good.

@hedara90 knows more about audio than me, so I'll let them pull the trigger on merging, but I _think_ at this stage, we should wait to merge until after 1.9 drops which is in the next day or so.

**Comment by hedara90** [comment]
I wouldn't say that I know a lot about audio, I just like reading file specs and their binary files. And I'd say that the hashes matching is the great decider in this case.
Agree that it can be merged after 1.9.

**Review by pkmnsnfrn — APPROVED** [review]

**Review by pkmnsnfrn — CHANGES_REQUESTED** [review]
@SombrAbsol please update this PR to target `upcoming` instead of `master`.

**Review by pkmnsnfrn — APPROVED** [review]

**Pull request merged**
