### PR TITLE
Added Normal and Terastal Terapagos sprites

### PR DESCRIPTION
**Pull request by hedara90**
## Description

Added 2 frame front sprites for Normal and Terastal form Terapagos with normal and shiny palettes and defined basic animations.
Added back sprites for Normal and Terastal form Terapagos with normal and shiny palettes.

## Images

terapagos

## Feature(s) this PR does NOT handle:

Stellar form Terapagos is not included in this PR.
It either requires implementing Tera Jewels or a way better spriter than I am.
(actually good sprites aren't handled by this PR either)

## **Discord contact info**

hedara

### CODE REVIEW

**Comment by kittenchilly** [comment]
Should target master.

**Comment by hedara90** [comment]
It was targeted to upcoming because Terapagos doesn't work in master.
The normal form isn't sent out, Tera form is sent out in master.

**Review by AlexOn1ine — APPROVED** [review]

**Comment by AsparagusEduardo** [comment]
> It was targeted to upcoming because Terapagos doesn't work in master. The normal form isn't sent out, Tera form is sent out in master.

What the...?

**Comment by hedara90** [comment]
I didn't question it since it worked in upcoming where all the Tera stuff is.

**Comment by kittenchilly** [comment]
> It was targeted to upcoming because Terapagos doesn't work in master. The normal form isn't sent out, Tera form is sent out in master.

It's because Terapagos' form change mechanics required new implementation of the ability Tera Shell, which was added to upcoming since it was a new thing.  That has nothing to do with the sprites.

**Pull request merged**
