### PR TITLE
Gen 6 Sprites/Animations For Species

### PR DESCRIPTION
**Pull request by katykat5099**
## Description
Adds new Sprites and/or Animations for the following:

_Note: GIF's skip frames, so get a better look in game._

- Chespin
Chespin
- Bunnelby
Bunnelby
- Fletchling
Fletchling
- Fletchinder
Fletchinder
- Talonflame
Talonflame
- Flabébé
Flabebe
- Floette
Floette
- **Floette Eternal Form** *
FloetteEternal
- Florges
Florges
- Amaura
Amaura

** Major changes (in **bold**)

## **Discord contact info**
kakarikiki "Katy"

### CODE REVIEW

**Comment by DizzyEggg** [comment]
Could you also provide gifs of the new animations?

**Comment by katykat5099** [comment]
> Could you also provide gifs of the new animations?

Yeah, it will look exactly like #3426

**Comment by AlexOn1ine** [comment]
The sprites look great 😄

I know you said you didn't want to continue work anymore but could you maybe fix Tyrantrum?
The backsprite is somewhat questionable lol
pokeemerald-7
It's fine if you don't want to though.

**Comment by katykat5099** [comment]
> The sprites look great 😄
> 
> I know you said you didn't want to continue work anymore but could you maybe fix Tyrantrum? The backsprite is somewhat questionable lol pokeemerald-7 It's fine if you don't want to though.

I'm mostly just taking a break. In the future!

**Review by AlexOn1ine — APPROVED** [review]

**Comment by AlexOn1ine** [comment]
> > The sprites look great 😄
> > I know you said you didn't want to continue work anymore but could you maybe fix Tyrantrum? The backsprite is somewhat questionable lol pokeemerald-7 It's fine if you don't want to though.
> 
> I'm mostly just taking a break. In the future!

thx

**Pull request merged**
