### PR TITLE
Utility Umbrella

### PR DESCRIPTION
**Pull request by ghoulslash**
Adds utility umbrella hold effect.

### CODE REVIEW

**Comment by BuffelSaft** [comment]
There are conflicts that need resolving. Looking at the changes I think this will be ready to go after some testing.

**Comment by ghoulslash** [comment]
> 
> 
> There are conflicts that need resolving. Looking at the changes I think this will be ready to go after some testing.

conflicts fixed

**Comment by BuffelSaft** [comment]
Tested with and without a held Utility Umbrella and both sides of the field:

Working:
- Solar Beam/Blade charge turn and damage reduction in Sun/Rain
- Dry Skin damage and healing
- Weather Ball's type change
- Hurricane/Thunder's accuracy
- Growth's stat changes
- Chlorophyll/Swift Swim's speed boost
- Solar Power's HP drop and damage boost
- Holder can be frozen in sunlight
- Flower Gift doesn't activate when Sunny Day is used and the Flower Gift mon has an umbrella
- Hydration doesn't heal status in rain if the mon has an umbrella
- Flower Gift's damage boost
- Sun and Rain's damage modifiers

Issues:
- Weather Ball's animation still changes if the holder has an umbrella
- Synthesis' healing is reduced while holding an umbrella in sun (should heal 1/2, but is healing 1/4 instead)
- Leaf Guard still blocks status in sun if the holder has an umbrella; it should do nothing
- Flower Gift/Forecast doesn't activate/deactivate immediately after losing/gaining an umbrella

The last one seems like it'll need some major changes to Flower Gift/Forecast, which need to be redone anyway, so maybe they could be handled separately.

**Comment by ghoulslash** [comment]
1. Weather Ball's animation still changes if the holder has an umbrella
    - Fixed
2. Synthesis healing is reduced while holding an umbrella in sun (should heal 1/2, but is healing 1/4 instead)
    - Fixed
3. Leaf Guard still blocks status in sun if the holder has an umbrella; it should do nothing
    - Fixed by changing `jumpifleafguard` to a `various` cmd with `IsLeafGuardProtected`
4. Flower Gift/Forecast doesn't activate/deactivate immediately after losing/gaining an umbrella
    - I agree that a new PR to fix all of this would make more sense

**ready for re-review**

**Comment by BuffelSaft** [comment]
Toxic is locking up the game if the battler has Leaf Guard in sun and isn't holding an umbrella:
leaf guard
Synthesis and Weather Ball are fixed.

**Comment by ghoulslash** [comment]
> 
> 
> Toxic is locking up the game if the battler has Leaf Guard in sun and isn't holding an umbrella: leaf guard Synthesis and Weather Ball are fixed.

I had a dumb mistake in `VARIOUS_JUMP_IF_LEAF_GUARD_PROTECTED`. Its fixed now so should be working

**Comment by BuffelSaft** [comment]
leaf guard
Freeze is fixed, but Leaf Guard is triggering the attacker's ability pop up instead of the defender's.

**Comment by ghoulslash** [comment]
Fixed leaf guard popup issue. Ready for review
leafguar

**Review by BuffelSaft — APPROVED** [review]

**Pull request merged**
