### PR TITLE
Fixed Wailord icon sprite

### LINKED ISSUE #3077: Wailord's icon wraps around
### Description

mGBA_2sFuHyc4cq

### Version

1.5.0 (Default) 

### Upcoming Version

This also happens in upcoming (c7e8edf19be3a17e86f78c31d966afd83d677620)

### Discord contact info

asparaguseduardo

### PR DESCRIPTION
**Pull request by SubzeroEclipse**
## Description
Moved it one pixel upwards to prevent it from wrapping around.

## Images
wailord

## Issue(s) that this PR fixes
Fixes #3077 

## **Discord contact info**
subzeroeclipse

### CODE REVIEW

**Comment by pkmnsnfrn** [comment]
OH MY GOD i thought this was a bug with my start menu tysm

**Review by AsparagusEduardo — APPROVED** [review]
Good to have the fix, though I think I'll open a separate issue on how icon rendering is handled, since this might be a vanilla bug that never manifested due to their icons never being so big.

**Comment by pkmnsnfrn** [comment]
Just had a thought. Does this undo Jaizu's work on centering? https://github.com/rh-hideout/pokeemerald-expansion/pull/2879

**Comment by AsparagusEduardo** [comment]
> Just had a thought. Does this undo Jaizu's work on centering? #2879

Meets it half-way, Jaizu's PR moved the sprite 2 pixels down, while this PR raises it 1 pixel up.

**Pull request merged**
