### PR TITLE
Some pledge combo fixes

### PR DESCRIPTION
**Pull request by ghoulslash**
Minor pledge combo fixes
- Sea Of Fire damage checks battler is alive
- Reset pledgeMove field at end of turn in case a canceller stops the combo'ed move

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
ghoul could you maybe look into issue #3589 for pledges? Skeli asked me to do an AI damage calc after the first pledge move has been chosen so that the second battler sees the increase in damage but i wasn't able to do it.

**Comment by ghoulslash** [comment]
> ghoul could you maybe look into issue #3589 for pledges? Skeli asked me to do an AI damage calc after the first pledge move has been chosen so that the second battler sees the increase in damage but i wasn't able to do it.

I'm not great with AI logic but can look to see if CFRU has anything on it

**Comment by AlexOn1ine** [comment]
> > ghoul could you maybe look into issue #3589 for pledges? Skeli asked me to do an AI damage calc after the first pledge move has been chosen so that the second battler sees the increase in damage but i wasn't able to do it.
> 
> I'm not great with AI logic but can look to see if CFRU has anything on it

It has less to do with AI logic but more with the way damage calcs are done in the expansion (which is only a problem for pledges). Since the calcs are ran at the start of the turn the second battler will never see a corresponding pledge move as a 150BP if the first battler has chosen one. 

Right now this is purely handled through AI logic (which tbh is enough for me) but it is probably better if the AI sees the correct damage? Though if there is no easy way for it without rewriting stuff I'm not sure how crucial it is. I'm 100% sure GF doesn't even handle it if they couldn't handle Dragon Rage lol

I would say I merge this PR and if you got something a new one can be opened, if not it's also fine.

**Comment by AlexOn1ine** [comment]
> > > ghoul could you maybe look into issue #3589 for pledges? Skeli asked me to do an AI damage calc after the first pledge move has been chosen so that the second battler sees the increase in damage but i wasn't able to do it.
> > 
> > 
> > I'm not great with AI logic but can look to see if CFRU has anything on it
> 
> It has less to do with AI logic but more with the way damage calcs are done in the expansion (which is only a problem for pledges). Since the calcs are ran at the start of the turn the second battler will never see a corresponding pledge move as a 150BP if the first battler has chosen one.
> 
> Right now this is purely handled through AI logic (which tbh is enough for me) but it is probably better if the AI sees the correct damage? Though if there is no easy way for it without rewriting stuff I'm not sure how crucial it is. I'm 100% sure GF doesn't even handle it if they couldn't handle Dragon Rage lol
> 
> I would say I merge this PR and if you got something a new one can be opened, if not it's also fine.

I should mention the during the actual damage everything is fine.

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
