### PR TITLE
Fix some Abilities overwriting gBattlerAttacker, Fix critical moveTarget bug

### PR DESCRIPTION
**Pull request by ghoulslash**
In doubles, if a mon with stamina is hit with a move that targets both mons (e.g. burning jealousy), it will overwrite the attacker so `GetNextTarget` gets confused and subsequent attacks hit itself and allies

Fixes:
- abilities calling BattleScript_TargetAbilityStatRaiseRet
- electromorphosis / wind power

Also fixes a bug in HandleAction_UseMove where the moveTarget is not properly set

### CODE REVIEW

**Review by DizzyEggg — CHANGES_REQUESTED** [review]
1. Solve conflicts
2. The issue still occurs for the Wind Power ability. Tried it with Air Cutter against a mon with Wind Power in a double battle.
3. Stamina seems fixed so that good news

**Comment by ghoulslash** [comment]
> 1. Solve conflicts
> 
>     2. The issue still occurs for the Wind Power ability. Tried it with Air Cutter against a mon with Wind Power in a double battle.
> 
>     3. Stamina seems fixed so that good news

Fixed conflicts. I fixed the string for Wind Power which was displaying the wrong name, but the status and ability pop up were working correctly, so it should be good to go now.

**Review by DizzyEggg — CHANGES_REQUESTED** [review]
The string was fixed, but the original issue still remains. The attackers hits itself and its partner. See attached gif.
WIND POWER

**Comment by AsparagusEduardo** [comment]
Replaced by #3143

**Pull request closed without merging**
