### PR TITLE
Refactor berries

### PR DESCRIPTION
**Pull request by fdeblasio**
## Description
This PR moves berry-related values into gBerries

## **Discord contact info**
Frankfurter0

## To Do:
Figure out why build is failing
Clean up variable names in new migration scripts

### CODE REVIEW

**Comment by Bassoonian** [comment]
Are you aware that changing the Berry2 struct breaks save compatibility? Just making sure you're aware that this will be a dealbreaker for a merge

**Comment by fdeblasio** [comment]
> Are you aware that changing the Berry2 struct breaks save compatibility? Just making sure you're aware that this will be a dealbreaker for a merge

Oops, I wasn't aware. I'm assuming this means this PR (once it's actually done) will have to wait for save migrations to be finished first?

**Comment by Bassoonian** [comment]
Basically, yeah, so considering that won't be a thing for the near feature, I'd personally hold off on spending more time on this :)

**Comment by Bassoonian** [comment]
To be re-opened later once save migrations or 2.0 are a thing

**Pull request closed without merging**
