### PR TITLE
Fixes Stomping Tantrum effect not doubling power in certain situations

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes Stomping Tantrum effect not doubling power in certain situations

### CODE REVIEW

**Comment by PhallenTree** [comment]
Dancer test fails here because in MOVEEND_DANCER there is this check to determine if the original dance move user failed to act:

`if (!(gBattleStruct->lastMoveFailed & gBitTable[gBattlerAttacker]
                    || (!gSpecialStatuses[gBattlerAttacker].dancerUsedMove
                        && gBattleStruct->bouncedMoveIsUsed)))`

Currently it fails since flinching/paralysis immobility didn't add the user to the list of `gBattleStruct->lastMoveFailed`.

Replacing `gBattleStruct->lastMoveFailed & gBitTable[gBattlerAttacker]` with `gMoveResultFlags & (MOVE_RESULT_FAILED | MOVE_RESULT_DOESNT_AFFECT_FOE)` should make the test pass

**Comment by AlexOn1ine** [comment]
> Dancer test fails here because in `MOVEEND_DANCER` there is this check:
> 
> `if (!(gBattleStruct->lastMoveFailed & gBitTable[gBattlerAttacker] || (!gSpecialStatuses[gBattlerAttacker].dancerUsedMove && gBattleStruct->bouncedMoveIsUsed)))`
> 
> Currently it fails since flinching/paralysis immobility didn't add the attacker to the list of `gBattleStruct->lastMoveFailed`.
> 
> Replacing `gBattleStruct->lastMoveFailed & gBitTable[gBattlerAttacker]` with `gMoveResultFlags & (MOVE_RESULT_FAILED | MOVE_RESULT_DOESNT_AFFECT_FOE)` should make the test pass if these MoveResultFlags aren't deleted before `MOVEEND_DANCER`

Thx, that worked.

**Comment by AlexOn1ine** [comment]
eh, I might be wrong. Flinch might not double.

**Comment by AlexOn1ine** [comment]
> eh, I might be wrong. Flinch might not double.

okay, it does.

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
