### PR TITLE
Add many gen 8 move animations

### PR DESCRIPTION
**Pull request by ghoulslash**
Adds many gen 8 move animations from CFRU. Not every single one is tested

Some GIFs:
bitter_malice burning_jealousy
dire_claw psyshield_bash

Gen 8:
- Spirit Break
- False Surrender
- Expanding Force
- Steel Roller
- Scale Shot
- Meteor Beam
- Misty Explosion
- Grassy Glide
- Rising Voltage
- Burning Jealousy
- Lash Out
- Corrosive Gas
- Coaching
- Flip Turn
- Triple Axel
- Scorching Sands
- Jungle Healing
- Wicked Blow
- Surging Stirkes
- Thunder Cage
- Dragon Energy
- Freezing Glare
- Fiery Wrath
- Thunderous Kick
- Glacial Lance
- Eerie Spell
- Dire Claw through Take Heart

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Just so that we're clear, all those moves are Gen 8, there's no Gen 9 moves in that list ^^;

**Comment by AaghatIsLive** [comment]
I was testing out some move effects and found out that shell smash freezes the game.

**Comment by AsparagusEduardo** [comment]
Skeli's right. Whenever we port something from CFRU, we should always keep the credit if possible.

There's been a severe lack of crediting, so let's start with this at least.

**Comment by ghoulslash** [comment]
fixed shell smash, thunder cage, shelter. updated anim credits. ready for review.

**Comment by ghoulslash** [comment]
Fixed conflicts, ready for review

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
