### PR TITLE
Indexes for Type Effectiveness table

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Made the table to be read a little bit easier.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by DizzyEggg** [comment]
I guess we could have some tests for type effectiveness?

**Comment by AsparagusEduardo** [comment]
> I guess we could have some tests for type effectiveness?

I guess so, yeah. We do for other mechanics, like critical hits and such.

**Review by mrgriffin — APPROVED** [review]
Looks good. Do you want to write the tests Egg suggested as part of this PR, or do it in the future?

**Review by ghoulslash — APPROVED** [review]
going to leave tests for a future PR

**Pull request merged**
