### PR TITLE
Fixed glitchy-looking water drops in the game's intro

### LINKED ISSUE #2683: I've fixed/improved a couple of things about the expansion_intro
...But I'm too much of a dummy to put it in a pull request. 🙈

Basically I moved the pret and RHH logos one tile to the right, to fix the horizontal centering.

And then tweaked the "×" symbol in the tileset so it could remain central.

**Original:**
pokeemerald-1

**Mine:**
pokeemerald-3

I've attached the two files I changed, hopefully someone smarter than me can get them merged!

[expansion_intro.zip](https://github.com/rh-hideout/pokeemerald-expansion/files/10726238/expansion_intro.zip)

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Fixes an issue brought up by missiri#4895. The fix was proved by Tustin2121#6219. I'm just PR'ing it on their behalf.

Before:
https://user-images.githubusercontent.com/4485172/218807128-b7badf50-bd42-49ce-bfa4-d9a03e79e9fd.mp4

After:
mGBA_20230214_140739970

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by Jaizu** [comment]
Any reason why the image was made 8px taller? That gray block shouldnt be used anywhere.

**Comment by LOuroboros** [comment]
> Any reason why the image was made 8px taller? That gray block shouldnt be used anywhere.

Dunno, I'm only submitting the PR after you asked me to. You should talk that stuff with @Meejle.

**Comment by SBird1337** [comment]
If it is unused, just remove that line of tiles? :)

**Comment by LOuroboros** [comment]
> If it is unused, just remove that line of tiles? :) I assume it is an artifact of something like tilemap studio

Uh, okay. I'll get to it.

**Comment by LOuroboros** [comment]
Ready for re-review.

**Comment by Jaizu** [comment]
While is an inprovement, the intro is still an un-aligned mess 
image

**Comment by LOuroboros** [comment]
This PR has been repurposed.

Instead of fixing the issues with the logos in the RHH intro, it now only fixes issues with the water drops in the game's own intro.

Any comment above is thus off-topic, but I don't have the privileges to mark them as such.

In any case, it's ready for review.

**Review by Jaizu — APPROVED** [review]

**Pull request merged**
