### PR TITLE
Gen 1-5 Palette Conversion Redemption

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
A re-introduction of #1960.
In addition to the original changes, a new config called `P_HIPPO_GENDER_DIFF_ICONS` will allow users to switch between using custom icons for hippopotas and hippodown and the vanilla behavior, in which it always uses the male icon.

The following palettes were *not* changed, and therefore need to be made into their own issue:

### To be handled separetly
- castform
- spinda
- Unown's shiny palette

## All Shiny Palettes missing replacement except:
-  arcanine
-  bulbasaur
-  charizard
-  combee
-  combeef
-  fearow
-  furret
-  gastrodon
-  gastrodon\east_sea
-  hoothoot
-  houndour
-  ivysaur
-  landorus
-  noctowl
-  pidgeot
-  pidgeotto
-  sandshrew
-  sandslash
-  sawsbuck\winter
-  shuckle
-  sigilyph
-  victreebel
-  wartortle
-  weepinbell

## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by Blackforest92** [comment]
I am pretty sure the personal preference shouldn't be that many, i think it is even below 50.
Abomasnow, Abra, etc. the entire gen 5 pokemon are obviously done. 
What i am remembering right now is : Blastoise, Pidgey and its evo, Nidoqueen, Horsea and its evo, Azumarill, 
You can just click the commit to check whats changed between the colors for example this [Gen4](https://github.com/rh-hideout/pokeemerald-expansion/pull/2318/commits/2ad3c3f6bec5f8f0cf6a908274fe304a73da56dd) commit where you can see Abomasnow, Ambipom, Arceus etc are clearly edited.

Keep note :
(1) We had fix with Scyther sprite before, 
(2) Azurill's emote is edited to be neutral, sorry about this.

**Comment by AsparagusEduardo** [comment]
Changed target to `breaking`, as this can be considered a breaking change.

**Comment by AsparagusEduardo** [comment]
> if it can be added without breaking saves, it's not a breaking change
@ExpoSeed 

Adjusted target to `dev`

**Comment by AsparagusEduardo** [comment]
Added most of the remaining pals by @Jaizu.

**Comment by AsparagusEduardo** [comment]
Ready for review.

**Comment by AsparagusEduardo** [comment]
Solved conflicts

**Comment by AsparagusEduardo** [comment]
Conflict solved.

**Review by ghoulslash — APPROVED** [review]

**Comment by ghoulslash** [comment]
Solve conflicts

**Pull request merged**
