### PR TITLE
Added FONT_SHORT_NARROWER

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Follow up to #4241 
Based of this commit: https://github.com/agsmgmaster64/worldlinkdeluxe-amesame/commit/3bd3589d0f1942b0580482f051b6f27a8dd0f743. Used with permission.

## Images
image

## **People who collaborated with me in this PR**
Full credit to @agsmgmaster64, I mainly removed unrelated features from the commit :)

## Feature(s) this PR does NOT handle:
There's barely any vanilla usage of `FONT_SHORT`, so can't test much.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Draft until I upload agsmgmaster64

**Comment by AsparagusEduardo** [comment]
Ready

**Comment by pkmnsnfrn** [comment]
This looks good from a code perspective but I'm having trouble finding a good way to test this in game. Specifically, I'm trying to find a place in the game where `PrependFontIdToFit` will trigger and use this but all the vanilla UIs only go as far as `FONT_SMALL_NARROW`. If you can show me some places that I can reliably test this, I'm happy to merge.

**Comment by AsparagusEduardo** [comment]
Added debug utility to test fonts:
mGBA_YKVqCLQ2Ae

**Comment by pkmnsnfrn** [comment]
I have not tested this since September but given that the only change was the debug function, I am okay with a merge. 

I have some questions - I don't think ANY of them are blocking, but I just want to make sure I understand.

1. Font debug is a great idea. I imagine it would be very easy to do a follow up PR where people could choose a font and it would test that, right? I'm not saying YOU should / need to do it, but I want to make sure I'm understanding the complexity.
2. Why did you insert line breaks so early into the lines? Or is that the length at which the words fit for the default font?

**Review by pkmnsnfrn — APPROVED** [review]

**Comment by AsparagusEduardo** [comment]
> 1. Font debug is a great idea. I imagine it would be very easy to do a follow up PR where people could choose a font and it would test that, right? I'm not saying YOU should / need to do it, but I want to make sure I'm understanding the complexity.

I actually thought of this at first, but I had no idea if a command already existed to dynamically switch fonts or not (I should've asked, but it was too late at night for me and just wanted to close this, so I went the easy route. If there is one, I could apply it. 

> 2. Why did you insert line breaks so early into the lines? Or is that the length at which the words fit for the default font?

That's exactly it, I used the width of FONT_NORMAL for it. I can ask hedara how to use the auto line breaks for this, and that way we can double its usefulness to also be an example on how users can use it on their projects :)

**Pull request merged**
