### PR TITLE
Organized pokemon graphics by generation

### LINKED ISSUE #2876: Reminder: Organize Pokémon graphics by generations
likely to be proposed as a pret change, like the friendship constant

### PR DESCRIPTION
**Pull request by MartyKen**
Title says it all
Fixes #2876 

Discord
gengalorian

### CODE REVIEW

**Comment by Bassoonian** [comment]
Hi, welcome and thanks for your interest in contributing! As indicated by the PR template, please join our [Discord Server](https://discord.gg/6CzjAG6GZk) to facilitate discussion. :)

**Comment by AlexOn1ine** [comment]
Conflicts

**Comment by MartyKen** [comment]
Added the P_footprints check

**Review by AlexOn1ine — APPROVED** [review]
Thank you and welcome (if I didn't miss something it looks like your first PR).

**Pull request merged**
