### PR TITLE
Update and clean up Battle Debug

### PR DESCRIPTION
**Pull request by kittenchilly**
## Description
The battle debug menu had quite a bit of missing flags in the bitfields you could edit, likely due to it not being updated when new stuff was added. I did that, going through all of them and adding any missing ones (but I didn't add some that just didn't work by flipping the bit).
I also restructured the code a bit, all ListMenuItem lists use enums now, which should make adding new flags easier.

Another thing is making it so the secondary list doesn't cut off early. This for example fixes the issues of the evasiveness stat stage changer noticeably cutting off, and also fixes some issues of longer names cutting off in Upcoming.

## **Discord contact info**
kittenchilly

### CODE REVIEW

**Review by AlexOn1ine — CHANGES_REQUESTED** [review]
You can't status mons anymore inside the debug menu

**Comment by kittenchilly** [comment]
> You can't status mons anymore inside the debug menu

It actually does apply the status but it doesn't update the graphics in the healthbox. I think its always been like that, but I can fix it anyways

**Comment by kittenchilly** [comment]
Oh, I just realized it was because I removed a line saving the status accidentally. Fixed.

**Comment by AlexOn1ine** [comment]
Most of the status3 stuff doesn't seem to work or they work but the behavior is weird. E.g. If you Leech Seed a mon it drains health from itself and gets it back.

**Comment by kittenchilly** [comment]
> Most of the status3 stuff doesn't seem to work or they work but the behavior is weird. E.g. If you Leech Seed a mon it drains health from itself and gets it back.

Can you make a list of stuff that doesn't seem to work at all so I can remove it? Also if something does seem to do something but doesn't seem right, maybe I can try to fix it

**Comment by AlexOn1ine** [comment]
> > Most of the status3 stuff doesn't seem to work or they work but the behavior is weird. E.g. If you Leech Seed a mon it drains health from itself and gets it back.
> 
> Can you make a list of stuff that doesn't seem to work at all so I can remove it? Also if something does seem to do something but doesn't seem right, maybe I can try to fix it

Please remove the following
```
Uproar
Bide
Multiple Turns
Lock Confuse
Wrapped
Infatuation
Transformed
Substitute
Nightmare
Trace
Me First
Telekinesis
Phantom Force
Infinite Confusion
Sky Dropped
Future Attack
```
Everything else is good

**Comment by kittenchilly** [comment]
Finally got around to fixing this

**Comment by AlexOn1ine** [comment]
Can you just remove them from the debug menu?

**Comment by kittenchilly** [comment]
> Can you just remove them from the debug menu?

I did, they don't appear.

**Comment by AlexOn1ine** [comment]
> > Can you just remove them from the debug menu?
> 
> I did, they don't appear.
the code is still there and for most of them it isn't functional

**Comment by kittenchilly** [comment]
> > > Can you just remove them from the debug menu?
> > 
> > 
> > I did, they don't appear.
> 
> the code is still there and for most of them it isn't functional. I don't see a reason to keep the code. We can always add it back when we decide that it makes sense to have it for something.

Ok, done

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
