### PR TITLE
Implemented Ice Face

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Supersedes #1846.
Special thanks to Benício Gonçalves#3454 who provided a base to work with.

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by LOuroboros** [comment]
Merge conflicts solved, ready for a review :eyes:

**Comment by LOuroboros** [comment]
Turning this into a draft until #2473 is merged.

**Comment by LOuroboros** [comment]
Ready for review :eyes:

**Comment by LOuroboros** [comment]
I could get rid of the `BattleScript_TargetFormChangeWithString` and `BattleScript_BattlerFormChangeWithStringEnd3` I added here if I overwrite the `gBattlerAttacker` in the instances where they're called and instead called the already existing `BattleScript_AttackerFormChangeMoveEffect` and `BattleScript_AttackerFormChange`, thus saving on pointless additions to the codebase. Thoughts?

```diff
diff --git a/data/battle_scripts_1.s b/data/battle_scripts_1.s
index de1aa536a..9e2d9acd3 100644
--- a/data/battle_scripts_1.s
+++ b/data/battle_scripts_1.s
@@ -7807,35 +7807,6 @@ BattleScript_TargetFormChange::
 	handleformchange BS_TARGET, 2
 	return
 
-BattleScript_TargetFormChangeWithString::
-	pause 5
-	copybyte gBattlerAbility, gBattlerTarget
-	call BattleScript_AbilityPopUp
-	printstring STRINGID_EMPTYSTRING3
-	waitmessage 1
-	handleformchange BS_TARGET, 0
-	handleformchange BS_TARGET, 1
-	playanimation BS_TARGET, B_ANIM_FORM_CHANGE, NULL
-	waitanimation
-	handleformchange BS_TARGET, 2
-	printstring STRINGID_PKMNTRANSFORMED
-	waitmessage B_WAIT_TIME_LONG
-	return
-
-BattleScript_BattlerFormChangeWithStringEnd3::
-	pause 5
-	call BattleScript_AbilityPopUp
-	printstring STRINGID_EMPTYSTRING3
-	waitmessage 1
-	handleformchange BS_SCRIPTING, 0
-	handleformchange BS_SCRIPTING, 1
-	playanimation BS_SCRIPTING, B_ANIM_FORM_CHANGE, NULL
-	waitanimation
-	handleformchange BS_SCRIPTING, 2
-	printstring STRINGID_PKMNTRANSFORMED
-	waitmessage B_WAIT_TIME_LONG
-	end3
-
 BattleScript_IllusionOff::
 	spriteignore0hp TRUE
 	playanimation BS_TARGET, B_ANIM_ILLUSION_OFF
@@ -8907,7 +8878,10 @@ BattleScript_IceFaceNullsDamage::
 	effectivenesssound
 	hitanimation BS_TARGET
 	waitstate
-	call BattleScript_TargetFormChangeWithString
+	savetarget
+	copybyte gBattlerAttacker, gBattlerTarget
+	call BattleScript_AttackerFormChange
+	restoretarget
 	goto BattleScript_MoveEnd
 
 BattleScript_DazzlingProtected::
diff --git a/src/battle_util.c b/src/battle_util.c
index b9b57f4eb..5dc5db939 100644
--- a/src/battle_util.c
+++ b/src/battle_util.c
@@ -5157,7 +5157,6 @@ u8 AbilityBattleEffects(u8 caseID, u8 battler, u16 ability, u8 special, u16 move
                 gBattleMons[gBattlerTarget].species = SPECIES_EISCUE_NOICE_FACE;
                 if (gBattleMons[gBattlerAttacker].status2 & STATUS2_MULTIPLETURNS)
                     gHitMarker |= HITMARKER_NO_PPDEDUCT;
-                gBattleScripting.battler = gBattlerTarget; // For STRINGID_PKMNTRANSFORMED
                 gBattlescriptCurrInstr = BattleScript_IceFaceNullsDamage;
                 effect = 1;
             }
@@ -6189,7 +6188,8 @@ u8 AbilityBattleEffects(u8 caseID, u8 battler, u16 ability, u8 special, u16 move
             {
                 gBattleStruct->allowedToChangeFormInWeather[gBattlerPartyIndexes[battler]][GetBattlerSide(battler)] = FALSE;
                 gBattleMons[battler].species = SPECIES_EISCUE;
-                BattleScriptPushCursorAndCallback(BattleScript_BattlerFormChangeWithStringEnd3);
+                gBattlerAttacker = battler;
+                BattleScriptPushCursorAndCallback(BattleScript_AttackerFormChangeMoveEffect);
                 effect++;
             }
             break;
```

**Review by ghoulslash — APPROVED** [review]

**Pull request merged**
