### PR TITLE
Adjusted battle elevations for certain species

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Adjusted mon elevations that I found were kinda weird.
- Voltorb
imageimage
- Electrode
imageimage
- Porygon
imageimage

- Unown forms set with same elevation as base form.
imageimageimage 
- Mantine
imageimage
- Porygon2
imageimage
- Pupitar
imageimage
- Swablu
imageimage
- Barboach
imageimage
- Baltoy
imageimage
- Luvdisc
imageimage
- Chingling (looks like it's standing, but raised based on the animation)
ching1ching2
- Bronzor
imageimage
- Finneon
imageimage
- Mantyke
imageimage
- Gliscor (accounted for tail animation)
glis1glis2
- Porygon-Z
poryz1poryz2
- Probopass
imageimage
- Dusknoir
imageimage

## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by TheXaman** [comment]
Swablu backsprite looks like its flying, so I'd argue the front one should be too, the rest of the changes look great

**Comment by AsparagusEduardo** [comment]
> Swablu backsprite looks like its flying, so I'd argue the front one should be too, the rest of the changes look great

Swablu doesn't have its wings extended and its feet hanging like it's flying in his front sprite. Plus, it wouldn't be the first time the front and back sprite have different poses. 

Screenshot_20220105-071957_Chrome

**Comment by AsparagusEduardo** [comment]
Added Gen V and VI adjustments.
- Phione
imageimage
- Manaphy
imageimage
- Munna
imageimage
- Musharna
imageimage
- Reuniclus
imageimage
- Cryogonal
imageimage
- Volcarona
imageimage
- Meloetta
imageimage
- Flabébé
flabebe1flabebe2
- Floette
imageimage
- Honedge
imageimage
- Doublade
imageimage
- Aegislash
imageimageimage
- Spritzee
sprit1sprit2
- Inkay
ink1ink2
- Carbink
imageimage
- Klefki
imageimage
- Phantump
imageimage
- Yveltal
imageimage

**Comment by AsparagusEduardo** [comment]
Added Gen VII
- Ribombee
imageimage
- Wishiwashi
imageimage
- Comfey
imageimage
- Minior forms
imageimage
imageimage
- Bruxish
imageimage
- Dhelmise
imageimage
- Tapu Koko
koko1koko2
- Tapu Lele
imageimage
- Tapu Bulu
imageimage
- Tapu Fini
imageimage
- Cosmog
imageimage
- Cosmoem
imageimage
- Lunala
imageimage
- Nihilego
imageimage
- Kartana
imageimage
- Necrozma + forms
imageimage
imageimage
imageimage
- Poiple
imageimage
- Naganadel
imageimage

**Comment by AsparagusEduardo** [comment]
Added Gen VIII and missing forms
- Corvisquire
imageimage
- Orbeetle
imageimage
- Flapple
imageimage
- Arrokuda
imageimage
- Sizzlipede
imageimage
- Sinistea
imageimage
- Polteageist
imageimage
- Runerigus
imageimage
- Milcery
imageimage
- Frosmoth
imageimage
- Dreepy
imageimage
- Drakloak
imageimage
- Eternatus
imageimage
imageimage
- Regieleki
imageimage
- Regidrago
imageimage
- Calyrex
imageimage
- Mega Aerodactyl
imageimage
- Mega Rayquaza
imageimage
- Alolan Raichu
imageimage
- Alolan Geodude
imageimage
- Galarian Weezing
imageimage
- Galarian Articuno
imageimage
- Castform
imageimage
imageimage
imageimage
- Rotom
imageimage
imageimage
imageimage
imageimage
imageimage
- Meloetta Pirouette
imageimage
- Hoopa Unbound
imageimage

**Comment by AsparagusEduardo** [comment]
Ready for review.

**Review by ghoulslash — APPROVED** [review]

**Pull request merged**
