### PR TITLE
Decapitalization of berries 'names

### PR DESCRIPTION
**Pull request by SubzeroEclipse**
## Description
Quick PR that fixes the names in src/berry.c (the ones that appear by interacting with berry plants).

## **Discord contact info**
SubzeroEclipse#7867

### CODE REVIEW

**Comment by LOuroboros** [comment]
> the ones that appear by interacting with berry plants

Isn't that specifically overworld related? I think it's out of scope for any of the 3 branches, if so.

**Comment by SubzeroEclipse** [comment]
> > the ones that appear by interacting with berry plants
> 
> Isn't that specifically overworld related? I think it's out of scope for any of the 3 branches, if so.

I thought it was OK, since everything else berry related is decapped. But if the other maintainers feel this way, by all means close this PR.

**Comment by AsparagusEduardo** [comment]
> > > the ones that appear by interacting with berry plants
> > 
> > 
> > Isn't that specifically overworld related? I think it's out of scope for any of the 3 branches, if so.
> 
> I thought it was OK, since everything else berry related is decapped. But if the other maintainers feel this way, by all means close this PR.
> 
> Edit: I just found out that those names also control the name on the Berry tag, so it's not related to just the overworld.

Yeah, I don't see how this is out of scope.

**Comment by AsparagusEduardo** [comment]
> > > the ones that appear by interacting with berry plants
> > 
> > 
> > Isn't that specifically overworld related? I think it's out of scope for any of the 3 branches, if so.
> 
> I thought it was OK, since everything else berry related is decapped. But if the other maintainers feel this way, by all means close this PR.
> 
> Edit: I just found out that those names also control the name on the Berry tag, so it's not related to just the overworld.

Yeah, I don't see how this is out of scope, but you'll need to decap all the names to keep consistency

**Comment by SubzeroEclipse** [comment]
> 
> Yeah, I don't see how this is out of scope, but you'll need to decap all the names to keep consistency

Do you mean the old Berries' names? I didn't decap those because I thought the policy was to keep the vanilla stuff intact (just like in the BE where new battle message are uncapped and the old aren not).

**Comment by MandL27** [comment]
> just like in the BE where new battle message are uncapped and the old aren not

I'm (slowly) working on a PR that addresses this with Ultima's blessing, so those will be decapped and updated to modern gens soon. Asparagus's point on consistency stands either way.

**Comment by SubzeroEclipse** [comment]
Decapped the old Berries' names (and the descriptions). Let me know if I missed something and sorry for the delay.

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
You're missing some `BERRY`s for the descriptions.

Also, you're missing the e-reader Enigma Berry.

**Comment by SubzeroEclipse** [comment]
> You're missing some `BERRY`s for the descriptions.
> 
> Also, you're missing the e-reader Enigma Berry.

Sorry about that. Should be all good to go now.

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
