### PR TITLE
Refactor Egg Moves

### LINKED ISSUE #3653: Egg Moves need a refactor
### Description

See #3562 

### Version

upcoming (Edge)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Bassoonian**
Refactors Egg moves so they're not a giant array with weird offsets anymore but rather structured lists like the teachable learnsets. All functionality is otherwise kept as similar to the original as possible, so this should not cause any real issues with feature branches.

## Issue(s) that this PR fixes
Fixes #3653 

## **Discord contact info**
bassoonian

### CODE REVIEW

**Comment by GraionDilach** [comment]
Why's this PRed from the setteratype branch?

**Comment by Bassoonian** [comment]
> Why's this PRed from the setteratype branch?

Because I suck at git

**Comment by GraionDilach** [comment]
It just makes 0441667 confusing somewhat, so prolly that comment should be rebased out.

On a more relebvant note - should this include setting the basic egg move arrays for the evolved mons wrt #4479?

**Comment by Bassoonian** [comment]
> On a more relevant note - should this include setting the basic egg move arrays for the evolved mons wrt #4479?

Since that discussion is still ongoing and we should limit the scope, I think they should remain separate PRs.

**Comment by AsparagusEduardo** [comment]
> It just makes [0441667](https://github.com/rh-hideout/pokeemerald-expansion/commit/04416671975db42679747e39540206dbcdeb4089) confusing somewhat, so prolly that comment should be rebased out.

Agreed. @Bassoonian, please rebase your changes to the latest upcoming to avoid these stray commits and muddle reviews.

**Comment by Bassoonian** [comment]
Superseded by #4534

**Pull request closed without merging**
