### PR TITLE
Backported upcoming tests

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
- Pressure (2 `KNOWN_FAILING` in master).
- Damage calculation test.
- Fixed `B_MEGA_EVO_TURN_ORDER` assumes.
- Fixed Enimga Berry, Leftovers, Metronome and Safety Goggles assumes.
- Modern fixes.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by DizzyEggg** [comment]
Won't this cause problems when merging master to upcoming?

**Comment by AsparagusEduardo** [comment]
Already tested that and the only conflicts were easily solved :)

**Comment by DizzyEggg** [comment]
Actually, why can't these tests wait for the next release?

**Comment by AsparagusEduardo** [comment]
> Actually, why can't these tests wait for the next release?

Besides tests for new features, I feel it's good to keep tests and the test runner syncronized between the 2 branches. I couldn't quite sync AI and Wild tests because they modify a *lot* to get them running.

**Comment by AsparagusEduardo** [comment]
Force-pushed to remove mistakenly added Opportunist tests

**Comment by DizzyEggg** [comment]
Is it needed actually? Can't we merge upcoming to master 1.7?

**Comment by AsparagusEduardo** [comment]
> Is it needed actually? Can't we merge upcoming to master 1.7?

If that's happening next, then yeah

**Pull request closed without merging**
