### PR TITLE
Fix Shiny Charm

### PR DESCRIPTION
**Pull request by citrusbolt**
Fixes the Shiny Charm so that it doesn't just affect stationaries.  Incidentally fixes the bug mentioned in #2803.

Related: Is it desired to create a set of configs for Synchronize's changes throughout the generations?

Marked as draft as I haven't tested this beyond compilation yet.

### CODE REVIEW

**Comment by mrgriffin** [comment]
Is there some way to unify these implementations rather than have four of them scattered across different functions? I appreciate that they each have subtle differences, but it seems like there must be a better solution than replicating changes to four places whenever we want to change something about shininess.

**Comment by citrusbolt** [comment]
I've pushed my first draft at a centralized PID generation scheme.  Any thoughts would be appreciated.  Does anyone have any desire for Size, Wurmple's evolution, Ability, or any other PID-derived factor to have controls as well?  It may also be worthwhile to apply bitwise math for each of the parameters instead of concentric loops.

**Comment by Bassoonian** [comment]
I think this can be simplified greatly with the advent of #3438, if you'd be interested in tackling it :)

**Comment by citrusbolt** [comment]
If we're settled on a new mon data spec, I'll for sure revisit this 👍

**Comment by Bassoonian** [comment]
Quick bump to check on your plans! :)

**Comment by citrusbolt** [comment]
Rebasing this turned into a huge mess, but I think it's good now.  A squashed merge would be good for this one.

**Comment by mrgriffin** [comment]
@Bassoonian, sorry I never got around to properly reviewing this. I've eyeballed the code and it looks reasonable, but it would be a good idea for somebody to test it in-game, or to write a handful of unit tests for `GeneratePIDMaster`.

**Comment by pkmnsnfrn** [comment]
@mrgriffin @citrusbolt what would a reasonable in-game test look like to you? would it just be triggering 1000+ encounters, counting the shinies, and seeing if the distribution is close to what we would expect?

**Comment by hedara90** [comment]
Quick maths says that ~6k encounters is needed for an ok certainty.
It should be possible to automate it

**Comment by tertu-m** [comment]
Hello, I think the internal consensus is now that we are going to do this in a different way.

**Pull request closed without merging**
