### PR TITLE
Add backwards compatible updated base shiny odds

### LINKED ISSUE #3910: Shiny chance config
### Description

Should be self-explanatory

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by kittenchilly**
## Description
This adds a config P_BASE_SHINY_ODDS. I implemented it in a way that should make it backwards compatible with existing pokemon, as the config is only applied during the CreateBoxMon process.

## Issue(s) that this PR fixes
Fixes #3910 

## **Discord contact info**
kittenchilly

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Interesting...
We need to check what other places use `GET_SHINY_VALUE` and see if they need to be updated as well.

**Comment by kittenchilly** [comment]
> Interesting... We need to check what other places use `GET_SHINY_VALUE` and see if they need to be updated as well.

I checked and all the other places are only in CreateBoxMon, so its fine I believe.

**Comment by Sneed69** [comment]
I would define the `8`s as `GEN_3_SHINY_ODDS` or something similar.

**Comment by tertu-m** [comment]
My concern with this is that it’s backwards compartible with Gen 3, and not whatever SHINY_ODDS was previously. People can and do change that value in their hacks, and presumably if the shiny odds were already higher they would want Pokémon that used to be shiny to remain that way (say somebody was migrating from pre-BoxMon refactor)

**Comment by pkmnsnfrn** [comment]
I think the changelog is a perfectly good place to address this. Should we just edit the PR desc to make sure there's a note for the changelog so it doesn't get missed on generation?

**Comment by pkmnsnfrn** [comment]
Separate question, how do we test that this actually works?

**Comment by AlexOn1ine** [comment]
> Separate question, how do we test that this actually works?

~~We merge it and if some user finds a bug revert it after~~

**Comment by AlexOn1ine** [comment]
> I would define the `8`s as `GEN_3_SHINY_ODDS` or something similar.

@kittenchilly can you do this?

**Comment by kittenchilly** [comment]
> > I would define the `8`s as `GEN_3_SHINY_ODDS` or something similar.
> 
> @kittenchilly can you do this?
> 
> Also can you address [this comment](https://github.com/rh-hideout/pokeemerald-expansion/pull/4667#issuecomment-2249761821) at the top of the description?

Alright, done. Tried to make it clear but it could probably be better

**Comment by AlexOn1ine** [comment]
Hey kitten, the majority of the maintainers aren't fond of this solution so it was decided to close the PR. The following reasons were mentioned 

* Can't verify if it works
* Potentially there is a better solution to this problem 
* Assumes users don't change shiny odds which can be dangerous

**Comment by kittenchilly** [comment]
Fair enough, but I do want to say that it's gonna be hard to verify if any changes to shiny odds work without someone shiny hunting multiple times and checking probability, which obviously would take a long time.

**Pull request closed without merging**
