### PR TITLE
Fix Magic bounce powder moves against grass types

### LINKED ISSUE #2594: Magic Bounced Stun Spore hits grass types
Scenario: Grass type uses Stun Spore on a Pokemon with the Magic Bounce ability. Magic Bounce is triggered and bounces back the Stun Spore to the attacker. The attacker gets paralyzed, even though it's a Grass type and should be immune to powder and spore moves.
MagicBounceStunSpore

I've not tried this with other powder/spore moves.

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #2594 

I used a hack for the AttackCanceller function to recheck the powder case, in case of bouncing back a move. 
Not sure if Powder Move cancellation should be there in the first place(subject to change in the future). For the time being, this should do.

pokeemerald_02

### CODE REVIEW

**Comment by Jaizu** [comment]
Checking Bulbapedia's Stun Spore page, this should be a config for gen >= GEN_6
We should also take the oportunity to make sure that everything is updated under a proper config too:

Generation VI onwards
[Grass-type](https://bulbapedia.bulbagarden.net/wiki/Grass_(type)) and [Electric-type](https://bulbapedia.bulbagarden.net/wiki/Electric_(type)) Pokémon, Pokémon with [Overcoat](https://bulbapedia.bulbagarden.net/wiki/Overcoat_(Ability)), and Pokémon holding the [Safety Goggles](https://bulbapedia.bulbagarden.net/wiki/Safety_Goggles) are now immune to Stun Spore.

**Comment by DizzyEggg** [comment]
> Checking Bulbapedia's Stun Spore page, this should be a config for gen >= GEN_6 We should also take the oportunity to make sure that everything is updated under a proper config too:
> 
> Generation VI onwards [Grass-type](https://bulbapedia.bulbagarden.net/wiki/Grass_(type)) and [Electric-type](https://bulbapedia.bulbagarden.net/wiki/Electric_(type)) Pokémon, Pokémon with [Overcoat](https://bulbapedia.bulbagarden.net/wiki/Overcoat_(Ability)), and Pokémon holding the [Safety Goggles](https://bulbapedia.bulbagarden.net/wiki/Safety_Goggles) are now immune to Stun Spore.

But the config is already there 
https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/battle_util.c#L3732

**Review by AsparagusEduardo — DISMISSED** [review]

**Comment by DizzyEggg** [comment]
Added testcases for Magic Bounce ability and powder moves. Ready for review

**Review by mrgriffin — CHANGES_REQUESTED** [review]
The test runner will match `\n`s/`\l`s/`\p`s in `MESSAGE` if you write spaces. I think it's a little bit more readable that way, although maybe opinions vary. e.g.:
```diff
-MESSAGE("Wynaut's Stun Spore was\nbounced back by Foe Espeon's\lMagic Bounce!");
+MESSAGE("Wynaut's Stun Spore was bounced back by Foe Espeon's Magic Bounce!");
```

You don't need the `// 1.` etc comments at the ends of the lines in `test/ability_magic_bounce.c` :)

But this is great! I don't have words for how thrilled I am to see you writing tests :heart:

**Comment by DizzyEggg** [comment]
> The test runner will match `\n`s/`\l`s/`\p`s in `MESSAGE` if you write spaces. I think it's a little bit more readable that way, although maybe opinions vary. e.g.:
> You don't need the `// 1.` etc comments at the ends of the lines in `test/ability_magic_bounce.c` :)
> 
> But this is great! I don't have words for how thrilled I am to see you writing tests ❤️

That's good to know, I'll fix it :D

**Comment by DizzyEggg** [comment]
Done

**Review by mrgriffin — APPROVED** [review]

**Pull request merged**
