### PR TITLE
Pret merge 23-07-25

### PR DESCRIPTION
**Pull request by mrgriffin**
I'll ask Edu for a witty thing to write here :wink:

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Not a witty comment, but please post the checksums before and after to make sure the merge was done without issues :)

**Comment by mrgriffin** [comment]
Will do! There's an intentional change in `src/pokemon_storage_system.c` which will cause a different checksum (the `GetMonData` PR caught a bug), but I can back that out temporarily while I calculate the checksums.

**Comment by AsparagusEduardo** [comment]
No problem, as long as it's documented here, it's fine by me :)

**Comment by mrgriffin** [comment]
Pre-merge:
49265b89021b06da4a1034ff5db8e7ef696c84eb  pokeemerald.gba

Post-merge:
43ff448890ff0846bc8c7bbb5ca86ec9dd483038  pokeemerald.gba

Post-intentional-change:
8a3b524738eda4cb971b5daac332913dd9df09e9  pokeemerald.gba

I believe the difference between pre-merge and post-merge is that agbcc has generated a) additional veneers, and b) the veneers in slightly different places. I think this doesn't come up on pret because their ROM is small enough that `bl` can be used directly. I'm not sure why agbcc would generate a veneer per alias, but c'est la vie.

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
