### PR TITLE
Fixes form change when using switch moves 

### LINKED ISSUE #3461: FORM_CHANGE_BATTLE_SWITCH doesn't trigger when using U-Turn/Volt Switch/Flip Turn
### Description

Found by @PCG06

zeronohero

### Version

1.6.1 (Default)

### Upcoming Version

_No response_

### Discord contact info

AsparagusEduardo

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #3461

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/4569d913-d46a-4c20-9a8c-9ff62d1c3e16

### CODE REVIEW

**Comment by mrgriffin** [comment]
Nice! Is it possible to write a test for this?

**Comment by AlexOn1ine** [comment]
> Nice! Is it possible to write a test for this?

Is there a way to check party values?

**Comment by mrgriffin** [comment]
> > Nice! Is it possible to write a test for this?
> 
> Is there a way to check party values?

I think `gPlayerParty` would work. So like `EXPECT_EQ(GetMonData(&gPlayerParty[2], MON_DATA_SPECIES), SPECIES_CHERRIM_OVERCAST);` maybe?

**Comment by AlexOn1ine** [comment]
> > > Nice! Is it possible to write a test for this?
> > 
> > 
> > Is there a way to check party values?
> 
> I think `gPlayerParty` would work. So like `EXPECT_EQ(GetMonData(&gPlayerParty[2], MON_DATA_SPECIES), SPECIES_CHERRIM_OVERCAST);` maybe?

I see, will try that.

**Comment by AlexOn1ine** [comment]
Tests added.

**Review by mrgriffin — APPROVED** [review]

**Comment by AsparagusEduardo** [comment]
Reminder to add other tests for other form-changing abilities like Hunger Switch.

**Pull request merged**
