### PR TITLE
Pokemon sprite review pt.1

### LINKED ISSUE #2589: Some Pokémon sprites got wrong and unofficial palettes
image

### PR DESCRIPTION
**Pull request by CyanSMP64**
## Description

As the professional Pokemon sprite critic I am, I've decided to start thoroughly reviewing the Pokemon front and back sprites currently in the expansion, suggest changes to the sprites and their animations, and convert the colour palettes (normal and shiny) to official ones.

In the process of converting palettes, the background colours have been set accordingly:
* Prefer green (#98D0A0) by default
* If a colour in the palette appears green or has a green hue, use blue (#98A0D0) instead so as it doesn't get mistaken for another colour
* If both green and blue are present, prefer red (#D098A0)
* As a final resort in the case that they all are present, try beige (#D0D0A0) or manually adjusting the hue to one that is certainly a non-match. Why not #FF00FF? I chose lighter and desaturated options so they reflect the brightness of an average battle background and don't hurt to look at.

Current progress of this PR: All Pokémon from Bulbasaur (0001) to Slowbro (0080)
All additional notes are on Discord - _pr-discussions > Pokemon sprite review_

## Issue(s) that this PR fixes

Partially fixes #2589.

## **Discord contact info**

cyansixfour

### CODE REVIEW

**Comment by Jaizu** [comment]
It breaks my heart that after editing and fixing so many sprites someone is coming back to make them not use their official palettes for some fucking reason
Like, whats the thinking proccess for something like this?
image

I already took care of making sure it uses the official palette
image
Why are u using personal preference instead using the official palette that sprite uses?

**Comment by AsparagusEduardo** [comment]
> Why are u using personal preference instead using the official palette that sprite uses?

I think it might originate from B2W2's palettes.
HGSS vs BW vs B2W2
Spr_4h_059 Spr_5b_059 Spr_5b2_059

It might be good to discuss which palettes to pull from, since there are multiple official palettes.

**Comment by Jaizu** [comment]
But those colors were made for the BW2 sprite and not the sprite we are using. Afaik we use gen iv sprites since they have proper backsprites as well as second frames for the front sprites.
And even with all of that, if I made plenty of sprites use their official sprite palettes aka the official ones why are we agreeing on throwing all my work away instead finishing fixing the ones left?

**Comment by AsparagusEduardo** [comment]
> But those colors were made for the BW2 sprite and not the sprite we are using.

I agree that if we're using a sprite based on HGSS, it would be better to apply the palette it originally used as well.

> why are we agreeing on throwing all my work away instead finishing fixing the ones left?

We didn't agree on it yet, it's still pending review. Once I would've started looking through the sprites I would've notice the regression on Arcanine's palette and asked about it.

**Comment by gruxor** [comment]
> > but I don't get the logic behind swapping the sprites OR palettes for anything that's gen 1-3 anyways - Emerald already has those
> 
> To stay consistent with future gen sprites.
> 
> > but the default should just be the vanilla sprites
> 
> I disagree. The alternative should be gen3 but we should stay with future gen sprites as default

The issue is that "future gen sprites" right now just seems to mean "whatever whoever the PR feels like making them." Because otherwise, the gen 5 sprite would be the most "future gen" available for Arcanine, but clearly that doesn't settle well with some people. Including myself, because I think that palette looks like absolute shit. Not to mention inconsistencies in style _within the same generation,_ which is widespread.

The only consistent factor is what generation they appeared in. Sprite/palette packs can allow people to pick and choose in the future, but if we want an objective baseline, that's all we have to go on - otherwise we'll be addressing PRs like this one every X months until the end of time.

**Comment by Jaizu** [comment]
Gen V should be avoid because they have no proper second frames and their backsprites are just full body versions.
We should standard to whatever gen IV game we agree, HG/SS was the latest one so that makes more sense to me.
After thats done, we can worry about configs and shit, but if we are randomly making PRs like this where we take sprites from other sprites after someone else fixed the sprites yeah, u are not only throwing my work away but also making things worse instead using the time in fixing the broken ones.
And even after discussing which ones we should be use, that doesnt change that I fixed a lot of sprites and someone is just changing them to whatever personal preference they want, which is super annoying and dumb, I don't care if u claim yourself as a "professional Pokemon sprite critic".

**Comment by gruxor** [comment]
> Gen V should be avoid because they have no proper second frames and their backsprites are just full body versions.
We should standard to whatever gen IV game we agree, HG/SS was the latest one so that makes more sense to me.

This is no less opinionated than the PR in question. I think a lot of the HG/SS sprites look like ass, even if they're usually better than the Gen 5 ones. You can argue the animation/backsprite thing, but in the same sense gen 4 sprites are _also_ incompatible due to different sizes, so there's still no baseline there. If anything, they'll end up looking worse because they were designed with a larger space in mind and anything that's downscaled will be either fan-made or some form of nearest-neighbor downscaling, both of which suffer in quality.

The only thing that you're saying is "my opinionated sprite PR was already merged, so mine should be the definitive one because I did it first" which doesn't really make much sense.

**Comment by Jaizu** [comment]
I don't think you are making much sense now so this will be my last message in this issue, after this I will turn off the notifications for this.
I proposed gen IV and gave a non personal opinion, I never said which ones I like more or dislike the most. I did my work to make sure that the current sprites were fixed and didnt have shit colors and had the official ones instead.
The differences between you and me are pretty clear mate.

- I actually did work to make sure the expansion got better using the official palettes without taking my personal opinions into account.
- I don't try to push my personal preference of sprites into anyone just because I think that some "look like ass".

I'm sorry but I can't only see you as someone that likes arguing based on personal preference for certain sprites and at the same time not doing shit to try to improve the expansion or the current sprites and rather bitch about what you personally like the most. So yeah, good luck trying to improve things and making thinks better thinking that way.

**Comment by gruxor** [comment]
...Considering this isn't even my PR, I don't think you read very carefully. Didn't you also ragequit the expansion a while back anyways? Kinda confused why you're showing up, skimming through without even checking who's posting what, and whining about changes that won't affect you because you (apparently) don't use the expansion anymore. 

Moreover, I wasn't talking about my personal preference at all - I said I have a personal preference, but that it shouldn't be a factor in what exists inside the expansion - which is why I suggested that generation was the only objective deciding factor. Anything else is up for opinion, because Game Freak isn't even consistent inside the same generation.

You:
> I proposed gen IV and gave a non personal opinion

Also you:
> were fixed and didnt have shit colors

🤷‍♂️

**Comment by MandL27** [comment]
Looks Good To Me:tm:

**Review by MandL27 — APPROVED** [review]

**Pull request merged**
