### PR TITLE
Halloween Pret merge

### PR DESCRIPTION
**Pull request by Bassoonian**
Merge without conflicts!

Hash before: `b7a687f50eee171ab33c58c0764b8d4950e5daa1298db4201f8216338c8328b2`
Hash after: `81fc86838208dbf2215529c9f904828f10af64c9b07816d0f843c90b1d664aaf`

## **Discord contact info**
bassoonian

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
If the hash changes, you need to document why. There may not be conflicts, but something might break if you don't know why it changed.

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
If the hash changes, you need to document why. There may not be conflicts, but something might break if you don't know why it changed.

**Comment by Bassoonian** [comment]
> If the hash changes, you need to document why. There may not be conflicts, but something might break if you don't know why it changed.

There was a bugfix in the battle factory, I assume that's why

**Comment by AsparagusEduardo** [comment]
> It was more than that. 

My bad, I assumed that you had this PR https://github.com/pret/pokeemerald/pull/1935.

Still, there shouldn't be assumptions, gotta confirm by reverting the changes to see if it matches.

**Pull request closed without merging**
