### PR TITLE
Fixed Overdrive's animation

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Addresses #1473.

Before -> After.
BeforeAfter

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by ghoulslash** [comment]
while you're fixing this animation, you should convert `launchtemplate` to `createsprite` and add commas between command arguments. I've found that something the lack of commas can cause bugs to occur, and `createsprite` is the pret command, whereas `launchtemplate` is from the mass animation port from the cfru

**Comment by LOuroboros** [comment]
> 
> 
> while you're fixing this animation, you should convert `launchtemplate` to `createsprite` and add commas between command arguments. I've found that something the lack of commas can cause bugs to occur, and `createsprite` is the pret command, whereas `launchtemplate` is from the mass animation port from the cfru

The thing is though, a huge number of animations use `launchtemplate`. Instead of changing the instances of it to use `createsprite` for this single animation, wouldn't it be better if someone worked on a PR to deal with it in one fell swoop? :eyes:

I'm fine either way though, so I'll get to it and wait for a response before pushing.

**Comment by ultima-soul** [comment]
> > while you're fixing this animation, you should convert `launchtemplate` to `createsprite` and add commas between command arguments. I've found that something the lack of commas can cause bugs to occur, and `createsprite` is the pret command, whereas `launchtemplate` is from the mass animation port from the cfru
> 
> The thing is though, a huge number of animations use `launchtemplate`. Instead of changing the instances of it to use `createsprite` for this single animation, wouldn't it be better if someone worked on a PR to deal with it in one fell swoop? 👀
> 
> I'm fine either way though, so I'll get to it and wait for a response before pushing.

Probably a todo is to convert everything to pret macros. Macros from CFRU were just used to make it easily portable at the time probably.

**Comment by ghoulslash** [comment]
> 
> 
> > while you're fixing this animation, you should convert `launchtemplate` to `createsprite` and add commas between command arguments. I've found that something the lack of commas can cause bugs to occur, and `createsprite` is the pret command, whereas `launchtemplate` is from the mass animation port from the cfru
> 
> The thing is though, a huge number of animations use `launchtemplate`. Instead of changing the instances of it to use `createsprite` for this single animation, wouldn't it be better if someone worked on a PR to deal with it in one fell swoop? 👀
> 
> I'm fine either way though, so I'll get to it and wait for a response before pushing.

That should definitely be done, but it's a pretty hefty task that I wouldn't wish on anybody haha. I think just overdrive is okay for this PR

**Comment by LOuroboros** [comment]
Ready for review :eyes:

**Review by DizzyEggg — APPROVED** [review]

**Pull request merged**
