### PR TITLE
Fixes tests rng

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Credit to MGriffin

### CODE REVIEW

**Review by mrgriffin — DISMISSED** [review]
That `indexSum[8]` one is very embarrassing :sweat_smile:

**Comment by mrgriffin** [comment]
Sent you a PR @AlexOn1ine with something that seems to fix the problem locally. Although I'm not convinced it's a proper fix, we might see this crop up again later :/

**Comment by AlexOn1ine** [comment]
> [Sent you a PR](https://github.com/AlexOn1ine/pokeemerald-expansion-1/pull/1) @AlexOn1ine with something that seems to fix the problem locally. Although I'm not convinced it's a proper fix, we might see this crop up again later :/

This should be good to go then

**Review by mrgriffin — APPROVED** [review]

**Comment by AsparagusEduardo** [comment]
Did you guys test at different thread amounts?

**Comment by AlexOn1ine** [comment]
> Did you guys test at different thread amounts?

I tested 2 and 4.

**Comment by mrgriffin** [comment]
Passes for 1 and 8 too.

**Comment by AsparagusEduardo** [comment]
Awesome :)

**Pull request merged**
