### PR TITLE
Various tweaks related to Pokémon cries

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
-Replaced every Gen. 1 to 5 cry with copies ripped from Pokémon White 2
-Made every Gen. 1 to 5 species use the `cry` and `cry2` macros in `sound/cry_tables.inc`, instead of `cry_not` and `cry2_not`
-Modified the makefile so it won't apply the `--compress` flag to files whose name begins in `uncomp_` *(previously affected files starting with `cry_not_` instead)*
-Modified the `cry_not` and `cry2_not` macros because those names are terrible. Now they're called `cry_uncomp` and `cry2_uncomp`, as in "uncompressed".

**Note**: Certain cries currently contain ugly noises. This will be fixed on the next merge with upstream, assuming that Luckytyphlosion's fixes for aif2pcm is accepted in time.

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by LOuroboros** [comment]
It's worth noting that this PR fixed #1337, and if we're willing to use uncompressed cries for Gen. 1 to 5 species selectively, it could solve #1265 too.

**Comment by LOuroboros** [comment]
Ever since I originally submitted this PR I wasn't happy with the titles and/or descriptions of the first couple of commits, so I used the power of `git cherry-pick` to address it since it hasn't been reviewed by anyone yet.

With that being said, this is ready for review.

**Review by ultima-soul — CHANGES_REQUESTED** [review]
Maybe we should wait for the update to aif2pcm to be merged upstream before merging this since the cries definitely sound crackly without the bugfix.

**Comment by amiosi** [comment]
extra crustle cry included, only needs crustle.aif, uncomp_crustle.aif can be removed

**Comment by ultima-soul** [comment]
This PR is no longer on hold as the sync PR has been merged.

**Comment by LOuroboros** [comment]
Ready for another review :eyes:

**Review by ultima-soul — APPROVED** [review]

**Review by ExpoSeed — APPROVED** [review]

**Pull request merged**
