### PR TITLE
A selection of animation frames

### PR DESCRIPTION
**Pull request by Tacobell24**
Added animation frames for some of the Gen VII and VIII 'mons that were missing them.
Will do some more in future but hopefully these are useful.

The Salandit that was in there originally was a little subpar too, so I made an entirely new frame sheet from scratch.
anim_front

Also updated most of the entries in src\pokemon.c and src\data\pokemon\front_pic_anims.c

The others included are:
* Stufful
* Bewear
* Wimpod
* Golisopod
* Grubbin
* Charjabug - updated back sprite
* Vikavolt
* Dewpider
* Aracquanid
* Applin - yet to finalise front_pic_anims for this line
* Flapple
* Appletun
* Sizzlipede
* Centiskorch
* Rookidee
* Corvisquire
* Covriknight
* Turtonator
* Pyukumuku
* Jangmo-O
* Hakamo-O
* Kommo-O
* Chewtle
* Drednaw
* Pincurhin - slight palette update for electric field of frame 2
* Aloloan Exeggcutor - updated palette to match new sprite
* Minior - new sprites, still need to add individual shiny palettes pointers for cores into src\pokemon.c 
* Salazzle - modified sprite

Enjoy!

**Discord contact info**

Tacobell24#7127

### CODE REVIEW

**Comment by mrgriffin** [comment]
> Rebase and/or give commits meanful names

fwiw, you can choose "Squash and merge" if you think that a PR should be a single commit, it'll let you write a new commit message for the combined commit.

That said, I don't know of a nice way in the Github UI to combine some of the commits together while keeping some of the others so it depends on the PR whether it's better to ask the author to rebase/etc or for the maintainer to squash. My rule of thumb is to squash if all the commits except the first are things like "address review comments" or "fix bugs" :)

**Comment by Tacobell24** [comment]
> Rebase and/or give commits meanful names

**Comment by Jaizu** [comment]
Don't worry, and thanks for contributing o/

**Comment by AsparagusEduardo** [comment]
> Rebase and/or give commits meanful names

Alternatively, we could've squash it ourselves ^^;

**Comment by Tacobell24** [comment]
> > Rebase and/or give commits meanful names
> 
> Alternatively, we could've squash it ourselves ^^;

Was I an absolute spud and messed something up here?
I see the build failed.
I'm on browser only and can't check what specifically went wrong with the pokemon.c or front_pic_anims file unfortunately

**Comment by AsparagusEduardo** [comment]
> > Rebase and/or give commits meanful names
> 
> fwiw, you can choose "Squash and merge" if you think that a PR should be a single commit, it'll let you write a new commit message for the combined commit.
> 
> That said, I don't know of a nice way in the Github UI to combine some of the commits together while keeping some of the others so it depends on the PR whether it's better to ask the author to rebase/etc or for the maintainer to squash. My rule of thumb is to squash if all the commits except the first are things like "address review comments" or "fix bugs" :)

Your changes to `src/pokemon.c` were made to an old version instead of the most recent one, causing issues.

**Comment by Tacobell24** [comment]
> > > Rebase and/or give commits meanful names
> > 
> > 
> > fwiw, you can choose "Squash and merge" if you think that a PR should be a single commit, it'll let you write a new commit message for the combined commit.
> > That said, I don't know of a nice way in the Github UI to combine some of the commits together while keeping some of the others so it depends on the PR whether it's better to ask the author to rebase/etc or for the maintainer to squash. My rule of thumb is to squash if all the commits except the first are things like "address review comments" or "fix bugs" :)
> 
> Your changes to `src/pokemon.c` were made to an old version instead of the most recent one, causing issues.

Looks like I fixed it 👍... hopefully

**Comment by AsparagusEduardo** [comment]
You also used an old version of `src/data/pokemon_graphics/front_pic_anims.h` which is causing a lot of unnecessary reversions and it's making it difficult to review.
imagen

**Comment by Tacobell24** [comment]
> You also used an old version of `src/data/pokemon_graphics/front_pic_anims.h` which is causing a lot of unnecessary reversions and it's making it difficult to review. imagen

Ulgh. Gosh darn. Sorry about that.
I updated it to the latest one and it appears to have built so fingers crossed. 🤞

**Comment by AsparagusEduardo** [comment]
The 2nd frames aren't being loaded because the references aren't changed in `src/data/graphics/pokemon.h`
mGBA_TKXalLPWpE

If possible, I prefer if the changes are made locally, built, tested and then PR'd, otherwise we go through this back and forth that takes ages to do, plus GitHub's file upload messes up the newline formats.
imagen

If you need help setting up your environment, please join the Discord server: https://discord.gg/6CzjAG6GZk

Otherwise, I can ask someone to implement your changes while crediting you if you want to.

**Comment by AsparagusEduardo** [comment]
Don't beat yourself up, you did a good job for what you could do from GitHub's limited UI :)

It isn't much of a nuisance for me, I was worried that it was a nuisance for you ^^;

The sprites look great btw!

I'd still like if you joined the Discord server to chat :)
You'll be able to take a look at how we develop the expansion and get feedback much quicker :D

**Comment by Tacobell24** [comment]
> I'd still like if you joined the Discord server to chat :) You'll be able to take a look at how we develop the expansion and get feedback much quicker :D

I'm actually alreay in there 👍

**Comment by AsparagusEduardo** [comment]
> I'm actually already in there 👍

Alright, I wasn't sure because you didn't put your Discord tag in the PR description like what the template said you needed to do.

**Comment by Tacobell24** [comment]
> > I'm actually already in there 👍
> 
> Alright, I wasn't sure because you didn't put your Discord tag in the PR description like what the template said you needed to do.

Oh gosh. Fail all round really :/
For posterity's sake I put it there 

**Tacobell24#7127**

**Comment by AsparagusEduardo** [comment]
Superseded by #3090

**Pull request closed without merging**
