### PR TITLE
Fix issues related to double battles with only one player mon

### LINKED ISSUE #2934: Possible issue with double battles and battle strings
image

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #2934

Cause & why this wasn't spotted:
In vanilla, there were usually 2 checks to verify a mon in battle: has more than 0 HP and is not an egg. But it didn't check if the mon was actually a mon, that is its species was not SPECIES_NONE.
The problems with repro stemmed from the above. Sometimes, the non mon data had 0 HP/egg bit set, but sometimes it was just species zeroed out.

I believe these should be all the places where adding the additional check fixes the 2vs1 battles once and for all 🤞

### CODE REVIEW

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
Looks good to me, just needs to rebase to master.

**Comment by DizzyEggg** [comment]
> Looks good to me, just needs to rebase to master.

@AsparagusEduardo Do I have to? Can't we merge to upcoming and then to master? 👀

**Comment by AsparagusEduardo** [comment]
> > Looks good to me, just needs to rebase to master.
> 
> @AsparagusEduardo Do I have to? Can't we merge to upcoming and then to master? 👀

As we stablished, master is for bugfixes, while upcoming is for new features/big refactors.
We would only merge from upcoming to master once it's time for minor versions, like 1.6, which we want to wait until the Save Migration setup is ready.
Speaking of new releases, I'll release 1.5.1 once this fix is on master :)

**Comment by DizzyEggg** [comment]
Alrighty then

**Pull request closed without merging**
