### PR TITLE
Transform updates AI_PARTY data

### PR DESCRIPTION
**Pull request by ghoulslash**
Cmd_transformdataexecution now updates AI_PARTY moves and ability properly, so if the player uses transform the AI has up to date move, ability knowledge

### CODE REVIEW

**Review by DizzyEggg — CHANGES_REQUESTED** [review]
Let's use RecordKnownMove and RecordAbilityBattle

**Comment by ghoulslash** [comment]
> Let's use RecordKnownMove and RecordAbilityBattle

RecordKnownMove won't work correctly because transform will have been recorded already and it looks for the first MOVE_NONE slot

**Comment by DizzyEggg** [comment]
> > Let's use RecordKnownMove and RecordAbilityBattle
> 
> RecordKnownMove won't work correctly because transform will have been recorded already and it looks for the first MOVE_NONE slot

I see, then let's create a new function like RecordAllMoves, so it updates both BATTLE_HISTORY and AI_PARTY. That's why I wanted to have RecordAbilityBattle used as well.

**Comment by ghoulslash** [comment]
> > > Let's use RecordKnownMove and RecordAbilityBattle
> > 
> > 
> > RecordKnownMove won't work correctly because transform will have been recorded already and it looks for the first MOVE_NONE slot
> 
> I see, then let's create a new function like RecordAllMoves, so it updates both BATTLE_HISTORY and AI_PARTY. That's why I wanted to have RecordAbilityBattle used as well.

Just committed RecordAllMoves. battle history doesnt need to be updated since it would have already been updated with the last used move (also, we can probably remove battle history altogether since we have AI_PARTY)

ready for re review

**Review by DizzyEggg — APPROVED** [review]

**Pull request merged**
