### PR TITLE
Implemented a CannotUseItemsInBattle function

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
This PR merges 2 functions, `CannotUseBagBattleItem` and `CannotUsePartyBattleItem`, into 1.
Why?
Because it can be quite misleading for a user to have 2 separate functions to decide whether the Player can use X or Y item in battle, instead of having just 1. I wasted a few hours of life before realizing `CannotUsePartyBattleItem` existed 😂 ...

The PR will remain in Draft Mode for now.
While there are no issues with the existing item effect tests, the function covers a lot of things, some that I don't think the existing tests cover, so I'll *try* to write new ones.
Eventually.
Hopefully.
Through this PR, someone else can take over the work done here in the worst case scenario.

Early reviews would still be appreciated regardless.

## **Discord contact info**
lunos4026

### CODE REVIEW

**Comment by LOuroboros** [comment]
Ready for review now that all the tests that could be written are added, and those that aren't ready at least have a `TO_DO` for someone else to do in the future.

The `EFFECT_ITEM_ESCAPE` tests introduced in #3789 are all `PASS`ing. I didn't include them with a commit of their own because I'm honestly not sure if that could potentially cause troubles during the next upcoming-into-master merge or not.

> [0] Poke Toy lets the player escape from a wild battle: PASS
> [0] Poke Toy lets the player escape from a wild battle even if a move forbid them to: PASS
> [0] Poke Toy lets the player escape from a wild battle even if an ability forbid them to: PASS
> - Tests PASSED:        3
> - Tests TOTAL:         3

> lunos:/mnt/c/Users/Lunos/Home/rhh$ git branch
> * CantReallyUseBattleItemsAtAll
>   upcoming
> lunos:/mnt/c/Users/Lunos/Home/rhh$

**Comment by LOuroboros** [comment]
This is a good time to bring up that I kinda considered adding checks for `mon != NULL` inside `CannotUseItemsInBattle`, more specifically in the `if` statements that assumg that a valid `mon` has been passed through the function when it's called.

I wasn't sure if it was functionally pointless or not so I didn't end up doing it though.

Like, let's take this statement for example:
```c
    // Items that restore HP (Potions, Sitrus Berry, etc.)
    else if (battleUsage == EFFECT_ITEM_RESTORE_HP && (hp == 0 || hp == GetMonData(mon, MON_DATA_MAX_HP)))
    {
        cannotUse = TRUE;
    }
```

Would a change like this be benefitial or matter when it comes to the function's operations?

```diff
```c
    // Items that restore HP (Potions, Sitrus Berry, etc.)
-   else if (battleUsage == EFFECT_ITEM_RESTORE_HP && (hp == 0 || hp == GetMonData(mon, MON_DATA_MAX_HP)))
+   else if (battleUsage == EFFECT_ITEM_RESTORE_HP && mon != NULL && (hp == 0 || hp == GetMonData(mon, MON_DATA_MAX_HP)))
    {
        cannotUse = TRUE;
    }
```
```

**Comment by AlexOn1ine** [comment]
> This is a good time to bring up that I kinda considered adding checks for `mon != NULL` inside `CannotUseItemsInBattle`, more specifically in the `if` statements that assume that a valid `mon` has been passed through the function when it's called instead of `NULL`.

It doesn't seem like it would be needed. 

Also looking at `CannotUseItemsInBattle`. Maybe a `switch` would be better here?

**Comment by LOuroboros** [comment]
> > This is a good time to bring up that I kinda considered adding checks for `mon != NULL` inside `CannotUseItemsInBattle`, more specifically in the `if` statements that assume that a valid `mon` has been passed through the function when it's called instead of `NULL`.
> 
> It doesn't seem like it would be needed.
> 
> Also looking at `CannotUseItemsInBattle`. Maybe a `switch` would be better here? To be fair Idk how beneficial it would be here other then looking better.

"Looking better" is already a good thing imo. A `switch` may certainly improve readability and make it easier for newbies to add their own `battleUsage` related behavior to the function. I'll make the changes and see how it looks :eyes:

**Comment by LOuroboros** [comment]
Ready for re-review :eyes:

**Pull request merged**
