### PR TITLE
[audio] resample oversampled cries to 13379Hz

### PR DESCRIPTION
**Pull request by SBird1337**
Resamples oversampled cries down to 13379Hz. For a complete list look at the files changed. Cries that already used this sample rate or a lower sample rate where not touched.

## Description
This script was used to execute the resample procedure:
```sh
for f in sound/direct_sound_samples/cries/*.aif
do
  base="$(basename -- $f)"
  samplerate="$(soxi $f | awk '/Sample Rate/ { print $4 }')"
  if [ $samplerate -gt 13379 ]
  then
    ffmpeg -i $f -c:a pcm_s8 -ar 13379 /tmp/$base
    mv /tmp/$base $f
  fi
done
```

In total 249 cries were oversampled. When building this locally it saved `2125776` bytes (~2MB) in the final binary.

## **Discord contact info**
karathan

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
So far I've compared the first 60. Will continue tomorrow.

Of those, most I have no notes, except for the following:
- [ ] applin.aif [Maybe raise the volume?](https://www.youtube.com/watch?v=J_aAd-hHFd4)
- [ ] clobbopus.aif [Maybe raise the volume?](https://www.youtube.com/watch?v=90bHIsP6RtI)
- [ ] dwebble.aif, [you can hear the "pebble" part, but not the insect part](https://www.youtube.com/watch?v=FscJZxJlbdo)
- [ ] eternatus_eternamax.aif, [it gets cut before it ends](https://www.youtube.com/watch?v=MaFRin3yeZA)

**Comment by CyanSMP64** [comment]
RE: Eternamax Eternatus
This may be due to the cry code (in sound.c iirc) that fixes the cry length to max 140 frames (roughly the length of Jynx's cry)

**Comment by AsparagusEduardo** [comment]
Feedback for the next 30 cries:
- [ ] frosmoth.aif, [needs volume raise](https://www.youtube.com/watch?v=amCyfo0CS7c&ab_channel=GabbyHicks)
- [ ] glastrier.aif, [needs volume raise](https://www.youtube.com/watch?v=dwqQmjlnSlw&ab_channel=HeroLinik)
- [ ] grookey.aif, [needs volume raise](https://www.youtube.com/watch?v=uvgDMGkJ2sg&ab_channel=Pok%C3%A9monCries)
- [ ] kleavor.aif, [It's a little bit higher pitched than the video](https://www.youtube.com/watch?v=FakZrbl-FGU&ab_channel=ThunderChocolate)

**Comment by AsparagusEduardo** [comment]
Finally came back to finish reviewing this (sorry for the delay)

For the sake of having everything together, I'll put the previous comments here as well:

### Volume Raise
- [ ] applin.aif
- [ ] clobbopus.aif
- [ ] frosmoth.aif
- [ ] glastrier.aif
- [ ] grookey.aif
- [ ] krookodile.aif
- [ ] lycanroc_dusk.aif
- [ ] mega_alakazam.aif
- [ ] mega_blastoise.aif
- [ ] mega_charizard_x.aif
- [ ] mega_charizard_y.aif
- [ ] mega_gyarados.aif
- [ ] mega_kangaskhan.aif
- [ ] mega_mewtwo_x.aif
- [ ] mega_mewtwo_y.aif
- [ ] mega_pinsir.aif
- [ ] mega_venusaur.aif
- [ ] morpeko.aif
- [ ] morpeko_hangry.aif
- [ ] orbeetle.aif
- [ ] overqwil.aif
- [ ] polteageist.aif
- [ ] silicobra.aif
- [ ] sinistea.aif
- [ ] spectrier.aif

### Volume decrease
- [ ] mega_gardevoir.aif

### Pitch adjustment
- [ ] kleavor.aif, [official cry is lower pitch](https://www.youtube.com/watch?v=FakZrbl-FGU&ab_channel=ThunderChocolate)
- [ ] ursaluna.aif, [official cry is lower pitch](https://www.youtube.com/watch?v=qV0sROqRlCM&pp=ygUMdXJzYWx1bmEgY3J5)
- [ ] watchog.aif, [official cry is higher pitch](https://www.youtube.com/watch?v=A1d4oKcGdy8&pp=ygULd2F0Y2hvZyBjcnk%3D)
- [ ] wyrdeer.aif, [official cry is lower pitch](https://www.youtube.com/watch?v=MN1so6Kaqyo&pp=ygULd3lyZGVlciBjcnk%3D)

### Other
- [x] dwebble.aif, ~~[you can hear the "pebble" part, but not the insect part](https://www.youtube.com/watch?v=FscJZxJlbdo)~~ Fixed.
- [x] eternatus_eternamax.aif ~~, [it gets cut before it ends](https://www.youtube.com/watch?v=MaFRin3yeZA)~~. Fixed.
- [ ] noibat.aif, [some of the higher pitch sound seems to be missing](https://www.youtube.com/watch?v=kc9APnUPOlA&pp=ygUKbm9pYmF0IGNyeQ%3D%3D), but not sure what could we do with it.
- [ ] oricorio_pom_pom.aif, [there's some *weird* distortion going on with this one](https://www.youtube.com/watch?v=k4SkN8dR_hM&pp=ygUUb3JpY29yaW8gcG9tIHBvbSBjcnk%3D)
- [ ] uncomp_klefki.aif, I think sounds good enough to rename it to just `klefki.aif`.

**Comment by SBird1337** [comment]
I addressed most of the review comments.

* noibat: I don't think they were missing, they are not that high pitched for it to make sense. If anything we are using a different sample than the video. I increased the volume though, so it is a bit more noticable.
* oricorio_pom_pom: not sure whats going on with this one, sounds like an entirely different sample, not much I can do about that.
* uncomp_klefki: I left it uncompressed, there's still a fair bit of high pitch sounds, so compression might just kill it (it's one of few exceptions, should be ok)

**Comment by AsparagusEduardo** [comment]
Most changes sound good, though I feel there's still 3 things left to adjust:
- Applin doesn't volume doesn't sound much raised from before ^^;
- Take the chance to rename the `mega_xxx` cries to `xxx_mega`.
- For the pitch adjustments they don't sound quite right still, so maybe we could use the ones from [here](https://play.pokemonshowdown.com/audio/cries/).

**Review by AsparagusEduardo — APPROVED** [review]
I'll create an issue to keep track of the missing changes. For now, it should be ready to merge.

**Pull request merged**
