### PR TITLE
Fix Jump Kick recoil not being after Spiky Shield

### LINKED ISSUE #1410: Jump Kick recoil should happen after Spiky Shield damage
Scenario:
Attacker uses Jump Kick, target uses Spiky Shield. 

Current behavior:
Attacker takes recoil damage, then Spiky Shield damage. If the attacker faints from the recoil, Spiky Shield will try to inflict damage on it and this will freeze the game.

Behavior in USUM:
Attacker takes Spiky Shield damage, then recoil damage.

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #1410

With a new test to verify it's working correctly.

### CODE REVIEW

**Comment by mrgriffin** [comment]
Hmm, history looks a little weird with this one. Was this branched from `upcoming` but targeted at `master`?

**Comment by DizzyEggg** [comment]
> Hmm, history looks a little weird with this one. Was this branched from `upcoming` but targeted at `master`?

This is bizzare, it's branched from master. No idea why these commits show up here.

**Comment by AlexOn1ine** [comment]
> This is bizzare, it's branched from master. No idea why these commits show up here.

I think this happened to me once because one PR of mine was merged into the wrong branch.

**Comment by AsparagusEduardo** [comment]
Replaced by #3208

**Pull request closed without merging**
