### PR TITLE
Support for multi battles where Trainer has only one mon

### LINKED ISSUE #2573: Add support for multi battles against a Trainer with a singular Pokémon in their party
```
multi_fixed_2_vs_1(TRAINER_HOPE,LittlerootTown_Text_BirchSomethingToShowYouAtLab,TRAINER_MAY_LILYCOVE_MUDKIP,TRAINER_BACK_PIC_MAY)
```
1MBCiLh 1

Arguably a duplicate of https://github.com/rh-hideout/pokeemerald-expansion/issues/2103

I'm trying to create a battle where the player and a friend are bullying a kid with only one Pokémon. (can also be used for you and a friend versus a super boss with a Level 100 Mewtwo or... something)

The enemy's partner Pokémon should be blank, as is done with `multi_fixed_wild`

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #2573

### CODE REVIEW

**Comment by pkmnsnfrn** [comment]
This fixes the reported bug, but creates a new one where the 2nd Pokemon in an actual double battle is invisible.

CleanShot 2023-02-16 at 09 03 50

**Comment by DizzyEggg** [comment]
@pkmnsnfrn  Nice catch, should be good now

**Comment by pkmnsnfrn** [comment]
VuWJASd 1

Thanks for the fix @DizzyEggg! (and thanks for the ping @Jaizu)

**Comment by Jaizu** [comment]
Imo, when playing multiple pokémon vs the enemy (aka 2vs1), if the enemy only has 1 Pokémon on its party is should have loaded the singles ui for the enemy, as well as the enemy pokémon coordinates (is too moved to the right)

**Comment by AsparagusEduardo** [comment]
> Imo, when playing multiple pokémon vs the enemy (aka 2vs1), if the enemy only has 1 Pokémon on its party is should have loaded the singles ui for the enemy, as well as the enemy pokémon coordinates (is too moved to the right)

I agree. This is already handled on the player's side when the opponent has 2 mon against your 1, so the same should happen on the other side.

**Comment by DizzyEggg** [comment]
@Jaizu  @pkmnsnfrn 
I applied your suggestion

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
