### PR TITLE
Set Disguise to be a Breakable Ability

### PR DESCRIPTION
**Pull request by AgustinGDLV**
Disguise is on the list of ignorable abilities [here](https://bulbapedia.bulbagarden.net/wiki/Ignoring_Abilities#Ignorable_Abilities). This hasn't been raised as an issue as far as I can see, but I noticed it while testing another move.

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
The CI doesn't show it but it seems some tests fail.

**Comment by AlexOn1ine** [comment]
> The CI doesn't show it but it seems some tests fail.

Hm, suddenly CI passed without any input

**Comment by Bassoonian** [comment]
I restar

> > The CI doesn't show it but it seems some tests fail.
> 
> Hm, suddenly CI passed without any input. Agustin, can you direct it to master?

I restarted the CI. Something cancelled it during the test process, so it didn't get to complete it. I agree this should go to master instead, but the PR itself is sound

**Comment by kittenchilly** [comment]
Just want to confirm that I checked with a datamine and Disguise actually has every ability flag set to true, including breakable. So this and the other flags it has should be correct.

**Pull request closed without merging**
