### PR TITLE
Reordered Debug_EventScript_InflictStatus1

### PR DESCRIPTION
**Pull request by damon-murdoch**
## Description
Reordered Debug_EventScript_InflictStatus1 to within the 'DEBUG_OVERWORLD_MENU == TRUE' .if block, as it relies on 'Debug_NoPokemon' which is not defined outside of it.

## Issue(s) that this PR fixes
[Discord Message](https://discord.com/channels/419213663107416084/1077168246555430962/1219230896075309097)

## **People who collaborated with me in this PR**
[MrGriffin, for suggesting the fix](https://discord.com/channels/419213663107416084/1077168246555430962/1219233509567365140)

## **Discord contact info**
sirscrubbington

### CODE REVIEW

**Comment by damon-murdoch** [comment]
After reviewing this again, this is not *quite* right - There are a few other things that need to be moved to within the .if block as well - I will be making another commit to this PR to resolve that issue

**Comment by damon-murdoch** [comment]
Tested and confirmed compiling in both dev and release modes

**Comment by LOuroboros** [comment]
Instead of shuffling around the contents of the file, you should only move `.endif` to the end of the file, imo.

All the scripts inside `data/scripts/debug.inc` *are* meant to be used by the debug menu alone anyway.

**Comment by damon-murdoch** [comment]
That's definitely a simpler solution, but when I tried to compile after doing that I found that one of the scripts in that file is actually a dependency of another file  - I'd have to recompile to get the actual file, I don't remember which one

**Comment by LOuroboros** [comment]
> That's definitely a simpler solution, but when I tried to compile after doing that I found that one of the scripts in that file is actually a dependency of another file - I'd have to recompile to get the actual file, I don't remember which one

Can you elaborate?

I built an up-to-date copy of upcoming from mostlyclean and things work just fine, no errors whatsoever.

wsl_20240318_123752732

**Comment by damon-murdoch** [comment]
I'll revert to the old file and move the .endif to the end real quick and get back to you, I might have misunderstood the error

**Comment by damon-murdoch** [comment]
Tested it again, with `DEBUG_OVERWORLD_MENU` set to `FALSE` and the `.endif` in `debug.inc` moved to the end, I get the following issue:

```
cd build/modern && arm-none-eabi-ld -Map ../../pokeemerald.map -T ld_script.ld -o ../../pokeemerald.elf <objects> <lib>
arm-none-eabi-ld: src/field_specials.o: in function `TrySkyBattle':
:(.text+0x3f3c): undefined reference to `Debug_FlagsAndVarNotSetBattleConfigMessage'
Memory region         Used Size  Region Size  %age Used
           EWRAM:      245734 B       256 KB     93.74%
           IWRAM:       30432 B        32 KB     92.87%
             ROM:    24024652 B        32 MB     71.60%
make: *** [Makefile:490: pokeemerald.elf] Error 1
```

Hopefully that helps - Feel free to ask me anything else, I will have to get back to you tomorrow though as it is 2AM here now lol

**Comment by AsparagusEduardo** [comment]
This should go to master since it's fixing a bug

**Comment by damon-murdoch** [comment]
Sorry for the late response - I am not certain if this bug is also present in master, but from what I've seen there have been discussions for solving this issue another way (by reorganizing the files some scripts are located in).

Please let me know if this PR is still required :)

**Comment by AlexOn1ine** [comment]
Can we decide on what to do with this? Looks like an easy merge once we move the Sky Battle script.

**Comment by AsparagusEduardo** [comment]
> Can we decide on what to do with this? Looks like an easy merge once we move the Sky Battle script.

Sorry, I was away mentally. I'll quickly test the error and fix to see.

**Comment by AlexOn1ine** [comment]
@damon-murdoch do you think you could do the stuff that was discussed on discord?

**Comment by damon-murdoch** [comment]
It's been awhile, I'll have a look at that discord discussion and check it out - From memory, this was a pretty simple change

**Comment by damon-murdoch** [comment]
I was unable to rebase this cleanly, so I've created a new PR which has the required change directly from the master branch: 

https://github.com/rh-hideout/pokeemerald-expansion/pull/4372

**Pull request closed without merging**
