### PR TITLE
Add Doodle + update ability banlists

### LINKED ISSUE #2498: MOVE_DOODLE Effect

### PR DESCRIPTION
**Pull request by kittenchilly**
## Description
Adds the move Doodle, and also updates all the ability banlists for certain moves and neutralizing gas, using data from smogon.

## Issue(s) that this PR fixes
Closes #2498

## **Discord contact info**
kittenchilly

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Can you please write a Parametrized test the checks all the banned abilities for user, partner and target?

```
Doodle will fail if either the target, the user, or the user's ally have any of the following Abilities: 
As One, Battle Bond, Comatose, Commander, Disguise, Gulp Missile, 
Ice Face, Multitype, Power Construct, Protosynthesis, Quark Drive, RKS System, 
Schooling, Shields Down, Stance Change, or Zen Mode. 
```
Also maybe some tests for Role Play? :eyes: 
It's fine either way though.

**Comment by DizzyEggg** [comment]
Conflicts

**Comment by kittenchilly** [comment]
> Conflicts

Resolved

**Comment by Bassoonian** [comment]
Conflicts. Also, can you do the parametrized tests as Alex asked? If not, we can open an issue, but then maybe it'd be helpful if you'd add a to do test as well :)

**Comment by kittenchilly** [comment]
> Conflicts. Also, can you do the parametrized tests as Alex asked? If not, we can open an issue, but then maybe it'd be helpful if you'd add a to do test as well :)

It'd be better if those tests were for role play. I'll make a separate PR for master.

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
