### PR TITLE
Fix battle palace bug

### PR DESCRIPTION
**Pull request by DizzyEggg**
This should hopefully fix the battle palace bug #2396

How did the bug appear?
The way AI moves are set-up and chosen was changed a while ago, but the palace code has not been updated with these changes.

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
It seems that all described issues were fixed, but now there's a new one introduced: Sometimes the AI will attack themselves, no matter if they're in the player's side or the opponent's.

https://user-images.githubusercontent.com/2904965/198881376-593fb4ae-89a0-486b-8f8c-d32884e9db61.mp4

https://user-images.githubusercontent.com/2904965/198881378-c3ed926b-baab-4c60-ae7d-97b477b2bb8d.mp4

**Comment by DizzyEggg** [comment]
Does it happen all the time or only with specific moves / moves with specific target?

**Comment by AsparagusEduardo** [comment]
> Does it happen all the time or only with specific moves / moves with specific target?

It doesn't happen all the time, but so far I've only encountered it with moves that target a single foe.


Here's Mud Shot targeting the user and then the opponent in the next turn:

https://user-images.githubusercontent.com/2904965/198889186-af2187b1-cc2d-4f12-a0f1-461ff618335b.mp4

**Comment by DizzyEggg** [comment]
@AsparagusEduardo  Should be fixed now

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
