### PR TITLE
Refactor Trainer sprites

### PR DESCRIPTION
**Pull request by fdeblasio**
This PR refactors the code involving Trainer sprites in order to make them easier to add in the future

To add a new trainer sprite, first define the new sprite in include/constants/trainers.h
`#define TRAINER_PIC_CUSTOM       95`

Next, add the sprite to graphics/trainers/front_pics and then in src/data/graphics/trainers.h, make a variable for the sprite and the palette

```
const u32 gTrainerFrontPic_Custom[] = INCBIN_U32("graphics/trainers/front_pics/custom.4bpp.lz");
const u32 gTrainerPalette_Custom[] = INCBIN_U32("graphics/trainers/front_pics/custom.gbapal.lz");
```

Finally, in src/data/graphics/trainers.h, add a new TRAINER_SPRITE to gTrainerSprites using the last parts of the variable names for the TRAINER_PIC and front pic/palette variables

`TRAINER_SPRITE(CUSTOM, Custom),`

## **Discord contact info**
Frankfurter

### CODE REVIEW

**Comment by Bassoonian** [comment]
Conflicts

**Comment by AlexOn1ine** [comment]
Could you add a small tutorial in the description on how new trainer sprites can be added?

**Comment by fdeblasio** [comment]
> Could you add a small tutorial in the description on how new trainer sprites can be added?

Done. Let me know if the tutorial can be improved

**Comment by fdeblasio** [comment]
> Conflicts

Conflicts resolved

**Comment by AlexOn1ine** [comment]
> > Could you add a small tutorial in the description on how new trainer sprites can be added?
> 
> Done. Let me know if the tutorial can be improved

No, it's fine. Thank you!

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
