### PR TITLE
Refactor Scale Shot to use Canceller Multihit Moves

### PR DESCRIPTION
**Pull request by AlexOn1ine**
This PR started as a bug fix and turned into a Scale Shot refactor to make use of `CANCELLER_MULTIHIT_MOVES`. The bug was fixed by this change and everything else works as before. 

Test that fails on upcoming/master:
```
SINGLE_BATTLE_TEST("Endure does not prevent multiply hits and stat changes")
```

### CODE REVIEW

**Review by DizzyEggg — DISMISSED** [review]

**Comment by DizzyEggg** [comment]
Since this is a bugfix, shouldn't it go to master? @AsparagusEduardo

**Comment by AsparagusEduardo** [comment]
> Since this is a bugfix, shouldn't it go to master? @AsparagusEduardo

I was asked this before the PR was made and I was told that it was a big refactor, so I said upcoming, but turns out it kinda wasn't ^^;

@AlexOn1ine, please rebase it to master and I'll approve it ASAP

**Comment by AlexOn1ine** [comment]
> I was asked this before the PR was made and I was told that it was a big refactor, so I said upcoming, but turns out it kinda wasn't 
Tbf I said that it was mostly code that was removed :sweat_smile: 

I'll rebase it to to master

**Comment by AsparagusEduardo** [comment]
> Tbf I said that it was mostly code that was removed 😅
> 
> I'll rebase it to to master

Oops, sorry, I might've misread then.
Thank you

**Comment by AlexOn1ine** [comment]
Done.

> Oops, sorry, I might've misread then. Thank you

All good, I think my main problem communicating it was that I didn't know what should be classified as a refactor.

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
