### PR TITLE
Species/form syntax refactor

### PR DESCRIPTION
**Pull request by cfmnephrite**
Revamped the way species and forms are handled in species_info

## Description
Created FORM and SPECIES macros to better represent species with multiple forms. Macro wraps around a species and includes FORMs as arguments; the base form sets fields for all forms, which all forms either inherit or override with their own values.

## Issue(s) that this PR fixes
Removes the need for MISC_INFO macros representing shared data between a species' formsb tidies up other miscellaneous macros as well

## Issue(s) that this PR introduces
To do: setting exception for overwrite flag, reordering fields to match struct order, indent forms to make it clear that they are forms

## **Discord contact info**
Cancer Fairly/thechurchofcage

### CODE REVIEW

**Comment by mrgriffin** [comment]
A note for other reviewers, I can review the particularly hairy macros when we get to the end. It'll probably be possible to simplify them, and I can definitely document/extract the reusable ones.

**Comment by cfmnephrite** [comment]
> A note for other reviewers, I can review the particularly hairy macros when we get to the end. It'll probably be possible to simplify them, and I can definitely document/extract the reusable ones.

Thanks! This is nearly ready, btw, just a few bullshit mons like Florges and Minior left to do.

**Comment by AsparagusEduardo** [comment]
FYI, here's the branch compiling: https://github.com/AsparagusEduardo/pokeemerald/tree/RHH/review/species_refactor_1
I'm thinking we should move `gSpeciesInfo` to a `species_info.c` file, since we don't want to add an exception to the entire `pokemon.c` file.

**Comment by AsparagusEduardo** [comment]
Hmm, I don't like that the field order is lost :/
image

**Comment by cfmnephrite** [comment]
Aftermath of integrating the macros - will be reordered at the end

На пт, 15.12.2023 г., 22:22 ч. AsparagusEduardo ***@***.***>
написа:

**Comment by AsparagusEduardo** [comment]
> Aftermath of integrating the macros - will be reordered at the end

Gotcha, thank you :)

**Comment by mrgriffin** [comment]
Done the cleanup and applied CF's suggested changes from Discord.

I need to think of the best way to make this work with agbcc, but I think that's the last thing to do? :crossed_fingers:

**Comment by mrgriffin** [comment]
I think to get this working on agbcc would end up with a reasonably small diff because the `_MISC_INFO` macros already exist, and that's all we could share between the forms. I'm unfortunately out of time to make that change, but we can hopefully look into whether it's worth it for 1.7.x or 1.8.

**Comment by cfmnephrite** [comment]
> I think to get this working on agbcc would end up with a reasonably small diff because the `_MISC_INFO` macros already exist, and that's all we could share between the forms. I'm unfortunately out of time to make that change, but we can hopefully look into whether it's worth it for 1.7.x or 1.8.

Thanks for your efforts :) I can't seem to get it build any more... Any ideas why?
image

Otherwise, the solution I would propose for now would be wrapping all the shared data in an explicitly SHARED macro, and the rest in another set of brackets. I can reverse a1a0ade1d and group together shared data based on the MISC_INFO macros to do that, and maybe we can merge a day or two late and Edu and the community won't mind...

Would this work as the macro, btw?
```
#define SPECIES(tag, shared_members, ...) \
    [tag] = { \
        __VA_OPT__(DEFINE_FORMS(__VA_ARGS__)) \
        UNPACK members \
        __VA_OPT__(UNPACK FIRST __VA_ARGS__) \
    } \
    RECURSIVELY(R_FOR_EACH_WITH(SPECIES_FORM, (tag, shared_members), __VA_ARGS__))

#define DEFINE_FORMS(non_shared_members, ...) \
    __VA_OPT__( \
        .formSpecies = { .formSpeciesIdTable = (static const u16[]) { \
            tag, \
            RECURSIVELY(R_FOR_EACH(SPECIES_FORM_TAG, __VA_ARGS__)) \
            FORM_SPECIES_END, \
        }}, \
    ) \

#define SHARED(fields) fields    
```

**Comment by mrgriffin** [comment]
> I can't seem to get it build any more... Any ideas why? (EDIT: works without the static keyword)
Oh, that's interesting :thinking: I needed to remove `static` on agbcc too, so I suppose being able to write that must be a very recent GCC change. Should be fine not to have it :)

I'm just on my way to work, so I'll reply to the rest of your message later :)

**Comment by cfmnephrite** [comment]
> ```
> #define SPECIES(tag, shared_members, ...) \
>     [tag] = { \
>         __VA_OPT__(DEFINE_FORMS(__VA_ARGS__)) \
>         UNPACK shared_members \
>         __VA_OPT__(UNPACK FIRST __VA_ARGS__) \
>     } \
>     RECURSIVELY(R_FOR_EACH_WITH(SPECIES_FORM, (tag, shared_members), __VA_ARGS__))
> 
> #define DEFINE_FORMS(non_shared_members, ...) \
>     __VA_OPT__( \
>         .formSpecies = { .formSpeciesIdTable = (static const u16[]) { \
>             tag, \
>             RECURSIVELY(R_FOR_EACH(SPECIES_FORM_TAG, __VA_ARGS__)) \
>             FORM_SPECIES_END, \
>         }}, \
>     ) \
> 
> #define SHARED(fields) (fields)    
> 
> // example:
> SPECIES(SPECIES_VENUSAUR, SHARED(
>    // shared info
> ),
> (
>   // non-shared info
> ),
> MEGA_EVOLUTION(SPECIES_VENUSAUR_MEGA, (
> ...
> )))
> ```

So what do we want to do with this @mrgriffin (@AsparagusEduardo since you're here anyway :P )? If it's worth keeping, it might be better to merge sooner rather than later. If not, and I've just wasted a week of my life... So be it, ig

**Pull request closed without merging**
