### PR TITLE
Removes redundancy in AI_TryToFaint and tweaks to AI_CompareDamagingM…

### LINKED ISSUE #3217: Suggestion: Improve function AI_TryToFaint
### Description

I mentioned it in PR #3199 already but since that PR makes a lot of AI score improvements which cover a variety of edge cases, it might make sense to clean up some redundancy in `AI_TryToFaint`.

### Version

1.5.1 (Default)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
## Description
`AI_TryToFaint` changes: 
- Especially with #3199, some of the score increases aren't needed anymore
- Replaced `AI_STRIKES_FIRST` with `GetWhichBattlerFaster` to ignore the move. If the move is considered the AI might think it's naturally faster when it isn't. The function checks for priority later.
- Rearranged a couple of things to allow the AI to go for a prio move if it sees the target can faint it.

Some minor tweaks to `AI_CompareDamagingMoves`
- Only decrease the score instead of increases and decreases. 
- In the `AI_WhichMoveBetter` section decrease the score only if `1` is returned.

Removed:
- EFFECT_FLAIL
- EFFECT_FACADE
- EFFECT_SMELLINGSALT
- EFFECT_WAKE_UP_SLAP

All 4 are handled by damage calcs. If they get a damage boost the score increases will be handled appropriately. 

And I also removed this small section:
```
    // check high crit
    if (gBattleMoves[move].highCritRatio && effectiveness >= AI_EFFECTIVENESS_x2 && AI_RandLessThan(128))
        score++;
```
Open to suggestions but I don't think the score should be increased randomly even though it is only on super effective.

## Images
Cut was made a 70BP Steel type move and kept the 95% Accuracy. Compared to Smart Strike it each of them get a score decrease:
pokeemerald-34
Both moves kill Typhlosion but a prio move will be chosen:
pokeemerald-32
EQ and Drill Run have a kill with the same number of hits but EQ is more accurate:
pokeemerald-31
Marill knows target can faint it so it prefers Aqua Jet
pokeemerald-25

## Issue(s) that this PR fixes
Fixes #3217

### CODE REVIEW

**Comment by DizzyEggg** [comment]
Could you check now with #3361 merged? Also, if you decide to change something, maybe you could also write a test? 👀

**Comment by DizzyEggg** [comment]
What's the status of this @AlexOn1ine ?

**Comment by AlexOn1ine** [comment]
> What's the status of this @AlexOn1ine ?

Can be closed. A lot of it is already done by you and PR #3382.

**Comment by AlexOn1ine** [comment]
```
EFFECT_FACADE
EFFECT_SMELLINGSALT
EFFECT_WAKE_UP_SLAP
```
Imo those and a couple more can be removed but it's probably better done in a new PR with proper tests.

**Pull request closed without merging**
