### PR TITLE
Battle Item Tests + critical fixes + new test macro

### LINKED ISSUE #2935: Heal Powder is not working
Currently Heal Powder does not work because it has the wrong battleUsage assigned.
`.battleUsage = EFFECT_ITEM_RESTORE_HP,` instead of `.battleUsage = EFFECT_ITEM_CURE_STATUS,`
Does not require any action to be taken. I have it fixed already and will pr soon, just want to see if I can discover more to go into that pr first.

### LINKED ISSUE #2938: Full Restore doesnt heal confusion
Full Restore will currently not heal confusion since the BattleScript uses `curestatus BS_ATTACKER` instead of the new `itemcurestatus`.
No action needs to be taken. I have it already fixed and will be included in the next bugfix pr

### PR DESCRIPTION
**Pull request by CallmeEchoo**
Test for all the Battle items, categorized by their battle effects. 
contributions are welcome. 
Double checking the tests for plausability is also welcomed and probably needed.

**Also add several fixes and new additions in relation to these tests:**
- Introduces a new test macro **MoveWithPP** that allows to specify the starting PP for a move.
Example use: `PLAYER(SPECIES_WOBBUFFET) { MovesWithPP({MOVE_TACKLE, 1}, {MOVE_CONFUSION, 20}); }`
- Includes a [fix](https://github.com/rh-hideout/pokeemerald-expansion/pull/2940/commits/a2809acfd1d6818acb6d39c5d8f1520746201c20) to make sure `gChosenMovePos` is correctly assigned for items that target a move
- Includes critical fixes #2933 and #2939

**#2939 Description:**

> Fixes Heal Powder not using the correct battleUsage
> Fixes Full Restore not using the correct BattleScript command to cure status

**#2933 Description:**

> ```
>      if (ctx.explicitPartyIndex)
>          gBattleStruct->itemPartyIndex[battlerId] = ctx.partyIndex;
>      if (ctx.explicitMove)
>          gBattleStruct->itemPartyIndex[battlerId] = i;
> ```
> These are setting variables that get overwritten with PARTY_SIZE at the start of the turn. &gPlayerParty[6] == &gEnemyParty[0].
> 
> I have replaced them with writing to the battle record in the tests, and reading from it in the battle controllers.
> 
> We should really make the controllers emit the itemPartyIndex rather than writing to it directly. As-is, any recorded battles with an item usage or any link battles with an item usage will go horribly wrong.

## TO-DO
- [x] HP Restoring Items
- [x] Status Curing Items
- [x] HP Restoring and Status Curing Items
- [x] Stat Increasing Items
- [x] Mist Setting Items
- [x] Focus Energy Setting Items
- [x] Reviving Items
- [x] PP Restoring Items
- [x] All Stats Increasing Items (note: dont have their own file. lumped together with stat increasing items)

## **Current Issues**
1. ~~Full Heal curing confusion is broken but not detected in the test (should be fixed with #2939)~~
2. ~~Hyper Potion check passes when it shouldnt -> other hp restoring tests probably not correct aswell.~~
3. ~~Dire Hit test fails when "Wobbuffet vs Wobbuffet" because "Foe Wobbuffet" is displayed. Doesnt happen when "Wobbuffet vs Anything else" [more context on discord](https://discord.com/channels/419213663107416084/1077009799293710357/1099327452511219742)~~
4. Due to missing sanity checks in the replay/test system, the actual revive property of revive items can not be fully tested. the property "fainted" is not checked for which leads to revive items being practically the same as healing items (see discord)(vice versa healing items can "revive" mons).

## **Relevant GIFS**
Dire Hit issue:
direhit direhit2

## Issue(s) that this PR fixes
Fixes #2935 
Fixes #2938 

## **Discord contact info**
Salem#3258

### CODE REVIEW

**Comment by CallmeEchoo** [comment]
Ready for review. Any input on issue 3. would be highly appreciated as I dont have a the time to deep dive on this one rn.

**Comment by mrgriffin** [comment]
> Ready for review. Any input on issue 3. would be highly appreciated as I dont have a the time to deep dive on this one rn.

idk if this is the problem, but:
```c
static const u8 sText_PkmnUsedXToGetPumped[] = _("{B_SCR_ACTIVE_NAME_WITH_PREFIX} used\n{B_LAST_ITEM} to get pumped!");
```

```c
void HandleAction_UseItem(void)
{
    gActiveBattler = gBattlerAttacker = gBattlerByTurnOrder[gCurrentTurnActionNumber];
```

We don't set `gBattleScripting.battler`, so we probably shouldn't expect any consistent behavior. I'm not sure if the fix here is to set that variable, or to create a new string that references e.g. the attacker, or what.

**Comment by Jaizu** [comment]
Idk if tests support that but there are plenty of double battle bugs related to items, it would be nice to add tests for those too, I'm pretty sure some will fail based on opened issues.

**Comment by CallmeEchoo** [comment]
> Idk if tests support that but there are plenty of double battle bugs related to items, it would be nice to add tests for those too, I'm pretty sure some will fail based on opened issues.

Could you provide some examples of those issues so I can write some targeted tests? :)

**Comment by Jaizu** [comment]
#2967 
In that issue there are 2 issues listed as well

**Comment by CallmeEchoo** [comment]
> #2967 
> In that issue there are 2 issues listed as well

Thanks I will look into it

**Comment by CallmeEchoo** [comment]
issue 3 fixed, pls review :)

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
