### PR TITLE
Primal Reversion Tweaks

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Addresses #1806 and #1860. I think it needs some extra testing though.
While the change I applied to try to solve #1860 definitely seems to help primal reversion trigger more consistently in doubles, I'm afraid it may not be a good or definitive solution, since I just had one battle in which a Groudon holding a Red Orb didn't go primal, even though I do have a Mega Bracelet in my bag.

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by kleeenexfeu** [comment]
> even though I do have a Mega Bracelet in my bag.
Posting it here because I see a mention of it, and also because I haven't looked at the code at all; but primal reversion doesn't require to have a keystone, the only requirement is the right species holding the right orb.

As a sidenote, you can also have 6 primal groudon during a battle, there is no set limit

**Comment by LOuroboros** [comment]
> Posting it here because I see a mention of it, and also because I haven't looked at the code at all; but primal reversion doesn't require to have a keystone, the only requirement is the right species holding the right orb.

I gave it a quick check, and you're right. I started a clean savefile, injected a Groudon with a Red Orb as soon as I could, and it was able to undergo Primal Reversion just fine.

I'll see if I can address it here, because right now it probably *does* need the Mega Bracelet in the BE.

**Comment by LOuroboros** [comment]
Ready for review :eyes:

**Comment by LOuroboros** [comment]
Alright NOW it's ready for review 👀

**Comment by LOuroboros** [comment]
Alright NOW it's truly, actually ready for review, I promise 👀

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
