### PR TITLE
Ogerpon masks were missing their hold effects

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Ogerpon Masks boost base power of moves by 20%

### CODE REVIEW

**Comment by hedara90** [comment]
Isn't it supposed to boost power of moves by 20%? Not attack.

**Comment by AlexOn1ine** [comment]
> Isn't it supposed to boost power of moves by 20%? Not attack.

ye, it is in the correct function meaning move base modifier 😅

Though, I'm going to write some tests. Kinda rushed the pr

**Comment by hedara90** [comment]
Ah, I only read the description.

**Comment by AlexOn1ine** [comment]
Test added.

**Comment by AlexOn1ine** [comment]
Ready for review again. There was still a bug that the test didn't pick up. You need to specify the actual for for the test to pick up the changes.

**Comment by kittenchilly** [comment]
Can you add ogerpon mask to sHoldEffectNames in battle_debug.c then

**Comment by AlexOn1ine** [comment]
> Can you add ogerpon mask to sHoldEffectNames in battle_debug.c then



> Can you add ogerpon mask to sHoldEffectNames in battle_debug.c then

added

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
