### PR TITLE
Pokemon GFX Upgrades/Fixes

### LINKED ISSUE #3553: Reminder: Add CyanSMP's Gen 9 icons
### Description

I saw this [commit ](https://github.com/leo60228/pokeemerald/commit/56f10adf1d817c8d3d35b18d803292477008ccda) and I thought it would be a good to the current icons.

### Discord contact info

doejohn126

### LINKED ISSUE #3613: togepi icon has a transparent pixel on first frame
### Description

Title

### Version

1.6.2 (Default)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #3772: Reminder to replace Tyrantrum back sprite
### Description

image

### Version

1.7.0 (Default)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by katykat5099**
## Description
Upgrades / Fixes to Pokemon Species sprites

## Images
todo

## Issue(s) that this PR fixes
Fixes #3772 
Fixes #3613 
Fixes #3553 

## **Discord contact info**
Kakariki

### CODE REVIEW

**Comment by Jaizu** [comment]
tyrantrum backsprite should have the shiny palette loaded

**Comment by Bassoonian** [comment]
If you include "Fixes" before each issue number, they'll automatically get marked as resolved when the PR gets approved :)

**Comment by katykat5099** [comment]
> tyrantrum backsprite should have the shiny palette loaded

Thanks, will fix. Must've forgot to change it back.
btw, is there a way to get notifications sent to mobile? I didn't see these comments and just stumbled upon them now.

**Comment by Jaizu** [comment]
I personally get the mby mail, not sure about git clients o7

**Comment by katykat5099** [comment]
Alright, I changed it to the shiny sprite.

I can set it up for review, and I'll just pr again, I've got a list but they're almost all harder ones to do.
~~And I like to do it when I have fun doing it. lol~~

One thing though, shouldn't it be going to upcoming or is this one, since its minor changes, fine to go to master?

**Comment by Bassoonian** [comment]
All the fixes should definitely go to master. I think the upgrades are technically better suited for upcoming, if you don't mind splitting the PR for that :)

**Comment by AlexOn1ine** [comment]
> All the fixes should definitely go to master. I think the upgrades are technically better suited for upcoming, if you don't mind splitting the PR for that :)

I think it's fine if all goes to master. 😅
The PR is simple enough.

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
