### PR TITLE
Test for Merged Branch

### PR DESCRIPTION
**Pull request by ExpoSeed**
Currently, all ifdefs for `BATTLE_ENGINE`, `ITEM_EXPANSION`, and `POKEMON_EXPANSION` have been deleted.

Next step: try experimenting with a `NEW_POKEMON` define that will optionally enable post gen3 pokemon

Open questions for `NEW_POKEMON`:
- how to handle unown forms, deoxys forms, etc.?
- how to handle evolution table without making it look ugly and still being consistent?
- how to handle special species and items defined in `battle_config.h`, `item_config.h`, etc.?

### CODE REVIEW

**Comment by LOuroboros** [comment]
> how to handle evolution table without making it look ugly and still being consistent?

I think a sensible choice would be to bring back the file to its default state, and then re-add the different Gen. 4+ species' evolution entries after `SPECIES_METANG`'s own entry..
This implies separating families such as `SPECIES_ELEKID` and `SPECIES_ELECTABUZZ` for example, but it's probably the cleanest way to go about it, I think.
Exceptions will have to be made with `#ifdef`s in the middle, such would be the case of Eevee for example, since you can't have 2 entries for the same species in the table.

**Comment by MandL27** [comment]
> how to handle evolution table without making it look ugly and still being consistent?
Seconding the idea discussed on Discord, which is having separate files for old-only and old+new, with `#ifdef NEW_POKEMON` around the latter (and its inverse around the former) so only one of them is actually used. Could probably apply this logic to any data tables that get inordinately messy if vanilla and expanded are both offered as options.

**Comment by AsparagusEduardo** [comment]
> how to handle unown forms, deoxys forms, etc.?

I think forms introduced in Gen 3 and before should be kept wether `NEW_POKEMON` is activated or not.

**Comment by AsparagusEduardo** [comment]
Superseded by #2229

**Pull request closed without merging**
