### PR TITLE
Fixes Dancer, adds Revelation Dance interactions with Z-Move, Roost and typeless mons

### PR DESCRIPTION
**Pull request by PhallenTree**
Adds Tests for Revelation Dance.

The following Revelation Dance interactions were added:

- If a Pokémon is Typeless, Revelation Dance will have no type (in which case Revelation Dance will not receive STAB). If a Pokémon has lost its primary Flying type due to having used Roost earlier this turn and uses Revelation Dance due to Dancer, Revelation Dance's type will match its current type: its secondary type if it has any, or else be Normal-type (regardless of type additions by Forest's Curse or Trick-or-Treat).
- Typeless Revelation Dance does not activate Color Change and is blocked by Wonder Guard. Conversion 2 will fail if the last move used by the target was typeless Revelation Dance.
- Regardless of the user's types, Revelation Dance is always treated as Normal-type for Z-Move mechanics, and can be upgraded to Breakneck Blitz by a Normalium Z.

Also fixes Dancer-called moves not updating their type according to the new user of the move.

## Feature(s) this PR does NOT handle:
When merging to upcoming, will be necessary to modify the checks for CheckDynamicMoveType.

## **Discord contact info**
PhallenTree

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
The CI fails.

**Comment by PhallenTree** [comment]
tests

I've run out of ideas to fix this. Fails on CI, passes on manual build

**Comment by PhallenTree** [comment]
> Are you able to make it fail locally by running at 4 threads? `make -j4 check`?

Yes, while running at 4 threads the test fails

**Comment by AsparagusEduardo** [comment]
> Yes, while running locally at 4 threads the test fails

What does the replay looks like? (you can open the elf file on mGBA)

**Comment by AsparagusEduardo** [comment]
> > Yes, while running locally at 4 threads the test fails
> 
> What does the replay looks like? (you can open the elf file on mGBA)

Wait, that's too many tests. Let's see if it fails just with `make -j4 check TESTS="Revelation Dance".

**Comment by AsparagusEduardo** [comment]
Ok, finally made it fail locally with just Dancer tests: `make -j3 check TESTS="Dancer"`

**Comment by PhallenTree** [comment]
I tried moving the Dancer test to above the previous one and it passes as well.
Should I just do that and add a comment to let others know that test fails if executed on thread 0?

**Comment by AsparagusEduardo** [comment]
In some cases, it seems that the battler sent to `AbilityBattleEffects` is changed. I'm not sure why it's happening.
image

But @AlexOn1ine identified that `MOVEEND_DANCER`'s loop should use `gBattlersCount` instead of `MAX_BATTLERS_COUNT`, which fixes the issue. Can you apply this change?
```diff
-                   for (battler = 0; battler < MAX_BATTLERS_COUNT; battler++)
+                   for (battler = 0; battler < gBattlersCount; battler++)
                    {
                        if (GetBattlerAbility(battler) == ABILITY_DANCER && !gSpecialStatuses[battler].dancerUsedMove)
                        {
                            if (turnOnHitmarker)
                                gHitMarker |= HITMARKER_ATTACKSTRING_PRINTED;
                            if (!nextDancer || (gBattleMons[battler].speed < gBattleMons[nextDancer & 0x3].speed))
                                nextDancer = battler | 0x4;
                        }
                    }

**Comment by PhallenTree** [comment]
It seems to me that it still had the speeds of the battlers from the previous test ("Dancer triggers from slowest to fastest") hence it using battler = 3 (which is the slowest in that test)

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
