### PR TITLE
Added back GBA sprites via config

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Restores Emerald's Pokémon sprites via new `P_GBA_SPECIES_GFX` config (off by default).

## Images
image image

## **People who collaborated with me in this PR**
@AlexOn1ine for their help with script to migrate data from vanilla to our current `gSpeciesInfo`.

## Feature(s) this PR does NOT handle:
We don't add new GBA-style sprites for any Pokémon that doesn't exist in Gen 3, so families will potentially look inconsistent.
Contributors are welcome to PR Gen3-style sprites, but they are low priority to me at least.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
GBA icons restored. Ready for review!

**Comment by Bassoonian** [comment]
Can you update the images in the PR description to reflect the now accounted for footprints and icons?

**Comment by AsparagusEduardo** [comment]
> Can you update the images in the PR description to reflect the now accounted for footprints and icons?

Done.

**Comment by kittenchilly** [comment]
I think it should be referred to as something like P_OLD_SPECIES_GFX since P_GBA_SPECIES_GFX I feel is too vague. Also technically all gfx on the gba is gba gfx lol

**Comment by AsparagusEduardo** [comment]
> I think it should be referred to as something like P_OLD_SPECIES_GFX since P_GBA_SPECIES_GFX I feel is too vague. Also technically all gfx on the gba is gba gfx lol

I called them "GBA" instead of "OLD" because if people were to contribute to add Gen3-style sprites for new Pokémon, then it would be an actual misnomer imo, as it's about the style instead of time difference (GBA vs DS)

**Comment by AsparagusEduardo** [comment]
As requested by @Bassoonian, separated icons and footprints into their own configs.

**Comment by kittenchilly** [comment]
> > I think it should be referred to as something like P_OLD_SPECIES_GFX since P_GBA_SPECIES_GFX I feel is too vague. Also technically all gfx on the gba is gba gfx lol
> 
> I called them "GBA" instead of "OLD" because if people were to contribute to add Gen3-style sprites for new Pokémon, then it would be an actual misnomer imo, as it's about the style instead of time difference (GBA vs DS)

Hm maybe then it can be P_GBA_STYLE_SPECIES_GFX

**Comment by Bassoonian** [comment]
Their actual path in the repo still refers to them as "old", so even if the config has a different name, it's still referred to as old somewhere. Do they truly need to be in a separate folder anyway? What's preventing us from doing eg `front_gba.png`?

**Comment by AsparagusEduardo** [comment]
> Their actual path in the repo still refers to them as "old", so even if the config has a different name, it's still referred to as old somewhere. Do they truly need to be in a separate folder anyway? What's preventing us from doing eg `front_gba.png`?

You're right, I'll rename them too.

**Comment by AsparagusEduardo** [comment]
Moved files to the `graphics/pokemon` folder with the `_gba` suffix.
Also, renamed the configs.

Ready for re-review.

**Comment by Bassoonian** [comment]
There are still a handful of files in the `pokemon_old` folder

**Comment by AsparagusEduardo** [comment]
> There are still a handful of files in the `pokemon_old` folder

Done

**Review by Bassoonian — APPROVED** [review]

**Pull request merged**
