### PR TITLE
Hunger Switch and Aura Wheel

### PR DESCRIPTION
**Pull request by BuffelSaft**
## Description
Implement the ability Hunger Switch and the move Aura Wheel.

Hunger Switch:
- Switches Morpeko between full belly and hangry mode at the end of each turn
- Does not work for transformed mons
- Morpeko's form reverts to full belly on switch out or battle end

Aura Wheel:
- Can only be used by Morpeko
- Changes to Dark type when used by hangry mode Morpeko
- Raises speed after a successful use

Also fixes Hyperspace Fury's species check.

Addresses #1041 and #1072

## **Discord contact info**
Buffel Saft#2205

### CODE REVIEW

**Comment by BuffelSaft** [comment]
Testing notes from Sword:
- Hunger Switch doesn't trigger the abililty pop up
- Morpeko reverts to full belly mode when switched out in hangry mode
- Aura Wheel shouldn't raise speed if it KO's the last mon in a party

**Comment by BuffelSaft** [comment]
Merged with BE and removed the ability pop up from Hunger Switch. The issue with Aura Wheel raising speed at the end of a wild battle is also present with Flame Charge, so I'd assume all hit + stat change moves have this problem. I'll raise a separate issue to handle that.

Ready for review!

**Review by ghoulslash — DISMISSED** [review]
just fix conflicts

**Comment by BuffelSaft** [comment]
> just fix conflicts
Done!

**Review by ghoulslash — APPROVED** [review]

**Pull request merged**
