### PR TITLE
Implemented Gulp Missile

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
I implemented Cramorant's Gulp Missile. Plain and simple.
I don't really know why I did it, I think I just wanted an excuse to look into the form changes I've never been interested in.

Anyway, the summary of the effect, because it's a scattered a bit throughout a few sections of `src/battle_util.c`:
-Cramorant changes into its Gulping form if it uses Surf or Dive and if it has more than half of its health.
-It launches a counterattack and reverts to its base form if it's hit by an opponent's move.
-Cramorant changes into its Gorging form if it uses Surf or Dive and if it has half or less of its health.

Cramorant's counterattack has different effects depending on its form.
-In Gulping form, it reduces the opponent's Defense by 1 stage.
-In Gorging form, it paralyzes them instead.

The counterattack has its own animation set, a copy of Tackle. If y'all have any suggestions on how to improve it or if you want me to come up with an original animation, let me know. I'm willing to give that a go.

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by LOuroboros** [comment]
This PR addresses #1024 which I cannot link to this PR because reasons.

**Review by ghoulslash — APPROVED** [review]

**Review by AsparagusEduardo — DISMISSED** [review]

**Comment by LOuroboros** [comment]
Solved conflicts.

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
Gulp Missile's damage is activating when it's in base form and not having used Dive or Surf
gulpmissile1
Plus, there's a weird pause after the hit to Oddish when hiding healthboxes.

**Comment by AsparagusEduardo** [comment]
Forgot to say, mon with Magic Guard should be inmune to Gulp Missile's attack but it isn't atm.

**Comment by LOuroboros** [comment]
> 
> 
> Gulp Missile's damage is activating when it's in base form and not having used Dive or Surf
> gulpmissile1
> Plus, there's a weird pause after the hit to Oddish when hiding healthboxes and it's not blinking after getting damaged.



> 
> 
> Forgot to say, mon with Magic Guard should be inmune to Gulp Missile's attack but it isn't atm.

I addressed those and a couple of other things in the latest commit. Ready for re-review :eyes:

**Comment by BuffelSaft** [comment]
I've found a couple of issues:
- If Surf KO's the target, "Cramorant" doesn't change form:
gulp-missile-ko
- If Gulp Missile's damage KO's the target, the secondary effect still triggers on the fainted mon:
gulp-missile-effect
I've set the defines for Cramorant like so for testing:
```#define SPECIES
_CRAMORANT               SPECIES_TORCHIC
#define SPECIES_CRAMORANT_GORGING       SPECIES_COMBUSKEN
 #define SPECIES_CRAMORANT_GULPING       SPECIES_BLAZIKEN
```
And it's definitely working normally:
gulp-missile-lotad

Also for the animation I'd suggest Rock Blast with a custom particle.

**Comment by LOuroboros** [comment]
Ready for re-re-review :eyes:

**Comment by BuffelSaft** [comment]
You'll also need checks for Full Metal Body, Big Pecks, White Smoke and Flower Veil in the stat lowering part, as those block defense drops too.

**Comment by LOuroboros** [comment]
Ready for re-re-re-review 👀

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
Flower Veil's protection should only apply to himself and their allies if they're grass type.
flowerveil
In the GIF, Poochyena has Flower Veil and isn't a grass type but it's being protected anyway.

**Comment by LOuroboros** [comment]
Ready for re-re-re-re-review 👀

**Comment by BuffelSaft** [comment]
Can confirm Flower Veil is working as expected - Wurmple has Flower Veil here:
flower veil
And here's the same test with flying type Sceptile:
flying sceptile

One more thing (sorry Lunos!): there's some weird behaviour if the attacker has Contrary:
contrary
The stat animation shows defense being raised, but the stat isn't actually changed. Not sure if this is a bug with Contrary or Gulp Missile - if it's Contrary that's broken then I think this PR is good to go.

I've retested the other cases and they're all working as expected.

**Comment by LOuroboros** [comment]
> 
> 
> Can confirm Flower Veil is working as expected - Wurmple has Flower Veil here: flower veil And here's the same test with flying type Sceptile: flying sceptile
> 
> One more thing (sorry Lunos!): there's some weird behaviour if the attacker has Contrary: contrary The stat animation shows defense being raised, but the stat isn't actually changed. Not sure if this is a bug with Contrary or Gulp Missile - if it's Contrary that's broken then I think this PR is good to go.
> 
> I've retested the other cases and they're all working as expected.

Nope, it's not a Contrary thing. It's happening even on 'mons that don't have Contrary.

%pn_1188

I'll look into it.

**Comment by LOuroboros** [comment]
Ready for re-re-re-re-re-review 👀

**Comment by AsparagusEduardo** [comment]
I'm thinking... what if instead of creating a macro for just checking Flower Veil we create one for checking if stats can be lowered in general? That way we can use it for other stuff.

**Review by AsparagusEduardo — APPROVED** [review]
You know what, regarding my previous comment, I think that should be tested in a different PR.
It's time.

**Comment by LOuroboros** [comment]
>  It's time.

https://user-images.githubusercontent.com/4485172/135698254-df0d0dda-ed3a-4560-a044-4f03cd46a8ed.mp4

**Pull request merged**
