### PR TITLE
Made EFFECT_WRING_OUT read the max power from the move's argument field

### LINKED ISSUE #4178: Hard Press's damage is wrong
### Description

Hard Press currently uses EFFECT_WRING_OUT, which caps at 120 BP. Hard Press caps at 100. Consider using a param for the max power instead of hard-coding to 120?

### Version

1.7.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Closes #4178

## **Discord contact info**
lunos4026

### CODE REVIEW

**Review by AlexOn1ine — APPROVED** [review]

**Comment by AlexOn1ine** [comment]
Maybe a new name for wring out?

**Comment by LOuroboros** [comment]
> Maybe a new name for wring out to represent both hard press and wring out?

Oh, you mean to rename `EFFECT_WRING_OUT`?

Uh, sure. I don't kno what to though. `EFFECT_FIXED_DAMAGE_ARG_BASED_ON_HP` I guess?

`EFFECT_VARY_POWER_BASED_ON_HP` looks nice too.

Those are some of the first ideas that popped in my head after checking Sonicboom's effect's label.

I guess there's also `EFFECT_HP_DAMAGE`, which would be similar to Seismic Toss' `EFFECT_LEVEL_DAMAGE`.

**Comment by AlexOn1ine** [comment]
I like `EFFECT_VARY_POWER_BASED_ON_HP` more then `EFFECT_HP_DAMAGE`. It is still reasonably long and tells you all you need to know.

**Review by AlexOn1ine — APPROVED** [review]

**Comment by AlexOn1ine** [comment]
damn, this should have been to master I suppose 😅

**Comment by LOuroboros** [comment]
Should it? It's not a test, it's not a bug fix and it's not a code style correction.

**Comment by LOuroboros** [comment]
Then again, I guess it kinda is a bug fix 🤔 ...

I mean, Hard Press having the wrong power limit was an accidental mistake

**Comment by AlexOn1ine** [comment]
> Then again, I guess it kinda is a bug fix 🤔 ...
> 
> I mean, Hard Press having the wrong power limit was an accidental mistake, so.

I think it's fine since we are about to release 1.8. And it is also not clear if it is a bug fix or not, I agree.

**Pull request merged**
