### PR TITLE
Add new Substitute doll sprites

### PR DESCRIPTION
**Pull request by kittenchilly**
## Description
Updates the Substitute doll sprite, like is being done to the Pokemon.
Front sprite is taken from gen 5, while back sprite is custom by CyanSixFour based on gen 4 and gen 5.

## Images
image

## **Discord contact info**
kittenchilly

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
I didn't realize that the new already existed. Why not update that one instead and fix it so that it's read via the other particle configs?

**Comment by kittenchilly** [comment]
> I didn't realize that the new already existed. Why not update that one instead and fix it so that it's read via the other particle configs?

I was thinking it'd be treated the same as Pokemon sprites, without any config. I don't think people would want the old substitute sprite if they have to use new pokemon sprites.

**Comment by AsparagusEduardo** [comment]
> I was thinking it'd be treated the same as Pokemon sprites, without any config. I don't think people would want the old substitute sprite if they have to use new pokemon sprites.

We also want to eventually have that as a config as well, but we're currently restricted by how graphics are loaded.

**Comment by kittenchilly** [comment]
> We also want to eventually have that as a config as well, but we're currently restricted by how graphics are loaded.

Hm ok I'll add the config back then

**Comment by kittenchilly** [comment]
> Hm ok I'll add the config back then
Actually, originally the config was only for the monster doll particle, which seems unused. Not sure if it'll work for the actual substitute sprite
It may be better to revisit this once we add the other pokemon sprites config

**Comment by AsparagusEduardo** [comment]
> Actually, originally the config was only for the monster doll particle, which seems unused. Not sure if it'll work for the actual substitute sprite It may be better to revisit this once we add the other pokemon sprites config

Carry on then xD

**Comment by AsparagusEduardo** [comment]
> > Hm ok I'll add the config back then
> 
> Actually, originally the config was only for the monster doll particle, which seems unused. Not sure if it'll work for the actual substitute sprite It may be better to revisit this once we add the other pokemon sprites config

Alright, makes sense to me. Do you have another back sprite for it? The vanilla back size looks too small to me. If not, lowering the sprite a bit would help as well

**Comment by kittenchilly** [comment]
New backsprite by CyanSixFour has been added thats a combination of the gen 4 and gen 5 ones, looks great
image

**Comment by AsparagusEduardo** [comment]
Question, why 2 different palettes for the front and back?

**Comment by Jaizu** [comment]
This file contains the 3 sprites and its .pal file, they all use the same pal.
[Substitute.zip](https://github.com/rh-hideout/pokeemerald-expansion/files/12496533/Substitute.zip)

image

**Comment by kittenchilly** [comment]
> This file contains the 3 sprites and its .pal file, they all use the same pal. [Substitute.zip](https://github.com/rh-hideout/pokeemerald-expansion/files/12496533/Substitute.zip)
> 
> image

This worked perfectly, thanks. PR should be complete and reviewable now.

**Comment by AsparagusEduardo** [comment]
Looks good, please solve conflicts.

**Comment by kittenchilly** [comment]
> Looks good, please solve conflicts.
Done

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
