### PR TITLE
Incorporated "Better Bag" feature branch

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
~~I regret calling it Better Bag lol~~

## Description
NOTE: Since it's a feature branch, please don't squash.

This branch incorporates togglable item pockets. This however breaks saves, hence they are disabled by default to maintain save compatibility.

### Pockets featured
```diff
    POCKET_ITEMS,
+   POCKET_MEDICINE,
    POCKET_POKE_BALLS,
+   POCKET_BATTLE_ITEMS,
    POCKET_TM_HM,
+   POCKET_POWER_UP, // Restored pocket from 2021
    POCKET_BERRIES,
+   POCKET_TREASURES,
+   POCKET_MEGA_STONES,
+   POCKET_Z_CRYSTALS,
    POCKET_KEY_ITEMS,
```

### Other changes
- Changed Pockets to an enum.
- Items that belong to a pocket that is disabled defaults to a different pocket.
  - Note: Some newer items may need adjusting for an appropiate pocket, so if I missed any, please let me know.
- Bag pocket UI adapts dynamically to the amount of pockets enabled.

## Images
image image image image image image

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by kittenchilly** [comment]
POWER UP should be Other Items right? and I don't think a Mega Stone pocket ever existed in a game, but I guess its fine if there's a z-crystal one. Although the z-crystal and mega stone pocket can just not be there and they both go into the other items pocket.

**Comment by kittenchilly** [comment]
> POWER UP should be Other Items right? and I don't think a Mega Stone pocket ever existed in a game, but I guess its fine if there's a z-crystal one. Although the z-crystal and mega stone pocket can just not be there and they both go into the other items pocket.

Oh, I literally forgot about the vanilla items pocket, which is just the Other Items pocket. nvm, people can just disable stuff if they want it vanilla

**Comment by AlexOn1ine** [comment]
Can we not have one config for this and let users do the rest? This doesn't doesn't look good imo. It has more configs then content

**Comment by AsparagusEduardo** [comment]
> POWER UP should be Other Items right?

"Other Items" (introduced in Gen 8) is the name that the Gen 3's "Items" pocket gets, which is the pocket where everything that doesn't fit in all other pockets goes.
"Power Up" was a pocket in LGPE that includes Evolution stones, PP Ups and PP Maxes. Since its focus is to "power up" your Pokémon, I extended it to include stuff such as mints, Rare/Exp. candies, Ability Capsules/Patches, and vitamins. I received a bit of backlash when I replaced it with the Treasures Pocket, so I believe it was a popular pocket worthy of inclusion.

> I don't think a Mega Stone pocket ever existed in a game, but I guess its fine if there's a z-crystal one. Although the z-crystal and mega stone pocket can just not be there and they both go into the other items pocket.

This can be done by just not enabling those pockets. Indeed, the Mega Stone pocket was added to have parity with the Z-Crystals Pocket in SM/USUM.

**Comment by AsparagusEduardo** [comment]
> Can we not have one config for this and let users do the rest? This doesn't look good imo. It has more configs then content

I did it this way to allow easier customability for the pockets they want, similar to family toggles.

**Comment by AlexOn1ine** [comment]
> > Can we not have one config for this and let users do the rest? This doesn't look good imo. It has more configs then content
> 
> I did it this way to allow easier customability for the pockets they want, similar to family toggles.

It would have been good to open a discussion thread about this. I'm not sure if this is the ideal why of handling it since it is basically 50% content 50% configs. Maybe we can find a better solution together.

**Comment by AsparagusEduardo** [comment]
> It would have been good to open a discussion thread about this. I'm not sure if this is the ideal why of handling it since it is basically 50% content 50% configs. Maybe we can find a better solution together.

Opened a thread on the Discord for feedback and discussion.

**Comment by AsparagusEduardo** [comment]
Closing for now as discussion for the scope of a desired feature is decided.

**Pull request closed without merging**
