### PR TITLE
TheXaman's Randomizer & Challenges (WIP)

### PR DESCRIPTION
**Pull request by katykat5099**
Port over and upgraded TheXaman's Randomizer & Challenges branch.
https://github.com/TheXaman/pokeemerald/tree/tx_randomizer_and_challenges

**SUMMARY**
Overall, most things have been ported and work. With some additional changes.

## Description
First, Check [TX_RAC_FEATURES.md](https://github.com/katykat5099/pokeemerald-expansion/blob/tx_randomizer_and_challenges/TX_RAC_FEATURES.md)

### Changes Compared to TX_RAC_FEATURES.md:
- Option to make Starter Pokemon randomize from a list of pokemon with 3 stage evolutions.
- The "*Evolution stages*" were changed up, rather than special pokemon not being randomized, pokemon with no evolution stages are instead uniquely randomized. (No evo for no evo.) (It's called EVO TYPE NONE, but it should probably replace EVO TYPE SELF)
- Gift pokemon are randomized based on wild pokemon randomization settings currently. (I think this maybe should be a individual option too?)

### Other Changes:
- Works with Modern.
- This branch had compatibility with a very old version of the expansion using old configs, so I updated some of the configs with the new configs. (some of it is still a WIP like the move arrays)
- Gen 9 added to randomization lists. (except random evolutions list)

### Recommended / Todo Changes:
- A setting to allow dupes clause to either let you run away or catch the duplicate pokemon.
- Randomization based on BST setting.
- Currently, Balance On Tiers replaces pokemon by evo stages but does not account for fully evolved stage 2 and middle stage 2. Not sure if this should be fixed.

### Known Issues:
- Pokeballs appear to have 100% catch rates.
- Egg hatching gets block everywhere rather than specific places. In Nuzlocke mode. (Most importantly the lavaridge egg is being blocked)
- Karrablast Evo evolution is broken
- Sometimes pokemon species get set to parter pokemon species after a death in double battles.

### **IMPORTANT**
Some things do not work yet, because I was mainly working on the randomizer and nuzlocke stuff.
Here's a list of things I tested and confirm don't work yet:
- Random evolutions
- Random Type Matchup
- Putting spaces as a nickname lets you bypass forced nicknaming
- EXP Multipliers dont appear to work as intended
- One Type Challenge doesnt appear to work alongside some other challenge settings
- No battle items disables a lot more than just battle items
- Evo Limit disables all evolutions
- Chaos Mode Starters commented out

Things I did not test:
- Chaos Mode 
- Party Limits 5, 4, 3 and 2. (1 works, i just assume the others work. But should probably still be tested)
- Level Cap Hard (Level Cap normal works)
- EXP Multiplied x1.5 (Didnt test this because the other one didnt work and this one is similarly coded.)
- Trainer Items
- Pokemon EVs
- Pokemon IVs
- Trainer EVs
- Stat Equalizer: 100
- Stat Equalizer: 255
- Shiny Clause

**Future Suggestions**
- Make randomization better in general.

## **Discord contact info**
Katy (kakarikiki)

### CODE REVIEW

**Comment by kaicardenas2** [comment]
can this PR be closed or does it need to be kept around for reference?

**Comment by pkmnsnfrn** [comment]
> can this PR be closed or does it need to be kept around for reference?

Correct me if I'm wrong, but I think even if you close it, people can come back and reference it, right?

**Comment by AsparagusEduardo** [comment]
> Correct me if I'm wrong, but I think even if you close it, people can come back and reference it, right?

Yes, unless the author were to force-push empty history 👁️_👁️

**Comment by tertu-m** [comment]
@katykat5099 We're going to delete this PR, as this isn't going to get merged as is. Please keep the branch around so we can refer to it though.

**Pull request closed without merging**
