### PR TITLE
Updating install instructions

### PR DESCRIPTION
**Pull request by hedara90**
## Description

Updating the install instruction to better reflect the current state of the tooling, cleaning it up and removing outdated parts.

## Feature(s) this PR does NOT handle:

Verification of macOS, NixOS and ChromeOS instructions.

## Things to note in the release changelog:

- Install instructions have been moved into individual files under `docs/install/ `

## **Discord contact info**

hedara

### CODE REVIEW

**Comment by hedara90** [comment]
Finished writing install instructions for windows.
They are not tested with anyone not already familiar with how to install stuff.

**Comment by AsparagusEduardo** [comment]
I think INSTALL.md should be kept as an index for the different installation guides

**Comment by hedara90** [comment]
Isn't that what I rewrote `INSTALL.md` to be?
I'll look at it again

**Comment by hedara90** [comment]
Ready for review.
Instructions tested by someone who knew nothing about the project, or what WSL was.

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
