### PR TITLE
Fix max length player name causing overflow+crash on whiteout.

### LINKED ISSUE #4202: Whiteout with max-length player name and Guillotine enabled causes overflow + crash
### Description

Mentioned in the discord here: https://discord.com/channels/419213663107416084/774393519569502268/1208076831958372382

If a player has a name with 7 characters (max length) and has Guillotine decaps enabled, then a whiteout will result in a text overflow and crash with a jump to an invalid address.

7chars
Screenshot_20240217_023608

### Version

upcoming (Edge)

### Upcoming/master Version

ebe13ff

### Discord contact info

ultimate_bob

### PR DESCRIPTION
**Pull request by Ultimate-Bob**
## Description
This copies PLAYER_NAME_LENGTH+1 characters to dest buffer to include the last null terminator when Guillotine appends the fixed case char for player names.

## Images
Before:
7chars

After:
fix7chars

## Issue(s) that this PR fixes

Fixes #4202 

## **Discord contact info**
ultimate_bob

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Can you PR this to merrp's branch instead? That way, vanilla users also benefit from this fix.

**Comment by Ultimate-Bob** [comment]
That's a good idea

**Comment by Ultimate-Bob** [comment]
Here's the same PR for merrps branch: https://github.com/aarant/pokeemerald/pull/26

**Comment by AlexOn1ine** [comment]
Can we close this PR or should we accept the fix here as well?

**Comment by AsparagusEduardo** [comment]
> Can we close this PR or should we accept the fix here as well?

Let's accept it for now, since I assume that #4182 would need to be updated with the latest version of the branch, but we were still discussing how it would need to be handled.

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
