### PR TITLE
[For 2.0][WIP] Species Refactor ™️

### LINKED ISSUE #2291: Add let's go eevee and let's go pikachu species
I think they fit and should be added to the pokémon expansion.
They should differ from regular ones on:
Species ID
Not being able to breed
Different movesets/learnset
Base stats
Shiny locked (not sure if this is out of scope)
Unable to evolve

Additionally, this could be an excuse to make something like not being able to deposit a certain species ID in a storage box, but I feel like that should be handled in a different github issue.

### LINKED ISSUE #2567: Give support for EASY CHAT
There are a few issues currently:
- [ ] Move names not being all uppercase
- [ ] Pokémon names not being all uppercase
- [ ] No support for post gen 3 species

### LINKED ISSUE #2738: Alternate forms don't have heights and weights specifict to them.
As @DizzyEggg noted in #1547, they're currently reading via the national dex number, meaning that Pokémon with differing weight per form don't get the proper battle calculations for weight/height-based moves.

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
- [x] Reordered IDs by game release.
- [x] Tables ordered by base species.
- [x] Added constants for base forms with official names
- [ ] Add data:
  - [ ] Teachable moves from future generations
  - [ ] Species data
    - [x] Generation 9 species.
    - [x] Scatterbug and Spewpa forms corresponding to each Vivillon form
    - [x] Missing Alcremie forms.
    - [ ] Partner Pikachu/Eevee. (Closes #2291)
    - [ ] Shadow Lugia.
    - [ ] Gigantamax Forms (borrowed from #2417).
    - [ ] Totem Forms
- [x] Removed `#if defined SPECIES_` instances.
- [x] Created new macros for `gSpeciesInfo` and grouped them all next to the cases used.
- [x] Pokédex Upgrades
  - [x] Simplify the creation of National and Regional Dexes by having to modify only 2 lists and having them auto-update based what species are disabled.
  - [x] Automatically use 4 digits when the Dex count exceeds 999.
  - [x] Add form dex data (Fixes #2738).
  - [x] Change form entry by pressing L or R in the scrolling list menu
  - [x] Tracking caught and seen specific forms.
  - [x] Configs
    - [x] Config to not show form entry info unless they're actually caught.
    - [x] Config to search mon by single letter instead of groups of 3 letters.
    - [x] Config to skip multiple dex entries (like in SV).
    - [x] Config to have an empty entry at the end of the dex list when there's an unseen mon ahead (like in SV)
    - [x] Config to have the regional dex have a N°000 entry like in Gen 5
- [ ] Config for toggling categories of species (Regional Forms, Mega Evolutions, Gigantamax, future gen evolutions)
- [x] Restore pret mon graphic order
- [x] Separate cries from species order into their own IDs to simplify adding newer species
- [x] Remove Unown hack.
- [x] Reduce space by storing mon pic tables as `u32 *const` instead of `CompressedSpriteSheet`
- [x] Group national dex data (like names and form tables) into their own table.
- [x] Rename Mega Pokémon voice samples from `mega_x.aif` to `x_mega.aif` for consistency.
- [x] Learnsets
  - [x] Learnsets pointers stored in `gSpeciesInfo`.
  - [x] Order Egg Moves by alphabetical order.
  - [x] Order Teachable Moves by alphabetical order.
- [x] Evolution table converted to individual tables to both reduce size and allow for over 10 evolutions (Milcery -> Alcremie)
- [ ] Extended Easy Chat integration (fixes #2567)

## Due to the sheer size of this PR, I decided to slowly port features from it into their own individuals PRs:
- [x] #3048 
- [x] #3116 
- [x] #3047
 
## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by Jaizu** [comment]
Support for Easy Chat is currently broken, so this category does nothing when pressing A.
image

**Comment by Jaizu** [comment]
Eggs are freezing the game on this PR.
On the function: u16 GetEggSpecies(u16 species)
Change:
`for (k = 0; evolutions[k].method != EVOLUTIONS_END; i++)`
to:
`for (k = 0; evolutions[k].method != EVOLUTIONS_END; k++)`

Thanks ghouslash for fixing it

**Comment by AsparagusEduardo** [comment]
> Eggs are freezing the game on this PR. On the function: u16 GetEggSpecies(u16 species) Change: `for (k = 0; evolutions[k].method != EVOLUTIONS_END; i++)` to: `for (k = 0; evolutions[k].method != EVOLUTIONS_END; k++)`
> 
> Thanks ghouslash for fixing it

Fix applied.

**Comment by AsparagusEduardo** [comment]
This PR is a mess. Keeping this open for so long has given people the impression that it's in a usable state, when it isn't.

**Pull request closed without merging**
