### PR TITLE
Fix HGSS dex sort orders working incorrectly

### LINKED ISSUE #5693: HGSS Dex has broken ORDER modes
### Description

ORDER_A_TO_Z shows multiple entries for each Pokemon.
pokeemerald-0

When `HOENN DEX` mode is enabled and an Order other than `NUMERICAL MODE` is selected, National Dex Pokemon are also included in the list.
pokeemerald-1

### Version

upcoming (Edge)

### Upcoming/master Version

572ea141af83caf2f57d50c4e74cb493fb306c88

### Discord contact info

te_on

### PR DESCRIPTION
**Pull request by ravepossum**
## Description
Fixes the HGSS dex orders not working correctly when Hoenn dex mode is on.

## Images
hgss_orders_fix

## Issue(s) that this PR fixes
Fixes #5693 

## **Discord contact info**
ravepossum

### CODE REVIEW

**Comment by hedara90** [comment]
pokeemerald-13

Is this supposed to be here in Hoenn mode?

**Comment by ravepossum** [comment]
Is there a specific thing you can identify that causes that to happen? I'm having trouble replicating it.

pokeemerald-0

**Comment by hedara90** [comment]
I cannot replicate it either on a fresh save.
It might be ghosts of tests past that's making themselves known.
I guess it's time to retire the current testing save then...

**Comment by hedara90** [comment]
I can't seem to get it to happen, maybe it's something with extra mons because I know I had added more species for testing at some point.

**Comment by hedara90** [comment]
I'd say that if nobody else can't replicate this on some old testing save, it's good to go.

**Comment by ravepossum** [comment]
I messed around with Hedara's save and got the weird decamark entry to disappear by clearing PC boxes and resetting dex flags. I'm also inclined to think this is just a crusty save issue.

**Review by hedara90 — APPROVED** [review]

**Pull request merged**
