### PR TITLE
Allow Z-Moves to be selected after Mega Evolution

### LINKED ISSUE #3227: Z-Moves don't work after Mega Evolution
### Description

https://github.com/rh-hideout/pokeemerald-expansion/assets/142124410/c454042e-7f1c-43c1-8a67-e18cb8106f94

As you can see in the video, Z-Moves can't be selected after Mega Evolution. However, reversing the order allows both mechanics to be utilized. In Gen 7, a team is allowed to both Mega Evolve and use a Z-Move in a battle, so the latter is working as intended.

### Version

1.5.2 (Default)

### Upcoming Version

_No response_

### Discord contact info

brandonlollol

### PR DESCRIPTION
**Pull request by kittenchilly**
Z-Moves were erroneously disallowed from being selected after Mega Evolving another Pokemon. This corrects the behavior.

## Issue(s) that this PR fixes
Fixes #3227

## **Discord contact info**
kittenchilly

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
To whoever reviews this, remember to test Mega Rayquaza to being able to use a Z-Move.

**Comment by AsparagusEduardo** [comment]
To whoever reviews this, remember to test Mega Rayquaza NOT being able to use a Z-Move.

**Comment by kittenchilly** [comment]
> To whoever reviews this, remember to test Mega Rayquaza NOT being able to use a Z-Move.

I actually forgot about Mega Rayquaza. I do believe this breaks that. However, it can be fixed by simply disallowing a pokemon from using a z move if it's mega evolved, rather than disallowing z moves entirely if you've mega evolved before.

**Comment by kittenchilly** [comment]
Added a check if you're doing Wish Mega Evolution for if you're holding a z crystal, which makes the mega rayquaza behavior more like gen 7 while keeping my initial changes.
Should be reviewable again.

**Comment by AsparagusEduardo** [comment]
Looks good, but since it's a bugfix it would be better set the target to master.

**Pull request closed without merging**
