### PR TITLE
Use RSE type icons for TMs

### PR DESCRIPTION
**Pull request by MandL27**
## Description

Title. Vanilla and current IE use FRLG icons, which breaks when displaying a Fairy-type TM.

## **Discord contact info**

MandL27#1732

### CODE REVIEW

**Review by Pyredrid — DISMISSED** [review]
Tested to be working.  Of note, however, is that the type icon for fairy type exists in the battle_engine branch, not the item_expansion branch.  Both are needed for this to work, but since fairy typing only exists in battle_engine anyways I think its fine.

**Comment by MandL27** [comment]
That could be fixed by adding the Fairy icon here, but I'm not sure if that's the direction we want to take with IE.

**Review by Pyredrid — APPROVED** [review]
All looks good to me.

**Comment by ultima-soul** [comment]
I'm of the opinion to not make drastic changes like this to the aesthetic of the vanilla game so I'm thinking we should keep the FRLG type icons and make an appropriate fix within that limitation. I believe I have done a fix before for this so I could make a PR for it.

**Comment by MandL27** [comment]
The issue that faces is that you'd have to rework [graphics/interface_fr/menu.png](https://github.com/rh-hideout/pokeemerald-expansion/blob/item_expansion/graphics/interface_fr/menu.png) to have fewer dead tiles so you can squeeze in a Fairy icon. With current IE, Fairy TMs overflow the array and end up looking like "Type: Typ" instead of e.g. "Type: Fairy".

**Comment by ExpoSeed** [comment]
I don't really feel strongly either way, but Ultima is of the opinion that we should keep the FRLG icons over the RSE icons and he can also fix the Type: Typ bug with the frlg icons

**Comment by ExpoSeed** [comment]
Would be interested in hearing more opinions

**Comment by LOuroboros** [comment]
> 
> 
> Would be interested in hearing more opinions

Ultima's solution would let us remain faithful to Game Freak's decision of using FRLG type sprites for the TMs, so *if* their solution is more space friendly than Mandl's, I think I would choose that, personally.

**Comment by ghoulslash** [comment]
this feels like a style choice which is out of the scope of the expansion branches

**Comment by ExpoSeed** [comment]
However, as of current IE, fairy type icons overflow and look like Type: Typ, so something must be done, whether it's in RSE or FRLG

**Comment by ultima-soul** [comment]
I have made PRs for FRLG-styled Fairy-type icon for each branch as the bug is present in all 3: #1327, #1328, #1329.

**Comment by Pyredrid** [comment]
> I have made PRs for FRLG-styled Fairy-type icon for each branch as the bug is present in all 3: #1327, #1328, #1329.

Should we close this PR then?

**Pull request closed without merging**
