### PR TITLE
Fix Jump Kick

### PR DESCRIPTION
**Pull request by BuffelSaft**
This PR fixes issue https://github.com/rh-hideout/pokeemerald-expansion/issues/1268, and also fixes a related bug:
- Jump Kick and Hi Jump Kick now inflict recoil damage on the user if the target was immune to the attack.
- Gen V+ recoil damage is now half of the user's HP instead of half of the target's HP.

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Please add entries in `battle_config.h` for configuring both of these settings.

**Comment by BuffelSaft** [comment]
Done, I've added config options for all variants of Jump Kick recoil from Gen 3 onwards. 
So that covers:
Gen 3: 
- On a miss, recoil is half the damage that would have been dealt, but not more than half of target's max HP
- If the target is immune, there's no recoil

Gen 4: 
- On a miss, behaves the same way as Gen 3
- If the target is immune, recoil is half of target's max HP

Gen 5+:
- If the target is immune or the user misses, recoil is half of the user's max HP

The battle script is pretty ugly though, would it be better to have two copies of BattleScript_MoveMissedDoDamage rather than all the .if blocks?

**Review by ghoulslash — APPROVED** [review]

**Review by ultima-soul — DISMISSED** [review]

**Comment by ExpoSeed** [comment]
Apologies for the late update, but please fix the conflict in `battle_config.h`

**Comment by BuffelSaft** [comment]
Done!

**Review by ultima-soul — APPROVED** [review]

**Review by ghoulslash — APPROVED** [review]

**Pull request merged**
