### PR TITLE
Master Upstream Sync 2021-05-22

### PR DESCRIPTION
**Pull request by pineapplemachine**
## Description

Followed the instructions here to create a more up-to-date master branch: https://www.pokecommunity.com/showthread.php?t=432321

## **Discord contact info**

legume

### CODE REVIEW

**Comment by ExpoSeed** [comment]
1. There are merge conflicts with master still

2. Would you mind listing all the files that you changed or had merge conflicts?

**Comment by pineapplemachine** [comment]
1. Sorry about that D: I hoped I could be helpful by following the steps and getting a newly synced master out but I guess there's a bit more work to do still to resolve the conflicts? I'll try merging master into this branch and see if I think I can work out the conflicts on my own.

2. The changes I made were to resolve merge conflicts in these files (starting with battle_engine, then merging in item_expansion, then pokemon_expansion):

src/pokemon.c
src/data/text/move_names.h
src/data/text/abilities.h
src/data/pokemon/level_up_learnsets.h
src/data/pokemon/egg_moves.h
src/data/pokemon/base_stats.h
src/battle_gfx_sfx_util.c
include/pokemon.h
include/global.h
include/constants/pokemon.h

And then some changes mentioned in the linked tutorial in this file as well:

src/battle_debug.c

The ROM builds and runs in an emulator successfully so I figure I can't have screwed any of it up _too_ badly...

**Comment by LOuroboros** [comment]
> And then some changes mentioned in the linked tutorial in this file as well:
> 
> src/battle_debug.c

I address those in the PR #1492, for whatever that's worth. This PR may cause a conflict with it.

**Comment by pineapplemachine** [comment]
Officially closing this and leaving the job to someone more experienced than me. Sorry!

**Pull request closed without merging**
