### PR TITLE
infestation between turn anim

### PR DESCRIPTION
**Pull request by ghoulslash**
## Description
Adds an end-turn animation for infestation. Previously, the undefined behavior would default to the wrap animation.

infestation

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
I feel this should be a config, as it's quite a long animation to be repeating constantly.

**Comment by ghoulslash** [comment]
> 
> 
> I feel this should be a config, as it's quite a long animation to be repeating constantly.

I think that option would bloat the config file unecessarily. I can shorten the between-turn animation since it is separate from the main one

**Comment by AsparagusEduardo** [comment]
> > I feel this should be a config, as it's quite a long animation to be repeating constantly.
> 
> I think that option would bloat the config file unecessarily. I can shorten the between-turn animation since it is separate from the main one

That'd be nice 👍

**Comment by ghoulslash** [comment]
ready for re-review

**Review by ultima-soul — DISMISSED** [review]

**Comment by AsparagusEduardo** [comment]
In the between turn animation there seems to be a second after the black dots are gone where the mon is still shaking, taking the same amount of time as the regular attack animation. Is there a way to shorten that?

Here's a comparison between the two
infestation

**Comment by ghoulslash** [comment]
> 
> 
> In the between turn animation there seems to be a second after the black dots are gone where the mon is still shaking, taking the same amount of time as the regular attack animation. Is there a way to shorten that?
> 
> Here's a comparison between the two
> infestation

Fixed this issue in the commit `fix shake duration`. The duration of the animation matches whirlpool/sand tomb/etc now

**Review by ultima-soul — APPROVED** [review]

**Review by ExpoSeed — APPROVED** [review]

**Pull request merged**
