### PR TITLE
Implement Enigma Berry's hold effect

### LINKED ISSUE #3281: Enigma Berry's effect is not implemented
### Description

HOLD_EFFECT_ENIGMA_BERRY does nothing, while it should, quoting Showdown
>Restore 1/4 max HP after holder is hit by a supereffective move

### Version

1.5.3 (Default)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by kittenchilly**
## Description
Now holding enigma berry works like it does in gen 4+

## Issue(s) that this PR fixes
Fixes #3281

## **Discord contact info**
kittenchilly

### CODE REVIEW

**Comment by DizzyEggg** [comment]
What about tests? 👀

**Comment by AsparagusEduardo** [comment]
This is a new effect, and therefore go into `upcoming`.

**Comment by AsparagusEduardo** [comment]
Also, tests are indeed missing.

**Comment by AsparagusEduardo** [comment]
Please open a new PR that addresses our concerns.

**Pull request merged**
