### PR TITLE
More Gen 8 Abilities

### PR DESCRIPTION
**Pull request by ghoulslash**
## Description
Complementing Lunos' Gen 8 ability PR:

This adds:
- Screen Cleaner effect (previously was just a switch-in message)
- Steely Spirit
- Transistor
- Dragon's Maw
- Chilling Neigh
- Grim Neigh
- As One
- Curious Medicine

As One Shadow Rider Stat Raise:
as_one_shadow

### CODE REVIEW

**Review by ultima-soul — CHANGES_REQUESTED** [review]
Some notes from my testing:
```
Screen Cleaner:
    - Look at ClearDefogHazards and reset timers for Reflect, Light Screen, Aurora Veil

As One:
    - Unnerve message is supposed to activate right after As One along with Unnerve as the ability in the pop-up
    - As One activation upon defeating a mon is supposed to say X Neigh depending which As One it is

Curious Medicine:
    - Curious Medicine vs. Intimidate when both sent out against each other (like at beginning of battle):
        - If Intimidate opponent is faster, it runs first:
            - Then Curious Medicine will activate to remove stat changes from ally since ally also lost stats from Intimidate
        - Else Curious Medicine never activates since there's no stat changes to reset for ally and Intimidate activates after
    - If switching in a mon with Curious Medicine:
        - Successfully resets stats
        - Prints "<User>'s attack missed!" instead of "<Ally>'s stat changes were removed!"
        - Should only activate if ally actually has any stat changes
```

**Comment by ghoulslash** [comment]
Fixes:
- As One shows ability activation of each ability properly (this is slightly hacky but flexible for any future double abilities)
as_one_ice
- Screen Cleaner resets timers
- Curious medicine proper string, only displays popup if ally stats are reset
curious_medicine

Ready for re-review.

**Review by ultima-soul — DISMISSED** [review]

**Comment by ultima-soul** [comment]
Please resolve conflicts.

**Comment by ghoulslash** [comment]
merged

**Review by ultima-soul — APPROVED** [review]

**Pull request merged**
