### PR TITLE
Fixed Magnemite's and Magneton's battle sprite palettes

### PR DESCRIPTION
**Pull request by LOuroboros**
None. I didn't do a single thing beyond submitting this PR Kappa

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by Jaizu** [comment]
Awesome fix, good job :+1:

**Review by Pyredrid — DISMISSED** [review]

**Review by Jaizu — APPROVED** [review]
All good

**Review by ExpoSeed — APPROVED** [review]

**Review by ultima-soul — CHANGES_REQUESTED** [review]
Magnemite's back sprite is showing the shiny which is correct, but I noticed the tips of the magnets are coloured blue and red rather than all grey which I believe is incorrect.

**Comment by Pyredrid** [comment]
I know we discussed this in discord already but just so its written here:

Magnemite's shiny palette has dark grey magnets until Gen 5 which has slightly darker tipped magnets which in a later gen were changed to be light grey magnets with black tips.

**Comment by Jaizu** [comment]
I will have everything fixed today, sorry about those magnets x)

**Comment by LOuroboros** [comment]
I pushed a new commit. Blackforest went through the trouble of fixing Magnemite, and Magneton too.
Comparison pics coming up soon.

**Comment by LOuroboros** [comment]
Before = Sprite as it is currently used in the pokemon_expansion branch, ignoring this PR entirely.
After = Sprite's state in this PR.

**Before**:
before_magnemite
before_magneton

**After**:
after_magnemite
after_magneton

**Comment by LOuroboros** [comment]
I'm going to quickly redo the PR since the credits were not stated very clearly and that doesn't feel correct to me.

**Pull request closed without merging**
