### PR TITLE
Added a license.

### PR DESCRIPTION
**Pull request by StephenLynx**
I added the MIT license to the project.
It makes legal questions much clearer. The MIT license in specific is permissive which won't cause issues for people that fork the project and use on their own. This is specially important given the scope of this project.

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
We don't own the original code or assets, so we don't have legal the right to put a license I think.

**Comment by StephenLynx** [comment]
I'm positive that if dizzy, which opened the original project chooses to do so, it is ok. This is my thought process: everyone contributed to HIS project. So is HIS prerogative to license the whole thing. What I do know is that not having a public license is a liability.

**Comment by AsparagusEduardo** [comment]
He forked from pret's decompilation project and expanded it. It's not an original game or program, this is a modification of Game Freak's product, so we don't have the legal right to instate licenses.

**Comment by LOuroboros** [comment]
For the record, I don't think @DizzyEggg ever shared his opinion on the matter. I'd like to know it personally since it could be valuable knowledge.

But I think I agree with Eduardo; as a fork of Pokeemerald which doesn't have a license, I'm not sure if we have the right or if it'd be correct to enforce one ourselves.

**Pull request closed without merging**
