### PR TITLE
Photon Geyser and (restored) Shell Side Arm effects work for physical moves 

### PR DESCRIPTION
**Pull request by Sneed69**
Restored `EFFECT_SHELL_SIDE_ARM` and made it and `EFFECT_PHOTON_GEYSER` work when used with a physical move.

## **Discord contact info**
duke5614

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
doesn't matter but it would be good to also remove the BP mul from the shellsidearm func

**Comment by Sneed69** [comment]
> doesn't matter but it would be good to also remove the BP mul from the shellsidearm func

I'm not sure how to do this and have identical results in 100% of situations.

**Comment by AlexOn1ine** [comment]
> > doesn't matter but it would be good to also remove the BP mul from the shellsidearm func
> 
> I'm not sure how to do this and have identical results in 100% of situations.

That means we can't use an effect for shell side arm though.

**Comment by AsparagusEduardo** [comment]
> That means we can't use an effect for shell side arm though because the base power requirement for other moves might be wrong..

I have an idea. What if we modify the function such that it takes the first of `EFFECT_SHELL_SIDE_ARM`'s move available in a mon's moveset? It's unlikely that a mon will have multiple of these moves and we need the calculation to be done before the beginning of the turn, so while not fully matching official functionality, it will at least make it easier to make clones of it.

**Comment by AlexOn1ine** [comment]
> > That means we can't use an effect for shell side arm though because the base power requirement for other moves might be wrong..
> 
> I have an idea. What if we modify the function such that it takes the first of `EFFECT_SHELL_SIDE_ARM`'s move available in a mon's moveset? It's unlikely that a mon will have multiple of these moves and we need the calculation to be done before the beginning of the turn, so while not fully matching official functionality, it will at least make it easier to make clones of it.

how do you handle metronome and me fist, mirror move and such?

**Comment by Sneed69** [comment]
The simplest way (that behaves exactly like it does now) is to store attacker level, attack and sp. atk, defender def and sp.def and do the calcs later

**Review by AlexOn1ine — APPROVED** [review]
Based on a conversation with Duke on [discord](https://discord.com/channels/419213663107416084/774393519569502268/1262036648124743731). I believe it is fine to be merged.

**Pull request merged**
