### PR TITLE
Kee berry

### LINKED ISSUE #4105: Kee Berry wrong proc
### Description

If the enemy Pokemon used a Physical Move on my Pokemon, it's Kee Berry activated when it shouldn't, as it would only activate if I hit it with a Physical Move. Added to that, while visibly showing that the enemy got a Defense Boost, my Pokemon got the defense Boost in reality.

### Version

upcoming (Edge)

### Upcoming/master Version

09d12fb

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #4105. 

Feels a little hacky but shouldn't cause any issues because Kee Berry and Maranga Berry are the only ones that use the function where this check is important. 

Also removed a redundant Kee Berry test. It was tested above already.

### CODE REVIEW

**Comment by Bassoonian** [comment]
The Bug Bite test is failing now, for some reason

**Comment by AlexOn1ine** [comment]
> The Bug Bite test is failing now, for some reason

makes sense that it would fail, damn.

**Comment by AlexOn1ine** [comment]
Should be good now. Once again tests preventing a regression.

**Review by Bassoonian — APPROVED** [review]

**Comment by AsparagusEduardo** [comment]
Please try to be more descriptive for the PR names.
It's not difficult to add "Fixed " to it.
Now the history doesn't show what this does in its name :/

**Comment by AlexOn1ine** [comment]
> Please try to be more descriptive for the PR names. It's not difficult to add "Fixed " to it. Now the history doesn't show what this does in its name :/

Sorry, this was my bad. I previously had Fixes Kee Berry but I messed some stuff up. Fixed.

**Pull request merged**
