### PR TITLE
Disable OW followers by default

### PR DESCRIPTION
**Pull request by Bassoonian**
Disables OW followers by default, preventing us from silently activating them in projects that may not want it. For precedent regarding including features but having them off by default, see the VS Seeker and HGSS Dex implementations.

## **Discord contact info**
bassoonian

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
We should consider turning all features on in debug mode. See #4664

**Comment by Bassoonian** [comment]
> We should consider turning all features on in debug mode. See #4664

I think that this is out of scope for the default, for one, so re-enabling followers in debug mode should be in that PR rather than this one. I also think that a debug build for expansion can very well differ from a user's debug build (which would presumably want to preserve their selection of features rather than all), but that's a discussion for that PR

**Comment by AsparagusEduardo** [comment]
> Disables OW followers by default, preventing us from silently activating them in projects that may not want it. For precedent regarding including features but having them off by default, see the VS Seeker and HGSS Dex implementations.

I actually believe that we should start doing the opposite for HGSS Dex, as a way to showcase features before they decide to disable them, plus making it easier on us to debug issues with it (for this last point, I need to add an option to the debug menu to see the vanilla dex when the HGSS menu is enabled)
We already allow them to opt out of undesired features, so having new features enabled by default for new users should be fine.

**Comment by AlexOn1ine** [comment]
> > Disables OW followers by default, preventing us from silently activating them in projects that may not want it. For precedent regarding including features but having them off by default, see the VS Seeker and HGSS Dex implementations.
> 
> I actually believe that we should start doing the opposite for HGSS Dex, as a way to showcase features before they decide to disable them, plus making it easier on us to debug issues with it (for this last point, I need to add an option to the debug menu to see the vanilla dex when the HGSS menu is enabled) We already allow them to opt out of undesired features, so having new features enabled by default for new users should be fine.

Then we should disable all species past gen3 otherwise we will run into species issues sooner then later.

**Comment by AsparagusEduardo** [comment]
> Then we should disable all species past gen3 otherwise we will run into space issues sooner then later.

That's a different discussion altogether. Features like HGSS Dex or potential future DexNav will never compare to the size used by Pokémon cries.
Heck, adding follower sprites for Gens *1-8* only took 3.4% of the total size, while cries take around 25%!

**Comment by AlexOn1ine** [comment]
> > Then we should disable all species past gen3 otherwise we will run into space issues sooner then later.
> 
> That's a different discussion altogether. Features like HGSS Dex or potential future DexNav will never compare to the size used by Pokémon cries. Heck, adding follower sprites for Gens _1-8_ only took 3.4% of the total size, while cries take around 25%!

Yeah sorry I just checked. Somehow I thought it adds much more.

**Comment by DizzyEggg** [comment]
Should this be closed now that we've decided to keep new features enabled?

**Comment by Bassoonian** [comment]
Ready for review again, fixed conflicts and added an explicit warning about additional scripting being required as discussed on Discord.

**Review by ghoulslash — APPROVED** [review]

**Pull request merged**
