### PR TITLE
Fix White Herb Known Failing tests

### PR DESCRIPTION
**Pull request by DizzyEggg**
This changes some code around White Herb / Red Card / Eject items, so it's possible I missed some edge cases around these. If there are any tests which should be included please let me know.

Oh and I had to comment out a Pickpocket White Herb, because I couldn't think of any interaction between these two. If it's agreed there isn't one, I can remove it entirely.

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
> Oh and I had to comment out a Pickpocket White Herb, because I couldn't think of any interaction between these two. If it's agreed there isn't one, I can remove it entirely.

My bad. I would remove it, yeah.

**Comment by AlexOn1ine** [comment]
> > Oh and I had to comment out a Pickpocket White Herb, because I couldn't think of any interaction between these two. If it's agreed there isn't one, I can remove it entirely.
> 
> My bad. I would remove it, yeah.

@DizzyEggg do you want to remove it or should I just merge? Though I don't see a reason to keep the test.

**Comment by DizzyEggg** [comment]
> > > Oh and I had to comment out a Pickpocket White Herb, because I couldn't think of any interaction between these two. If it's agreed there isn't one, I can remove it entirely.
> > 
> > 
> > My bad. I would remove it, yeah.
> 
> @DizzyEggg do you want to remove it or should I just merge? Though I don't see a reason to keep the test.

I removed the test. Though given how big 1.8 already is, maybe it's better to merge it after the update?

**Comment by AlexOn1ine** [comment]
> > > > Oh and I had to comment out a Pickpocket White Herb, because I couldn't think of any interaction between these two. If it's agreed there isn't one, I can remove it entirely.
> > > 
> > > 
> > > My bad. I would remove it, yeah.
> > 
> > 
> > @DizzyEggg do you want to remove it or should I just merge? Though I don't see a reason to keep the test.
> 
> I removed the test. Though given how big 1.8 already is, maybe it's better to merge it after the update?
Sounds good

**Comment by AlexOn1ine** [comment]
Conflicts :eyes:

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
