### PR TITLE
Clean up contest strings

### PR DESCRIPTION
**Pull request by Bassoonian**
Clean up contest strings, removing all the unused ones (which saves a bunch of space!) and moving most others out of the .inc and header file and into `contest.c`. Not completely finished yet, hoping for some feedback before I continue. I did find out compound strings take just that tiny bit more of ROM space compared to a bare pointer to an .inc string, and while the removal of all the unused strings makes up for it here, it may be something we want to keep in mind before we turn things into compound strings more than necessary.

## **Discord contact info**
bassoonian

### CODE REVIEW

**Comment by DizzyEggg** [comment]
>I did find out compound strings take just that tiny bit more of ROM space compared to a bare pointer to an .inc string, and while the removal of all the unused strings makes up for it here, it may be something we want to keep in mind before we turn things into compound strings more than necessary.

I think it's because of alignment. For some reason modern aligns all the strings, even though they don't really need to be aligned. I'm not sure how or if it's possible to change it 🤔

**Comment by Bassoonian** [comment]
Technically not 100% finished, but this has been sititng here for a while and I haven't been feeling like doing the rest, so let's consider this ready for review so the work isn't lost and someone else can finish it later :)

**Comment by AsparagusEduardo** [comment]
> Technically not 100% finished, but this has been sititng here for a while and I haven't been feeling like doing the rest, so let's consider this ready for review so the work isn't lost and someone else can finish it later :)

What's missing?

**Comment by Bassoonian** [comment]
`gContestEffectDescriptionPointers` should be moved to C and its contents (where possible) converted to compound strings, but that's essentially it

**Review by DizzyEggg — APPROVED** [review]

**Pull request merged**
