### PR TITLE
use dka container for a more modern gcc

### PR DESCRIPTION
**Pull request by SBird1337**
Switches the build environment in the CI to a DKP docker container.

## Description
Seemed like one of the easiest ways to get an up to date arm toolchain, it's also what a lot of people use to build the project, so it should match the user environment as well as provide a modern toolchain.

Depends on #3428 

## Issue(s) that this PR fixes
/

## **Discord contact info**
karathan

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
I think we need to update the `INSTALL.md`

**Comment by SBird1337** [comment]
> I think we need to update the `INSTALL.md`

How so?

**Comment by AsparagusEduardo** [comment]
> How so?

Don't we need to do that for the WSL instructions? Seeing that Ubuntu doesn't come with the latest gcc and collaborators and users could get frustrated on why their code works locally but not on CI

**Comment by SBird1337** [comment]
rebased to `upcoming` and set to ready. CI passes on gcc 13.2 :)

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
