### PR TITLE
Adds new scripting macros to increase developer quality of life

### PR DESCRIPTION
**Pull request by pkmnsnfrn**
# Description
Brendan using getobjectfacingdirection to tell what direction the player is facing

* Adds new scripting macros (`removeallitem`, `getobjectxy`, `getobjecttemplatexy`, `getobjectcurrentxy`, `checkobjectat`, `setseenmon`, `setcaughtmon`, `getseenmon`, `getcaughtmon`, `checkspecies`, `checkspecies_choose`, `checkspecies_auto`, `getobjectfacingdirection`) to increase developer quality of life

### `removeallitem`
Remove all of specified item from the player's bag.
### `getobjectxy` / `getobjecttemplatexy` / `getobjectcurrentxy`
Stores the position of the given object in `VAR_0x8007` (x) and `VAR_0x8008` (y). Mode `CURRENT_POSITION` will take the object's current position. Mode `TEMPLATE_POSITION` will take the object's template position.
### `checkobjectat`
Checks if there is any object at a given x and y position.
### `setseenmon` / `setcaughtmon`
Checks the state of the Pokédex Seen / Caught flag of the specified Pokemon and stores the result in `VAR_RESULT`.
### `getseenmon` / `getcaughtmon`
Sets the Pokédex Seen / Caught flag of the specified Pokemon.
### `checkspecies` / `checkspecies_choose` / `checkspecies_auto`
Check if the Player has \speciesId in their party. `OPEN_PARTY_SCREEN` will have the player select a mon from their party. `NO_PARTY_SCREEN` will automatically check every mon in the player's party.
### `getobjectfacingdirection`
Gets the facing direction of a given event object and stores it in the given variable.

# Testing
## Clean Branch
You can recreate this branch by applying a patch or pulling the repo. From a clean version of expansion's upcoming, you can either:

### Patch
`wget https://files.catbox.moe/031oqa.patch -O script.patch ; git apply script.patch ; rm script.patch`

### Repo
`git remote add psf-expansion https://github.com/PokemonSanFran/pokeemerald-expansion/ ; git pull psf-expansion scriptCommands`

## Manual Tests
After replicating the branch, to recreate my testing environment, you can either directly download the debug script, or manually create the changes.

### Download
`wget https://files.catbox.moe/v2vl7q.inc -O data/scripts/debug.inc`

### Manual Testing
* Modify `data/scripts/debug.inc` to the match given debug script
* Compile
* Start new game
* Exit truck and enter house
* Run Cheat Start
* Run desired scripts

## Verified Scenarios
All verified scenarios follow the flow described in Manual Testing.

### `removeallitem`  (Script 1 and Script 2)
https://github.com/user-attachments/assets/dafc2eb2-94c8-4e10-bfc8-e98841e2c472
### `getobjectxy` (Script 3)
https://github.com/user-attachments/assets/0f57d9b6-02e5-43ac-8c85-c5a9bc38e68f
### `checkobjectat`  (Script 4)
https://github.com/user-attachments/assets/0dc5a551-6c6d-4f37-8cff-e5533ff408ce
### `getseenmon` / `setseenmon` / `setcaughtmon`  (Script 5)
https://github.com/user-attachments/assets/38598cf0-6975-4963-8b81-d37c738279a8
### `checkspecies_auto`  (Script 7)
https://github.com/user-attachments/assets/507900cd-755b-43f2-abdf-435834e37b30
### `getobjectfacingdirection`  (Script 8)
https://github.com/user-attachments/assets/d70fd4d0-dca3-432a-9a7b-47ebf87a5ed6

# **People who collaborated with me in this PR**
These macros were written by @Pawkkie, @Lunos, and @ghoulslash and were originally part of [Useful Scripting Specials](<https://github.com/pret/pokeemerald/wiki/Useful-Scripting-Specials#checkforspecies>). Give them all the credit.
# Discord Contact Info
I am `pkmnsnfrn` on Discord.

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Does it make sense to add new specials? They make devs lives easier but a lot of them are also subjective meaning why would you add X but not Y?

**Comment by ghoulslash** [comment]
> Does it make sense to add new specials? They make devs lives easier but a lot of them are also subjective meaning why would you add X but not Y?

When script cmds take arguments I personally always prefer a callnative. With specials you have to use scripting vars for Args which has the (rare) potential to stomp on other values you've set previously in the script.

**Comment by AlexOn1ine** [comment]
> > Does it make sense to add new specials? They make devs lives easier but a lot of them are also subjective meaning why would you add X but not Y?
> 
> When script cmds take arguments I personally always prefer a callnative. With specials you have to use scripting vars for Args which has the (rare) potential to stomp on other values you've set previously in the script.

The same question applies. Would it make sense to add them? Just trying to figure out scope on this one

**Comment by pkmnsnfrn** [comment]
> Does it make sense to add new specials? They make devs lives easier but a lot of them are also subjective meaning why would you add X but not Y?
Is there a good reason not to add as many as we want? There's no scrolling list or menu with finite space. Space isn't an issue, we can switch to `callnative` if the special table is finite.

I was inspired to add this once [4189 was merged](https://github.com/rh-hideout/pokeemerald-expansion/pull/4189#pullrequestreview-1881946396). If we can add things that would improve quality of life, we should.

> When script cmds take arguments I personally always prefer a callnative. With specials you have to use scripting vars for Args which has the (rare) potential to stomp on other values you've set previously in the script.

~~ghoul two of these are yours and they're not callnative~~
If wrapping all of these in functions that use scriptcontext and callnative is blocking, I think that's fair and I'm happy to do it.

**Comment by AlexOn1ine** [comment]
> I was inspired to add this once https://github.com/rh-hideout/pokeemerald-expansion/pull/4189#pullrequestreview-1881946396. If we can add things that would improve quality of life, we should.

I'm generally wondering what is going to be useful for other projects because I would guess most of the time people write their own specific specials that only makes sense in their project. So trying to avoid the trap where we accept each random special basically answering the question why X but not Y.

**Comment by pkmnsnfrn** [comment]
I edited my post but I don't think you saw it in time. In any case, I _think_ we all agree that a command for a specific scenario in one person's game should not be merged. 

If you're looking for a guiding principle, I trust the (current) Senate enough to say:

> If another Senate member thinks "yeah, this could be generically useful"

then it should be merged.

~~it is mere coincidence that these were all written by current Senate members and therefore passes that bar~~

**Comment by Bassoonian** [comment]
I personally think `setmonball` doesn't qualify since it's a non-vanilla feature, I'm fine with the others. For `removeallitem` it may be useful to return (through `VAR_RESULT`) the amount of removed items for an easy addition of further logic. I also don't think the `checkspecies` variants need to exist; rather, one of the two could be set as the default with the other needing to be explicitly set through the argument.

**Comment by pkmnsnfrn** [comment]
@Bassoonian restating for clarity

merge criteria is

1. Remove `setmonball`
2. Set `VAR_RESULT` to the number of removed items from `removallitem`
3. Remove `checkspecies_auto` and make its behavior the default, with the ability to use `checkspecies_choose`
4. still waiting on an answer to `callnative` discussion from above

**Comment by pkmnsnfrn** [comment]
@ghoulslash - was your feedback saying "convert the specials to callnative"?

**Comment by pkmnsnfrn** [comment]
All feedback addressed.

**Review by ghoulslash — APPROVED** [review]

**Pull request merged**
