### PR TITLE
New move animations

### PR DESCRIPTION
**Pull request by Captain-Ford**
## Description
Upated anims for:

-Charge Beam
-Trick or Treat (didn't have one)
-Phantom Force (didn't have one)
-Psyshock
-Steamroller
-Acrobatics
-Head Smash
-Meteor Beam

## Images
Animations are the same as in the videos I post for them

## **Discord contact info**
thermobaricpunch

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
It's not compiling.

**Comment by AsparagusEduardo** [comment]
Please add the videos to the PR description.

**Comment by AsparagusEduardo** [comment]
Please solve conflicts and make sure that it compiles.

**Comment by AlexOn1ine** [comment]
> Please solve conflicts and make sure that it compiles.

I think they mentioned that they are taking a break for now and might PR at a later time. They also would prefer that nobody picks up on it.

**Comment by AsparagusEduardo** [comment]
> I think they mentioned that they are taking a break for now and might PR at a later time. They also would prefer that nobody picks up on it.

Ah ok, I didn't know that, and if they where on the server, they're not anymore ^^;

**Comment by AlexOn1ine** [comment]
Superseded by #3529

**Pull request closed without merging**
