### PR TITLE
FIx mummy and lingering aroma abilities

### PR DESCRIPTION
**Pull request by Sneed69**
## Issue(s) that this PR fixes
They straight up didn't work.

## **Discord contact info**
duke5614

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
can you parametrize both tests and leave a comment in the empty file that point to the test file with the tests?

**Comment by Sneed69** [comment]
Are you sure? I don't think I've seen any tests that parametrize strings.

**Comment by AlexOn1ine** [comment]
> Are you sure? I don't think I've seen any tests that parametrize strings.

@AsparagusEduardo what should be done here?

**Comment by AsparagusEduardo** [comment]
> @AsparagusEduardo what should be done here?

The if/else added should be good enough

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
