### PR TITLE
Refactor trainer classes

### PR DESCRIPTION
**Pull request by fdeblasio**
## Description
Refactors the trainer classes in a gTrainerClasses to make editing easier

## **Discord contact info**
Frankfurter0

### CODE REVIEW

**Comment by LOuroboros** [comment]
Isn't there a way to make this more compact and to avoid having to create an entirely new file?

Something like this, for example?

```js
struct TrainerNameMoneyBall
{
    const u8 *name;
    u8 moneyMultiplier;
    u16 ballId;
};

const struct TrainerNameMoneyBall gTrainerNameMoneyBallTable[] =
{
    [TRAINER_CLASS_TEAM_AQUA]   = {COMPOUND_STRING("TEAM AQUA"), 5, ITEM_POKE_BALL},
    [TRAINER_CLASS_AQUA_LEADER] = {COMPOUND_STRING("AQUA LEADER"), 20, ITEM_MASTER_BALL),
    [...]
};
```

**Comment by fdeblasio** [comment]
Yeah I was going to focus on compacting it once I got the Poke Balls in. What file were you thinking of it going in to avoid making a whole new file?

**Comment by LOuroboros** [comment]
> Yeah I was going to focus on compacting it once I got the Poke Balls in. What file were you thinking of it going in to avoid making a whole new file?

Same file where the original arrays are located, `src/battle_main.c`.

**Comment by AlexOn1ine** [comment]
@fdeblasio I know it's likely very trivial but could you still add a little tutorial at the top?

**Review by AlexOn1ine — APPROVED** [review]

**Pull request merged**
