### PR TITLE
#3207 TSpikes Pecha Fix

### LINKED ISSUE #3207: Toxic Spikes don't function properly after a Pecha Berry activation.
### Description

Toxic Spikes seem to bug out if a Pokémon has its poison healed by a Pecha Berry on switch-in.

Once you've been healed by the Pecha Berry, if you switch in any other Pokémon afterwards, Toxic Spikes will not poison that Pokémon. (Judging by the nature of the bug, I'd assume an item like Lum Berry would work too.)

For clarity, here's a scenario where this bug would occur:

```
Turn 1:
* Opponent sets up 1 layer of Toxic Spikes

Turn 2:
* Player switches in Pokémon holding Pecha Berry.
* Pokémon gets poisoned but is immediately healed by Pecha Berry.

Turn 3:
* Player switches in Pokémon holding nothing.
* Pokémon does not get poisoned.

Turn 4:
* Player switches to another Pokémon holding nothing.
* Pokémon gets poisoned by the Toxic Spikes like normal.
```

Here's a video of this bug in action:

https://github.com/rh-hideout/pokeemerald-expansion/assets/77281351/11f1847c-5c26-4393-963a-7ab9841317c3

### Version

1.5.1 (Default)

### Upcoming Version

_No response_

### Discord contact info

sarnnn

### PR DESCRIPTION
**Pull request by Pawkkie**
Fixes #3207, involving status cure berries blocking an instance of hazard damage and hazard status being applied.

Changes the ItemBattleEffects function to use the same pattern as ItemEffectMoveEnd when handling HOLD_EFFECT_CURE_XYZ and berries. This cleanly fixes this issue, but I'm not super familiar with this section of code to be confident that this is an appropriate solution. Feel free to dismiss outright if not.

I updated all of the status cure berries with this change rather than just Pecha and Lum in case any downstream users might have added a TSpikes that burns etc.

## Video
2nd Poochyena has a Pecha Berry, 4th Poochyena has a Lum Berry. Both behave as expected.

https://github.com/rh-hideout/pokeemerald-expansion/assets/61265402/ffca8d15-4bf3-4e39-9f87-3175c26c2770

## Issue(s) that this PR fixes
Fixes #3207 

## **Discord contact info**
Pawkkie

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Note for the reviewer:
I would recommend adding tests that check that the battlers can be statused again once the corresponding status-healing items trigger. This way, we can prevent these specific regressions.

**Comment by DizzyEggg** [comment]
As Asparagus said,  this fix should have the tests included.

**Comment by Pawkkie** [comment]
Unfortunately writing these tests is beyond the scope of the time I'm willing to commit to this PR, I've not made them before and while I'm sure the syntax isn't that bad to learn I'm personally not willing to spend the time doing so and then also spend the time figuring out and testing that specific implementation.

Just fixed this in my own project and figured I'd share it. Feel free to close this PR if that's a required feature for bug fix acceptable, I'll keep a branch available on my GitHub we can direct people to if anyone wants it in the meantime :)

**Comment by AlexOn1ine** [comment]
This test fails with this PR.
```
SINGLE_BATTLE_TEST("Hold effect cures status if a pokemon enters a battle")
{
    u16 status;
    PARAMETRIZE{ status = STATUS1_BURN; }
    PARAMETRIZE{ status = STATUS1_FREEZE; }
    PARAMETRIZE{ status = STATUS1_PARALYSIS; }
    PARAMETRIZE{ status = STATUS1_POISON; }
    PARAMETRIZE{ status = STATUS1_TOXIC_POISON; }
    PARAMETRIZE{ status = STATUS1_SLEEP; }

    GIVEN {
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_WOBBUFFET) { Status1(status); Item(ITEM_LUM_BERRY); }
    } WHEN {
        TURN { }
    } SCENE {
        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_HELD_ITEM_EFFECT, opponent);
    }
}
```
The berries are supposed to trigger when a pokemon with a status condition enters the battle.

**Comment by Pawkkie** [comment]
This PR can probably be closed unless anyone has any other ideas. Alex and I did some chatting this morning, and while this fixes the interaction between status cure berries and avoiding hazard damage, it introduces an issue where if you have a pre-status'd mon with a status cure berry as the first mon that enters during a battle, its status won't be cured immediately, which it should be.

Neither of us are sure where to go from here, this bug is weird, but he'll PR his tests separately :)

**Comment by AsparagusEduardo** [comment]
Replaced by #3316

**Pull request closed without merging**
