### PR TITLE
Misc pokemon sprite fixes

### PR DESCRIPTION
**Pull request by Cafeei**
Some tweaks and fixes to Pokemon sprites

## Description
- Spiky Eared Pichu - fixed not using its second sprite animation + added asymmetric follower
- Pincurchin - added glow to its spikes on its second sprite 
- Maractus - fixed two miscolored spikes on its back sprite
- Honedge - fixed off-centered blade on its back and bended blade on its front + made its grin more pronounced on the second frame + changed color of its sheath (it was a kinda nasty color)
- Duraludon - incorrect follower positioning
- Diggersby - cleaned up its back sprite

## Images
pichu se pichu se
image -> image
image -> image
pincurchin
image image -> image image
duraludon -> duraludon

### CODE REVIEW

**Comment by kittenchilly** [comment]
You think you could fix the missing pixel on Ariados in this pr?

**Comment by Cafeei** [comment]
> You think you could fix the missing pixel on Ariados in this pr?

Done

**Comment by Cafeei** [comment]
It builds fine on my end idk

**Comment by AsparagusEduardo** [comment]
May be an issue on master

**Comment by hedara90** [comment]
Yea, `enumeration value 'VARIOUS_EERIE_SPELL_PP_REDUCE' not handled in switch [-Werror=switch]`

**Comment by AsparagusEduardo** [comment]
Ah, the Sheer Force PR wasn't updated to the latest master, so it didn't get the warning of unused VARIOUS

**Comment by AsparagusEduardo** [comment]
It's been fixed. Please merge with master so that CI can pass

**Review by hedara90 — APPROVED** [review]

**Pull request merged**
