### PR TITLE
Mirror Armor

### PR DESCRIPTION
**Pull request by ghoulslash**
Adds the mirror armor ability functionality

mirror_armor_intimidate

mirror_armor_stickyweb
mirror_armor

Test cases and notes:
- growl ------> WORKS, NO GROWL ANIMATION
- gooey ------> GOOD		
- bubblebeam move effect ------> GOOD
- sticky web ------> GOOD
- intimidate ------> GOOD
- growl, attacker at -6 ------> MIRROR ARMOR TRIGGER, PRINTS STAT WONT GO LOWER
- growl, target at -6 ------> MIRROR ARMOR BOUNCES

### CODE REVIEW

**Comment by BuffelSaft** [comment]
There are some issues with the wrong stat change being bounced back in doubles after a stat boosting move is used:
Mirror armor bug
Everything in the gif except Mightyena has Mirror Armor.

**Comment by ghoulslash** [comment]
I've fixed the stat id issue, and also handled blocking reflected stat changes e.g. corphish + hyper cutter:

mirror_armor_fix

ready for re-review

**Comment by BuffelSaft** [comment]
That fix is working, but now Clear Body isn't blocking the stat drop from Icy Wind:
Icy Wind Clear Body
Clear Body is working properly in a clean BE branch.

Also there's a "feature" edge case that's not working. According to Bulbapedia "If the Pokémon with this Ability is affected by Sticky Web, the effect is reflected back to the Pokémon which set it up. If Pokémon which set up Sticky Web is not on the field, no Pokémon have their Speed lowered."

**Comment by ghoulslash** [comment]
Fixed both clear body and the sticky web targeting with mirror armor.
ready for another review

**Comment by BuffelSaft** [comment]
Can confirm those are both fixed. I've noticed Big Pecks isn't blocking reflected defense drops from Screech, but it turns out that Big Pecks is just broken so that can be its own issue.

I've also tested reflected stat drops vs Contrary, Magic Bounce and Mirror Armor and those are all working fine, so I think this is good to go. We might find some bizarre edge case in future, but for now I've tested everything I can think of in singles, doubles and on both sides of the field.

**Review by BuffelSaft — APPROVED** [review]

**Pull request merged**
