### PR TITLE
Implement Desolate Land, Primordial Sea and Delta Stream

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
This PR implements the abilities of Primal Groudon, Primal Kyogre and Mega Rayquaza into the battle_engine.

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by LOuroboros** [comment]
For `STRINGID_ATTACKWEAKENEDBSTRONGWINDS` I could also just end the string with a `\p`. That way it would remain on screen until the Player pressed the A or B buttons to proceed with the turn normally. It just wouldn't be accurate since in the official games, the string is printed on screen for a certain specific amount of time.
All in all, it would still be better than how it's handled right now, where `STRINGID_ATTACKWEAKENEDBSTRONGWINDS` is printed immediately after `attackstring` *(the function that makes the game print the "[Pokémon] used [move]!" string)* kicks in.
I'll leave the decision to whoever reviews this in 2022.

**Comment by BuffelSaft** [comment]
Seems there's a problem with Desolate Land's weather deactivating when the opponent is switched out:
drought

**Comment by LOuroboros** [comment]
Ready for re-review :eyes:

**Comment by BuffelSaft** [comment]
The switchout issue is fixed, I've tested the following:
- Multiple primal weather mons on the field: weather stays active if one switches out
- One primal weather mon on the field: weather stops when it switches out

There's a bug with Delta Stream though:
delta stream
Torchic here is Fire/Flying and gets hit by a super effective water attack, but that shouldn't be weakened by Delta Stream. It should only weaken moves that are super effective against the flying type - the secondary type on any flying types isn't accounted for.

Also, a couple of details from testing in USUM:
- Other weather abilities (drought, drizzle, sand stream, snow warning) should still try to activate and show the ability pop up, but they then fail with the same string as rain dance etc. Looks like this can be handled in the battle scripts for these abilities  the same way you've done it for the weather moves.
- Delta Stream's "strong winds weakened the attack!" message should be shown after the opponent's move is announced, not before.
E.g. "Heatran used Ice Punch!" "The mysterious air current weakened the attack!" instead of "The mysterious air current weakened the attack!" "Kyogre used Water Pulse!"

Test clip from USUM: https://streamable.com/76ua17

**Comment by LOuroboros** [comment]
Ready for re-re-review 👀

**Comment by BuffelSaft** [comment]
Re-tested and found some more issues:
- The ability popup activates when the strong winds weaken an attack, but it shouldn't
- Move effectiveness isn't displayed correctly when the strong winds weaken an attack. E.g. if a normal/flying type is hit by a rock attack, it shouldn't say "it's super effective!" if delta stream is active
- Drought doesn't try to activate when delta stream is active
- If a mon with delta stream is switched out using shift mode, the strong winds aren't cleared when it leaves the field

Gif showing all of the above:
shiftmode

**Comment by LOuroboros** [comment]
Ready for re-re-re-review 👀

**Comment by LOuroboros** [comment]
Okay *NOW* it's actually ready for a re-re-re-review 👀

**Comment by LOuroboros** [comment]
I was kidding when I said it was ready before, but it is ready now. Hopefully :eyes:

**Comment by LOuroboros** [comment]
I'm ready to see another review bring out more bugs!

And by that, I mean that I'm ready for the re-re-re-re-re-re-re-re-re-re-review :eyes:

**Comment by LOuroboros** [comment]
> If the primal weather ability is lost via Gastro Acid, Worry Seed, Simple Beam, etc. the weather should also be cleared.

Is there any other move effect or ability I should know about in that "etc"? :eyes:

If not, I think I'm good to go.

**Comment by LOuroboros** [comment]
Ready for re-re-re-re-re-review 👀

**Pull request merged**
