### PR TITLE
Added Mind's Eye, with tests + Keen Eye tests

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Tests:
- Mind's Eye allows to hit Ghost-type Pokémon with Normal- and Fighting-type moves
- Mind's Eye doesn't bypass a Ghost-type's Wonder Guard (based of Smogon's NatDex implementation)
- Mind's Eye prevents accuracy from being lowered
- Mind's Eye ignores target's evasion
- Mold Breaker-type abilities bypass Minds Eye's accuracy lowering prevention

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Review by DizzyEggg — COMMENTED** [review]
How comfortable do you feel to write an AI test for Minds Eye? :D

**Comment by AsparagusEduardo** [comment]
> How comfortable do you feel to write an AI test for Minds Eye? :D

I can take the chance to learn :)

**Comment by DizzyEggg** [comment]
> > How comfortable do you feel to write an AI test for Minds Eye? :D
> 
> I can take the chance to learn :)

You could use the Contrary one as a blueprint 👀

**Comment by Bassoonian** [comment]
Superseded by #3782

**Pull request closed without merging**
