### PR TITLE
Updated the Master branch's README.md

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
:eyes:

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
We should update the readme in general to reflect the change in direction to have master as the only active branch. I posted on discord an incomplete draft that could be used.

**Comment by LOuroboros** [comment]
Makes sense. I guess it's pointless to update the links when the branches will be deleted eventually. I'll leave it to you then.

**Comment by AsparagusEduardo** [comment]
If you want to do it go ahead, my plate is a bit full at the moment :eyes:

**Comment by LOuroboros** [comment]
> If you want to do it go ahead, my plate is a bit full at the moment 👀

Got it. I'll think about what can I add, if there's anything, and then push another commit to this branch then.

**Comment by AsparagusEduardo** [comment]
Here, you can use this as a reference, if not that's ok.
https://discord.com/channels/419213663107416084/419213926245335041/1015449926798426133

**Comment by LOuroboros** [comment]
Ready for review, I guess :eyes:

**Review by AsparagusEduardo — APPROVED** [review]

**Pull request merged**
