### PR TITLE
Pret merge 07.03.2024

### PR DESCRIPTION
**Pull request by DizzyEggg**
Pret merge 07.03.2024

- SHA1 before merge: 2C956078BAF6F46A96C7A673E1EECAAD002B8485
- SHA1 after    merge: 2C956078BAF6F46A96C7A673E1EECAAD002B8485

### CODE REVIEW

**Comment by Bassoonian** [comment]
Asking so Edu doesn't have to: what's the reason the hash changes?

**Comment by DizzyEggg** [comment]
> Asking so Edu doesn't have to: what's the reason the hash changes?

No idea tbh, maybe I made a mistake 🤔

**Comment by AsparagusEduardo** [comment]
> No idea tbh, maybe I made a mistake 🤔

Could it be the `gHeap` alignment that it wasn't before? 🤔

**Comment by DizzyEggg** [comment]
> > No idea tbh, maybe I made a mistake 🤔
> 
> Could it be the `gHeap` alignment that it wasn't before? 🤔

I don't think so, if the heap wasn't aligned the game would be broken.

**Comment by DizzyEggg** [comment]
Update: I corrected the SHA1. It's the same before and after merge. 
I think I had a pokeemerald.gba from a different branch before and mistakenly thought it was from upcoming.

**Review by AsparagusEduardo — APPROVED** [review]
> Update: I corrected the SHA1. It's the same before and after merge. I think I had a pokeemerald.gba from a different branch before and mistakenly thought it was from upcoming.

Phew! xD

**Pull request merged**
