### PR TITLE
Organized tests into subfolders

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
image image

Also, split into files:
- Primal Weather
  - Desolate Land
  - Primordial Sea
- Powder Moves
  - Overcoat
  - Safety Goggles
  - Grass types
- Form change
  - Battle Switch
  - Begin Battle
  - Faint
- Status1
  - Bad Poison
  - Burn
  - Freeze
  - Frostbite
  - Paralysis
  - Poison
  - Sleep

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by mrgriffin** [comment]
idk if I like moving the header files from `test` to `include/test`, but if you do that, you don't need `-I test` in the [Makefile](https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/Makefile#L435).

**Comment by AsparagusEduardo** [comment]
> idk if I like moving the header files from `test` to `include/test`
I needed to do that otherwise it wouldn't compile D:

**Comment by AsparagusEduardo** [comment]
Conflict solved, moved new tests to their respective folders.

Ready for re-review.

**Comment by AsparagusEduardo** [comment]
Solved conflicts and rebased to master

**Review by mrgriffin — COMMENTED** [review]
Looks good to me, but I have one question:
- How come we're not `#include "global.h"`ing in some of the tests anymore?

**Comment by AsparagusEduardo** [comment]
> * How come we're not `#include "global.h"`ing in some of the tests anymore?

It's included in `tests/battle.h` :) 
I can make it so that all tests have only this one include or that they still have globah, whatever you prefer.

**Comment by mrgriffin** [comment]
> It's included in `tests/battle.h` :)
> I can make it so that all tests have only this one include or that they still have globah, whatever you prefer.

Ah I see! Yeah, I think I would prefer to keep the include of `global.h` in all the files to be consistent with regular sources, but I'll admit I don't have any real argument for doing so :)

**Comment by AsparagusEduardo** [comment]
> Ah I see! Yeah, I think I would prefer to keep the include of `global.h` in all the files to be consistent with regular sources, but I'll admit I don't have any real argument for doing so :)

Sure, I have no issue keeping global.h there, so I'll re-add it.

**Review by mrgriffin — APPROVED** [review]

**Pull request merged**
