### PR TITLE
Ported Gen 5 & 6 mon animations from Inclement Emerald + added most missing Gen 7 form animations

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Ported mon animations from Inclement Emerald (originally by Mr. Dollsteak) and also added most animations for Gen 7 forms. Only missing Oricorio, Lycanroc, Wishiwashi and Necrozma Forms

## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by DizzyEggg** [comment]
I see this also changes the existing animations. Is that fine with everyone?

**Comment by BuffelSaft** [comment]
> I see this also changes the existing animations. Is that fine with everyone?
Super slow reply here, but it's fine with me. A lot of the existing animations look pretty bad with the new sprites (e.g. flappy arms Gardevoir). IMO Mr. Dollsteak's animations are really well done, they're a huge upgrade over the current ones.

**Comment by LOuroboros** [comment]
A few examples in a gif or a vid to illustraste would probably make it easier to decide, maybe? :eyes:

**Comment by AsparagusEduardo** [comment]
> A few examples in a gif or a vid to illustraste would probably make it easier to decide, maybe? 👀

Alright, I'll do them

**Comment by DizzyEggg** [comment]
> Alright, I'll do them

Waiting 😂

**Comment by AsparagusEduardo** [comment]
> > Alright, I'll do them
> 
> Waiting joy

Right! :joy:

**Comment by AsparagusEduardo** [comment]
Old vs New (Gen 1-3)
006_old 006new
045_old 045new
086_old 086new
125_old 125new
153_old 153new
154_old 154new
157_old 157new
166_old 166new
180_old 180new
182_old 182new
183_old 183new
184_old 184new
191_old 191new
202_old 202new
203_old 203new
208_old 208new
214_old 214new
215_old 215new
223_old 223new
225_old 225new
227_old 227new
228_old 228new
232_old 232new
238_old 238new
239_old 239new
240_old 240new
242_old 242new
243_old 243new
248_old 248new
249_old 249new
282_old 282new

**Comment by LOuroboros** [comment]
> 

Most of them look nice, but a few of the new ones look kinda weird or worse than the old ones imo. Namely: Electabuzz, Meganium, Azumarill, Raikou and Lugia.

**Comment by AsparagusEduardo** [comment]
Gen 4 (pt 1, for some reason I can't upload more files)

Old vs New
387_old 387new
388_old 388new
389_old 389new
390_old 390new
391_old 391new
392_old 392new
394_old 394new
395_old 395new
396_old 396new
397_old 397new
398_old 398new
399_old 399new
400_old 400new
401_old 401new
402_old 402new
403_old 403new
404_old 404new

**Comment by AsparagusEduardo** [comment]
Pt 2
405_old 405new
406_old 406new
407_old 407new
408_old 408new
409_old 409new
410_old 410new
411_old 411new
412_old 412new
413_old 413new
416_old 416new
417_old 417new
418_old 418new
419_old 419new
420_old 420new
421_old 421new
422_old 422new
423_old 423new
424_old 424new
425_old 425new
426_old 426new
427_old 427new
428_old 428new
429_old 429new
430_old 430new
431_old 431new
432_old 432new
433_old 433new
434_old 434new
435_old 435new
436_old 436new
437_old 437new
438_old 438new
439_old 439new
440_old 440new
441_old 441new
442_old 442new
443_old 443new
444_old 444new
445_old 445new
446_old 446new
447_old 447new
448_old 448new
449_old 449new
450_old 450new
451_old 451new
452_old 452new
453_old 453new
454_old 454new
455_old 455new

**Comment by AsparagusEduardo** [comment]
Final part of Gen 4.

I'm not posting Gen 5-7 as those have default animations and can be viewed by checking out the PR.

456_old 456new
457_old 457new
458_old 458new
459_old 459new
460_old 460new
461_old 461new
462_old 462new
463_old 463new
464_old 464new
465_old 465new
466_old 466new
468_old 468new
469_old 469new
470_old 470new
471_old 471new
472_old 472new
473_old 473new
474_old 474new
475_old 475new
476_old 476new
477_old 477new
478_old 478new
479_fan_old 479_fannew
479_frost_old 479_frostnew
479_heat_old 479_heatnew
479_mow_old 479_mownew
479_normal_old 479_normalnew
479_wash_old 479_washnew
480_old 480new
481_old 481new
482_old 482new
483_old 483new
484_old 484new
485_old 485new
486_old 486new
487_old 487new
488_old 488new
489_old 489new
490_old 490new
491_old 491new
492_old 492new
493_old 493new

**Comment by AsparagusEduardo** [comment]
Fixed conflicts.

**Pull request merged**
