### PR TITLE
Simplify HP Logic

### PR DESCRIPTION
**Pull request by RSilicon**
Simplify the HP logic
## Description

Fun fact: By setting maxHP for Shedinja earlier in the code, we do not need to worry about it for calculating HP later down the line.

What only matters is: currentHP only increases if the maxHP is greater than previous maxHP (currentHP can never go down), and currentHP is always at most maxHP.

## **Discord contact info**

RSilicon

### CODE REVIEW

**Comment by hedara90** [comment]
This change makes it so that fainted pokemon that evolve are revived with HP equal to `newMaxHP - oldMaxHP`
This is not the current behavior. It should stay fainted.

**Comment by RSilicon** [comment]
> This change makes it so that fainted pokemon that evolve are revived with HP equal to `newMaxHP - oldMaxHP` This is not the current behavior. It should stay fainted.

Fixed

**Comment by hedara90** [comment]
Did you test this at all before pushing changes?
Because right now 1.9k tests are failing.
Please don't push changes before `make check` passes locally.

**Comment by AlexOn1ine** [comment]
please don't force push after the review began

**Comment by RSilicon** [comment]
> Did you test this at all before pushing changes? Because right now 1.9k tests are failing. Please don't push changes before `make check` passes locally.

Yes it is only failing on here, not locally.

**Comment by AlexOn1ine** [comment]
I've asked you not to force push. Now we don't know what you've changed

**Comment by AlexOn1ine** [comment]
all of the tests are still failing.

**Comment by hedara90** [comment]
It's still failing 1.9k tests.
Can you please stop pushing things that don't work.
20240918_19h44m07s_grim

**Comment by hedara90** [comment]
Now the code is just back to this point:

> This change makes it so that fainted pokemon that evolve are revived with HP equal to `newMaxHP - oldMaxHP`
> This is not the current behavior. It should stay fainted.

This is not simplifying anything unless every single edge case that the previous code handles is accounted for.

**Comment by RSilicon** [comment]
> Now the code is just back to this point:
> 
> > This change makes it so that fainted pokemon that evolve are revived with HP equal to `newMaxHP - oldMaxHP`
> > This is not the current behavior. It should stay fainted.
> 
> This is not simplifying anything unless every single edge case that the previous code handles is accounted for.

Answer: we only need to not return at 0 if exp is updated it seems. Give me a sec,I was just ensuring that I broke the tests.

**Comment by RSilicon** [comment]
So, is oldMaxHP being tested for 0 just a test to see if we should update the currentHP even if it was 0?

If true, then this will work for now, as a proper fix which will be much more involved and require feedback from the community at large would be refactoring the HP update code to be its own function that takes a boolean parameter that controls whether or not we want to adjust the currentHP even if 0 or bail at currentHP being 0.

**Comment by RSilicon** [comment]
But as of now, this works.

> So, is oldMaxHP being tested for 0 just a test to see if we should update the currentHP even if it was 0?
> 
> If true, then this will work for now, as a proper fix which will be much more involved and require feedback from the community at large would be refactoring the HP update code to be its own function that takes a boolean parameter that controls whether or not we want to adjust the currentHP even if 0 or bail at currentHP being 0.

To add, the only place where this boolean would be false would be when calling this after updating the exp of a pokemon.

**Comment by hedara90** [comment]
Can you stop force pushing every single time? Please.
It's been asked 2 times already.

**Comment by RSilicon** [comment]
> Can you stop force pushing every single time? Please. It's been asked 2 times already.

Yeah. I will stop, now.

**Comment by AsparagusEduardo** [comment]
I've already warned you in previous PRs that if you kept being uncooperative, we will no longer accepting your PRs.

***This is your final warning.***

**Review by hedara90 — CHANGES_REQUESTED** [review]
This change should target `upcoming` instead of `master`. Please re-target it to `upcoming`.

Assuming that everything still works on `upcoming` it should be good to go.

**Comment by RSilicon** [comment]
Rebase and force push required due to conflicts when changing base.

**Comment by RSilicon** [comment]
Closing and reopening since git doesn't want to cooperate as I fix this branch. I will make a new one. Apologies.

**Comment by RSilicon** [comment]
See: https://github.com/rh-hideout/pokeemerald-expansion/pull/5403

**Pull request closed without merging**
