### PR TITLE
Convert vanilla trainer data to only use the full custom trainer mon struct

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
To convert existing IV data for the vanilla structs, use the resulting value of `IV * 31 / 255` (rounded down) to convert the values to the current structure.
e.g. 100 becomes `TRAINER_PARTY_IVS(12, 12, 12, 12, 12, 12)`.

`TrainerMonCustomized` was also renamed to `TrainerMon` and `EVERYTHING_CUSTOMIZED` to `TRAINER_PARTY`.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by DizzyEggg** [comment]
I guess this is gonna break trainers in everyone's hacks. Are we okay with it?

**Comment by AsparagusEduardo** [comment]
> I guess this is gonna break trainers in everyone's hacks. Are we okay with it?

We already gave the notice in 1.5.0 that we would be making this change, a bit of a month ago, so they would have time to port their trainers to the customized version. The only thing that needs to be converted is the iv field, which I gave instructions on the description to how to do it.

We *can* delay it for later once 1.6 is getting closer if needed.
I want to know if review approvals are kept when switching to draft. If so, we could do that :P

**Review by DizzyEggg — APPROVED** [review]

**Comment by AsparagusEduardo** [comment]
Awesome, they do :)

**Comment by mrgriffin** [comment]
> We already gave the notice in 1.5.0 that we would be making this change, a bit of a month ago

Related to the "who builds with modern?" question, I'd love to know how frequently people update, and/or how frequently people are okay with us removing deprecated things :)

~Shame we haven't already switched to modern, then we could use [`__attribute__((deprecated))`](https://godbolt.org/z/o9oe1P5jE) to really draw attention during builds.~

**Comment by AsparagusEduardo** [comment]
Since Egg had already approved the PR and no further changes have been made to it, I'm merging it now.

**Comment by mrgriffin** [comment]
idk how hard it would be, but if there's some way to write a `sed` script, or whatever to convert the old party formats to the new one that would be an awesome thing to include in the next release too :)

**Pull request merged**
