### PR TITLE
A few new gen 9 move animations

### PR DESCRIPTION
**Pull request by AlexOn1ine**
A couple New gen9 animations made by @ZnogyroP with improvment suggestions by @ghoulslash and adjustments by me.
Also replaced old Draco Meteor (I am not sure who made the old anim but I hope the replacement is okay by everyone) animation with the CFRU one, Credits to @Skeli789

Raging Bull:

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/4a8cee48-cdd3-457a-870c-aea433d52f97

Gigaton Hammer:

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/f328491f-8daa-4466-9172-cf5394fc7a72

Ice Spinner:

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/86b6dad8-dc45-43fb-9e76-803dd7851392

Aqua Cutter:

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/7dc1871c-8008-4dc1-91b4-3a269886ed79

Made some minor adjustments to the Double Shock anim I previously PR'd. I wasn't happy with it and I think it's marginally better now:

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/3115d7fb-5b4e-4674-95d8-7192c7526ac5

### CODE REVIEW

**Comment by ghoulslash** [comment]
A couple ideas (having not seen the actual GF anims so maybe they will be less true to those):
1. Aqua Cutter slash should probably be blue-ish and maybe have crabhammer bubbles after/during instead of the waterfall. The blue slash could either be from false swipe or just using AnimTask_BlendParticle
2. Ice spinner might look better if the ice punch crystal swirl or a crystal swirl using fire spin's callback envelops the attacker as it rapid spins away (either instead or in addition to the bg)
3. raging bull should maybe have the wind-up from double edge or other slide-back movement

**Comment by AlexOn1ine** [comment]
> A couple ideas (having not seen the actual GF anims so maybe they will be less true to those):
> 
>     1. Aqua Cutter slash should probably be blue-ish and maybe have crabhammer bubbles after/during instead of the waterfall. The blue slash could either be from false swipe or just using AnimTask_BlendParticle
> 
>     2. Ice spinner might look better if the ice punch crystal swirl or a crystal swirl using fire spin's callback envelops the attacker as it rapid spins away (either instead or in addition to the bg)
> 
>     3. raging bull should maybe have the wind-up from double edge or other slide-back movement

Good suggestions! I'll take a look.

**Comment by ghoulslash** [comment]
> 
> Good suggestions! I'll take a look.

Sounds good just let me know if you need help with anything!

**Comment by AlexOn1ine** [comment]
Suggestions applied: 

I've moved the BG to appear slightly later because of the ice crystals but open to removing it altogether. 

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/104a3573-33ee-445c-95a5-55917062cdc6

As suggested I used crabhammer at the end and I couldn't get it to work nicely with `AnimTask_BlendParticle` so I used False Swipe anim.

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/5895a797-ed7b-4b8a-b02f-a96e5dcaaae1

Added the wind-up from Double Edge and a BG to make it more distinct  

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/ec5fcea9-99c2-4dff-9139-e09a1fe1789b

Also I've ported the Draco Meteor anim (single commit) but I have trouble loading the GFX. 
pokeemerald-18
For comparison:
image

**Comment by AlexOn1ine** [comment]
Ready for re-review!

Was able to figure out the problem with Draco Meteor. I don't know who made the old animation but I hope it's okay if I replace it.

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/5761225b-40df-4069-b618-1e44665c4a10

I'm totally fine with removing the BG from Ice Spinner

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/3b99ee1a-c837-4cd4-8d74-2edb4ec4ad86

Removed Aqua Cutter slices. 

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/0f1a1198-1f83-4ae2-a9a1-4dad59ed0795

**Review by ghoulslash — APPROVED** [review]

**Pull request merged**
