### PR TITLE
Add the Strange Ball

### PR DESCRIPTION
**Pull request by kittenchilly**
## Description
Adds the Strange Ball.
Its an standalone item and also works if the pokeball a mon is in is invalid, it loads it as the strange ball.
Due to how adding new poke balls works, this will break saves and is thus a draft until safe save migration is implemented.
If anyone thinks they can make a better sprites for it (especially the thrown sprite), they are welcome to do so. 

## Images
pokeemerald-0

## **Discord contact info**
kittenchilly

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
I recommend implementing the Strange Ball as a failsafe instead of an actual item.

**Comment by kittenchilly** [comment]
> I recommend implementing the Strange Ball as a failsafe instead of an actual item.

It is an actual item in every game that includes it, so it should be an actual item here. This also allows people to give it out if they want. If it was a failsafe there'll literally be nowhere it can appear.

**Comment by AsparagusEduardo** [comment]
> It is an actual item in every game that includes it, so it should be an actual item here. This also allows people to give it out if they want. If it was a failsafe there'll literally be nowhere it can appear.

In [Pokémon Brilliant Diamond and Shining Pearl](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Brilliant_Diamond_and_Shining_Pearl), [Pokémon Legends: Arceus](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Legends:_Arceus), and [Pokémon Scarlet and Violet](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Scarlet_and_Violet), Pokémon caught in Poké Balls that do not exist in that game instead display a Strange Ball as their Poké Ball.

In [Pokémon Legends: Arceus](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Legends:_Arceus), Pokémon caught in any Poké Ball other than one of the Hisuian Poké Balls are displayed as being caught in a Strange Ball.
In [Pokémon Brilliant Diamond and Shining Pearl](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Brilliant_Diamond_and_Shining_Pearl) and [Pokémon Scarlet and Violet](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Scarlet_and_Violet), Pokémon caught in any Hisuian Poké Balls are displayed as being caught in a Strange Ball.

The Strange Ball is only defined as an [item](https://bulbapedia.bulbagarden.net/wiki/Item) in Legends: Arceus, Scarlet, and Violet. **In Brilliant Diamond and Shining Pearl, it does not exist as an actual item, only as a graphic displayed for Pokémon with a ball ID value that doesn't match any ball found in the game.**

**Comment by kittenchilly** [comment]
> > It is an actual item in every game that includes it, so it should be an actual item here. This also allows people to give it out if they want. If it was a failsafe there'll literally be nowhere it can appear.
> 
> In [Pokémon Brilliant Diamond and Shining Pearl](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Brilliant_Diamond_and_Shining_Pearl), [Pokémon Legends: Arceus](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Legends:_Arceus), and [Pokémon Scarlet and Violet](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Scarlet_and_Violet), Pokémon caught in Poké Balls that do not exist in that game instead display a Strange Ball as their Poké Ball.
> 
> In [Pokémon Legends: Arceus](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Legends:_Arceus), Pokémon caught in any Poké Ball other than one of the Hisuian Poké Balls are displayed as being caught in a Strange Ball. In [Pokémon Brilliant Diamond and Shining Pearl](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Brilliant_Diamond_and_Shining_Pearl) and [Pokémon Scarlet and Violet](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Scarlet_and_Violet), Pokémon caught in any Hisuian Poké Balls are displayed as being caught in a Strange Ball.
> 
> The Strange Ball is only defined as an [item](https://bulbapedia.bulbagarden.net/wiki/Item) in Legends: Arceus, Scarlet, and Violet. **In Brilliant Diamond and Shining Pearl, it does not exist as an actual item, only as a graphic displayed for Pokémon with a ball ID value that doesn't match any ball found in the game.**

I forgot about BDSP, but still. That doesn't change that the latest games do have it as an item, and I think making it an actual item makes the most sense so hackers can actually use it if they want, and not only if its a failsafe (which should literally never occur in our case)

**Comment by AsparagusEduardo** [comment]
> I forgot about BDSP, but still. That doesn't change that the latest games do have it as an item, and I think making it an actual item makes the most sense so hackers can actually use it if they want, and not only if its a failsafe (which should literally never occur in our case)

Keep the item, but still make it a failsafe. It would happen if someone adds a Pokéball in one hack and the other doesn't have it.

**Comment by kittenchilly** [comment]
> > I forgot about BDSP, but still. That doesn't change that the latest games do have it as an item, and I think making it an actual item makes the most sense so hackers can actually use it if they want, and not only if its a failsafe (which should literally never occur in our case)
> 
> Keep the item, but still make it a failsafe. It would happen if someone adds a Pokéball in one hack and the other doesn't have it.

Right. I actually forgot to do that since I was so caught up in sprites lol.

**Comment by AsparagusEduardo** [comment]
BTW, if someone decouples Pokéballs from the required order, you could add this to the end of the item list for now.

**Comment by kittenchilly** [comment]
Closing for now since it doesn't seem like this'll go anywhere for a while.

**Comment by ShinyDragonHunter** [comment]
strange
Slight edit of the ball graphics so it looks more gen 3

**Pull request closed without merging**
