### PR TITLE
Implemented Ice Face

### LINKED ISSUE #1031: ABILITY_ICE_FACE

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Closes #1031.

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by BuffelSaft** [comment]
Need to add defines for Eiscue to the list of species in the BE, should fix the build issue.

**Comment by BuffelSaft** [comment]
Conflicts need resolving, then I can start testing

**Comment by LOuroboros** [comment]
> 
> 
> Conflicts need resolving, then I can start testing

Done :eyes:

**Comment by BuffelSaft** [comment]
Looks like #1817 introduced more conflicts

**Comment by LOuroboros** [comment]
> 
> 
> Looks like #1817 introduced more conflicts

Done :eyes:

**Comment by BuffelSaft** [comment]
Couple of issues so far:
- Eiscue and its form need entries in `UndoFormChange` so that it reverts into regular Eiscue after the battle ends
- Noice face Eiscue should revert into regular Eiscue at the end of the turn, not immediately after it starts hailing

**Comment by LOuroboros** [comment]
> 
> 
> Couple of issues so far:
> 
>     * Eiscue and its form need entries in `UndoFormChange` so that it reverts into regular Eiscue after the battle ends
> 
>     * Noice face Eiscue should revert into regular Eiscue at the end of the turn, not immediately after it starts hailing

Oh, I actually did add an entry for Eiscue in `UndoFormChange`, but I reverted it in one of the merges after Eduardo optimized a little how it handles the "form change on switch out" part of it :eyes:
I'll correct it, and I'll look into the other problem.

**Comment by LOuroboros** [comment]
Alright, I think it's ready for another review.

**Comment by LOuroboros** [comment]
Alright, I think this is ready for a review. I know, this was a mess where I did plenty of force pushes and I apologize for that.

**Comment by LOuroboros** [comment]
Merged with upstream to solve conflicts :eyes:

**Comment by AsparagusEduardo** [comment]
Sorry for the lateness. Please resolve conflicts.

**Comment by LOuroboros** [comment]
> Sorry for the lateness. Please resolve conflicts.

Done :eyes:

**Comment by AsparagusEduardo** [comment]
Found this edge case in which Eiscue is switched in after turn 1 of hail

Trying to be restored on its first hail:
mGBA_gRjLbJW9le

After having already been restored by a previous hail:
mGBA_w69N4JHcf7

**Comment by LOuroboros** [comment]
I re-implemented this ability in a clean copy of the Master branch, making use of the base provided by Benício Gonçalves#3454 which seems to work nice and smoothly compared to my febble implementation.

May I have permission to force push? :eyes:

**Comment by AsparagusEduardo** [comment]
> May I have permission to force push? eyes

Hmm, I think for this case I would prefer you to make a new PR. I'd like to see the differences in implementation to see if there's anything of note.

**Comment by LOuroboros** [comment]
> > May I have permission to force push? eyes
> 
> Hmm, I think for this case I would prefer you to make a new PR. I'd like to see the differences in implementation to see if there's anything of note.

Okay :eyes:

**Comment by AsparagusEduardo** [comment]
Superseded by #2255

**Pull request closed without merging**
