### PR TITLE
Fairy Lock animation fix

### LINKED ISSUE #3021: Fairy Lock's animation looks either buggy or incomplete when the Player's Pokémon uses it
Originally posted in #2845, but since it's not directly related, I decided to make a new ticket for it.

When your Pokémon uses Fairy Lock, there is no actual lock in the move's animation. Instead there's multiple small black sticks.

mGBA_20230523_181901608

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3021
The animation isn't really anything special, but at least it doesn't cause any graphical glitches.

fairy_lock

Edit: Wait, it's still bugged,

### CODE REVIEW

**Review by Bassoonian — APPROVED** [review]

**Comment by AlexOn1ine** [comment]
Egg, what is still broken about it? I've tested it and could find anything.

**Comment by AlexOn1ine** [comment]
> Egg, what is still broken about it? I've tested it and could not find anything.
> 
> /Edit: ok I see lol

This should fix it. Please don't ask why 😅
```diff
-       setalpha 8, 8
        monbg ANIM_ATK_PARTNER
+       setalpha 12, 8
```

**Comment by DizzyEggg** [comment]
Should be working now.

@AlexOn1ine  I actually did it differently. 🤔

**Review by AlexOn1ine — APPROVED** [review]
> @AlexOn1ine I actually did it differently. 🤔

Maybe I was just like and tested enough.

**Pull request merged**
