### PR TITLE
Use proper symbol name styles for Jangmo-o family

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Ho-Oh's symbols were standarized as `HoOh`, so it made sense to do the same for these two.

## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by BuffelSaft** [comment]
Should probably do this for Jangmo-o at the same time, but if you'd rather that be a separate PR this is good to go.

**Comment by AsparagusEduardo** [comment]
> Should probably do this for Jangmo-o at the same time, but if you'd rather that be a separate PR this is good to go.

For a moment I thought Jangmo-o was already handled but I was wrong. PR updated.

**Comment by BuffelSaft** [comment]
One last thing, it seems their footprints are in a different format:
```   
[SPECIES_JANGMO_O] = gMonFootprint_Jangmo_o,
[SPECIES_HAKAMO_O] = gMonFootprint_Hakamo_o,
[SPECIES_KOMMO_O] = gMonFootprint_Kommo_o,

Do you want to fix that too?

**Comment by AsparagusEduardo** [comment]
Fixed

**Review by BuffelSaft — APPROVED** [review]

**Pull request merged**
